### PR TITLE
hospital (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR restructures and inserts events related to the hospital (Spyder)
- renames spyder_hospital in spyder_candy_hospital3 (because it's in candy + addition elevator back teleport);
- renames spyder_hospital_alt in spyder_candy_hospital3_alt (because it's in candy + addition elevator back teleport);
- creates the map spyder_candy_hospital1 (new one);
- creates the map spyder_candy_hospital2 (new one);
- edits the map spyder_candy_center (enlargement of the map + elevator);
- adds NPCs for the maps above;
- adds events for the maps above;

@Sanglorian here the PR regarding the hospital, split from #1749 

**removed images readability** 
```

NPCs
Spyder Rookie:

    You look like you could use a challenge.
    Anu level 30, Galnec level 30
    Well, I didn't say it would be me.

Spyder Boss:

    You will quickly learn that you have chosen for your sparring partner the most skilled trainer in the building.
    Exclawvate level 40
    Not too shabby. I don't suppose I could recruit you for Spyder?

Spyder Boss:

    Salutations. Test your puissance against my menagerie.
    Boltnu level 30, Taupypus level 30, Snaki level 30, Galnec level 30
    Bollocks.

Spyder Rookie

    Boss says we can't help ourselves to the stashed tuxemon ... yet.
    Anu level 30, Selket level 30
    This would have been a lot easier with a Moloch or two!

Spyder Boss

    You wouldn't believe the powerful mons these suckers have handed over.
    Boltnu level 36, Snaki level 36
    You may have beaten me, but you'll never stop Spyder.

Spyder Rookie (no battle)
I don't recognize you from the induction.

Spyder Rookie:

    What happened to your uniform? Wait, imposter! Stop right there!
    Anu level 34, Taupypus level 27
    I'm going to have to report this to head office. Thanks for nothing.

Spyder Boss (looking over a box full of tuxeballs or cage of tuxemon):

    Like taking candy from a baby.
    Galnec level 36, Exclawvate level 36
    Waa!

What's the point of having so many of us stationed here. No one will get through the DNA blocker.

Spyder Rookie:

    Oi! Stop right there!
    Selket level 32, Taupypus level 32
    You may have beaten me, but there's no way you'll beat what they have cooking at HQ.

Spyder Boss (no battle):
Confiscating all the tuxemon was a waste of time. No trainer can stop the super-monsters that Spyder is breeding.

Scientist (no battle):
We have a cure, but we keep running into the Cathedral's DRM system.

Nurse (no battle):
You have to stop them! These villains have taken over the hospital, and they're stopping us from releasing the cure.
```

### CODE REVIEW

**Comment by JaskRendix** [comment]
@Sanglorian what do you think about moving the battle with Billie (I'm referring to the one in spyder_hospitall before of the cure, so it can unlock the elevator, going up to the third floor) in front of the elevator inside the center? Here:

once he did all the aardant stuff, fusion, etc., then he can unlock the elevator for the floors 1 and 2

8 NPCs (fights) in floor 1 (all the NPCs above + nurse), done
7 NPCs (fights) in floor 2 (only scientist - from the list - at the moment)

Done, all the NPCs in the list have been set in hospital1 (1st floors), now it's missing the second.
https://wiki.tuxemon.org/Hospital (updated, connection with monsters, missing NPCs, division per floors) in this way you can know what I have done and what's missing.

update:
nurse hospital 1 and scientist hospital2
(I have almost updated all the variations for scientists, nurses, spyder bosses, etc in the wiki, if you're interested in some, then let me know)

**Comment by Sanglorian** [comment]
Thanks so much @JaskRendix. That sounds good except the battle with Billie should occur after the Cure has been discovered, as the player is leaving. 

Would it be possible to have a different elevator or set of stairs, somewhere on the second floor, as the only way to access the third floor? That would make sure players have to hunt for the cure and pass through trainer battles along the way. Or if you'd prefer me to do that, let me know -- you've done so much already. 

> 8 NPCs (fights) in floor 1 (all the NPCs above + nurse), done 7 NPCs (fights) in floor 2 (only scientist - from the list - at the moment)
> 
> Done, all the NPCs in the list have been set in hospital1 (1st floors), now it's missing the second. https://wiki.tuxemon.org/Hospital (updated, connection with monsters, missing NPCs, division per floors) in this way you can know what I have done and what's missing.

Thanks! Very helpful -- I've moved some trainers to the second floor and added a few more trainers and NPCs. I think that's enough for this map. 

> update: nurse hospital 1 and scientist hospital2 (I have almost updated all the variations for scientists, nurses, spyder bosses, etc in the wiki, if you're interested in some, then let me know)

Yes, thank you -- the variety sounds good to me.

**Comment by JaskRendix** [comment]
> That sounds good except the battle with Billie should occur after the Cure has been discovered, as the player is leaving.

That's fine #1772 (tagged the PR so I can remember)

> Would it be possible to have a different elevator or set of stairs, somewhere on the second floor, as the only way to access the third floor?

Done, it's better, before the elevator was too much complicated (3 variables), now only 2. There is a stair now!

> Yes, thank you -- the variety sounds good to me.

I'm happy about it!

**Comment by JaskRendix** [comment]
@Sanglorian this is ready, replaced the screen, deleted the spyder_hospital_alt, everything centralized in one map.

When #1745 is merged, I'm going to set ready for review this one.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
