### PR TITLE
dojo (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR implements https://wiki.tuxemon.org/index.php?title=Dojo_of_the_Five_Elements
- new map dojo4 (it was planned another level);
- new action called **get_party_monster** (event action), it'll save all the ids in the party;
- upgraded **add_tech**, it was necessary because @Sanglorian needed a way to give a specific tech to certain monster;
- implemented **change_taste** (event action);

it'll follow probably another PR

regarding the missing monsters for type (2nd floor) and stats (3rd floor), I pulled some data regarding monster lv 25:
```
- hp: hampotamos, pharfan, sludgehog, baoby, eruptibus, mystikapi, baobaraffe, shnark, sharpfin, dollfin
- melee: urcine, noctalo, flambear, anoleaf, flacono, galnec, aardorn, birdling, memnomnom, nuenflu
- ranged: katacoon, nudiflot_male, vivitron, vivitrans, nudiflot_female, boltnu, vivipere, tetrchimp, hydrone, tourbidi
- speed: capiti, cowpignon, bamboon, frondly, tweesher, graffiki, sampsage, bursa, volcoli, eaglace
- armour: sludgehog, baoby, mystikapi, picc, lightmare, incandesfin, loliferno, zunna, embra, cairfrey
- dodge: tigrock, skwib, memnomnom, snarlon, cateye, drashimi, grimachin, nudiflot_male, miaownolith, nudiflot_female
- earth: sludgehog, grintot, qetzlrokilus, galnec, rockitten, cairfrey, foofle, jemuar, tumblequill, vivipere
- fire: loliferno, foxfire, criniotherme, eruptibus, medushock, embra, volcoli, merlicun, abesnaki, masknake
- water: manosting, conifrost, incandesfin, bumbulus, jelillow, noctalo, nudiflot_female, sharpfin, chillimp, nuenflu
- wood: vigueur, tourbidi, sapsnap, pairagrim, trapsnap, legko, banling, turnipper, rosarin, tarpeur
- metal: apeoro, neutrito, chrome-robo, eyenemy, bugnin, possessun, sampsack, flacono, tetrchimp, propellercat
```
most powerful monster (lv25) for each category, it can help you to choose the right ones for the missing ones (consider that some stats can be higher because of the tastes, but at the end these are on top for a reason). If you need some data, then feel free to ask (other levels).

At the moment all the monks are white, same sprite, if you want I can upload these variations:
monk_red_back - monk_orange_back - monk_green_back - monk_blue_back - monk_black_back

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thank you! 

* here, what do you mean with eg Let me tell you how Experience works. (Insert description). insert description?

When I wrote that I didn't know how the different rules of the game would work. I've filled those in now to help out! 

Morphing: Throughout their lives, most monsters pass through different stages. For example, a Rockitten may become a Rockat and then a Jemuar. This is called Morphing. Most Morphing occurs because a monster reaches a certain level, but there are other ways that Morphing can occur, like Dollfin becoming Bigfin when exposed to Sweet Sand. 

Experience: The idea for Experience to increase Stats has been dropped, so I replaced it with someone to talk about Stats instead. 

Stats: Monsters have six Stats: HP, Melee, Ranged, Armor, Dodge and Speed. HP determines how much Damage they can take from attacks before passing out. Melee determines how much Damage their melee and touch attacks do. Ranged determines how much Damage their ranged and reach attacks do. Armor reduces Damage from melee and reach attacks. Dodge reduces Damage from ranged and touch attacks. Whichever monster has the higher Speed acts first in battle. 

Tastes: Every monster has two Tastes: Warm and Cold. A Warm Taste makes the monster 10 percent better in one Stat: Speed for Peppy Taste, Melee for Salty Taste, Armor for Hearty Taste, Ranged for Zesty Taste and Dodge for Refined Taste. A Cold Taste makes the monster 10 percent worse in one Stat: Speed for Mild Taste, Melee for Sweet Taste, Armor for Soft Taste, Ranged for Flakey Taste and Dodge for Dry Taste. 

Techniques: In combat, monsters can choose from up to four techniques that they know. Techniques have an accuracy, which determines how likely they are to occur. If a technique has a Power, that determines how much Damage it does. Some techniques impose a condition on the user or the target, or both - and the technique's Potency determines how likely that is to occur. Some techniques, once used, take a while to become available again.

* Trainers

Can remove Exapode from Toph. I think the levels you've chosen are good for now - we can always tweak later. 

I've added monsters to Wan, Yangchen and Iroh (and one to Kataro although I imagine we'll want to add more later). 

---

Got to run now, but will tackle your notes on level 3 onwards another day!

**Comment by JaskRendix** [comment]
No problem @Sanglorian 
I noticed you updated the wiki too, thank you so much
Everything updated is done, waiting for the rest. Fixed the monsters and techniques names in the wiki too.

----

@Sanglorian you need to reconsider this number here:
`<property name="act12" value="add_monster sapsnap,20,spyder_dojo_yangchen,27,10"/>`
the **27**, the experience modifier is too much.

I fought with a rockitten lv5 vs cardiling lv20 (full of hibernates, just testing don't worry)
I won, rockitten jumped at lv22!
I fought again with rockitten lv 22 vs djinnbo lv 20
I won, rockitten jumped at lv28!

I advise you to lower the exp mod (from 5 to 10), pump it to 15 (max 17/18) for "boss" fight (eg like Billie, Wan, Tu, etc.).
We can do it, we can mass replace to a number (eg 8) really easily and then edit the single ones specifically (like Billie, etc)

**Comment by Sanglorian** [comment]
Thanks again! I've updated the Dojo entry with new details of monsters for the trainers on levels 3 and 4. 

Those colour changes for the monks look good, I think that's a nice idea to differentiate them.

I've removed Sudden Valley. Scope and Panjandrum would be new techniques with new effects, we can ignore them for now -- but I'm collecting [some ideas](https://wiki.tuxemon.org/Other_technique_ideas) (new and old) for additional technique effects separately on the wiki so if at a later time we'd like to implement them, all the details are there. 

> @Sanglorian you need to reconsider this number here: `<property name="act12" value="add_monster sapsnap,20,spyder_dojo_yangchen,27,10"/>` the **27**, the experience modifier is too much.
> 
> I fought with a rockitten lv5 vs cardiling lv20 (full of hibernates, just testing don't worry) I won, rockitten jumped at lv22! I fought again with rockitten lv 22 vs djinnbo lv 20 I won, rockitten jumped at lv28!
> 
> I advise you to lower the exp mod (from 5 to 10), pump it to 15 (max 17/18) for "boss" fight (eg like Billie, Wan, Tu, etc.). We can do it, we can mass replace to a number (eg 8) really easily and then edit the single ones specifically (like Billie, etc)

You've been doing a lot more testing than me on this, so I trust your judgement -- lowering it to 5 and then setting it to 15 for boss fights sounds good to me.

**Comment by JaskRendix** [comment]
Ok, that's perfect, last question before setting ready for review this PR.

What do you mean here with starter?

**STARTER level 35, [Eyesore](https://wiki.tuxemon.org/Eyesore) level 35, [Cardiwing](https://wiki.tuxemon.org/Cardiwing) level 35, [Viviphyta](https://wiki.tuxemon.org/Viviphyta) level 35**

In the Dojo there is the sharing of Tuxepedia between Billie and the player. 
Starter is Dollfin lv35?

All the fights with Billie:
```    
Paper Town
add_monster dollfin,5,spyder_billie,27,10
    
Route 2
add_monster dollfin,6,spyder_route2_billie,27,10
add_monster eyenemy,6,spyder_route2_billie,27,10
add_monster cardiling,3,spyder_route2_billie,27,10

Dojo
add_monster dollfin/sharpfin/bigfin,35,spyder_route2_billie,27,10 <------- need to add this?
add_monster eyesore,35,spyder_dojo_billie,27,10
add_monster cardiwing,35,spyder_dojo_billie,27,10
add_monster viviphyta,35,spyder_dojo_billie,27,10
    
Hospital Alt
add_monster dollfin/sharpfin/bigfin,40,spyder_route2_billie,27,10 <------- need to add this too?
add_monster viviphyta,40,spyder_hospital_billie,27,10
add_monster eyesore,40,spyder_hospital_billie,27,10
add_monster cardinale,40,spyder_hospital_billie,27,10
```

**Comment by Sanglorian** [comment]
> Ok, that's perfect, last question before setting ready for review this PR.
> 
> What do you mean here with starter?
> 
> **STARTER level 35, [Eyesore](https://wiki.tuxemon.org/Eyesore) level 35, [Cardiwing](https://wiki.tuxemon.org/Cardiwing) level 35, [Viviphyta](https://wiki.tuxemon.org/Viviphyta) level 35**
> 
> In the Dojo there is the sharing of Tuxepedia between Billie and the player. Starter is Dollfin lv35?
> 
> All the fights with Billie:
> 
> ```
> Paper Town
> add_monster dollfin,5,spyder_billie,27,10
>     
> Route 2
> add_monster dollfin,6,spyder_route2_billie,27,10
> add_monster eyenemy,6,spyder_route2_billie,27,10
> add_monster cardiling,3,spyder_route2_billie,27,10
> 
> Dojo
> add_monster dollfin/sharpfin/bigfin,35,spyder_route2_billie,27,10 <------- need to add this?
> add_monster eyesore,35,spyder_dojo_billie,27,10
> add_monster cardiwing,35,spyder_dojo_billie,27,10
> add_monster viviphyta,35,spyder_dojo_billie,27,10
>     
> Hospital Alt
> add_monster dollfin/sharpfin/bigfin,40,spyder_route2_billie,27,10 <------- need to add this too?
> add_monster viviphyta,40,spyder_hospital_billie,27,10
> add_monster eyesore,40,spyder_hospital_billie,27,10
> add_monster cardinale,40,spyder_hospital_billie,27,10
> ```

Good catch! 

For now, Billie can be given Bigfin. Eventually, I would like to be able to set her monster based on which monster the player picks -- I'll make an issue about it.

**Comment by Sanglorian** [comment]
> Ok, that's perfect, last question before setting ready for review this PR.
> 
> What do you mean here with starter?
> 
> **STARTER level 35, [Eyesore](https://wiki.tuxemon.org/Eyesore) level 35, [Cardiwing](https://wiki.tuxemon.org/Cardiwing) level 35, [Viviphyta](https://wiki.tuxemon.org/Viviphyta) level 35**
> 
> In the Dojo there is the sharing of Tuxepedia between Billie and the player. Starter is Dollfin lv35?
> 
> All the fights with Billie:
> 
> ```
> Paper Town
> add_monster dollfin,5,spyder_billie,27,10
>     
> Route 2
> add_monster dollfin,6,spyder_route2_billie,27,10
> add_monster eyenemy,6,spyder_route2_billie,27,10
> add_monster cardiling,3,spyder_route2_billie,27,10
> 
> Dojo
> add_monster dollfin/sharpfin/bigfin,35,spyder_route2_billie,27,10 <------- need to add this?
> add_monster eyesore,35,spyder_dojo_billie,27,10
> add_monster cardiwing,35,spyder_dojo_billie,27,10
> add_monster viviphyta,35,spyder_dojo_billie,27,10
>     
> Hospital Alt
> add_monster dollfin/sharpfin/bigfin,40,spyder_route2_billie,27,10 <------- need to add this too?
> add_monster viviphyta,40,spyder_hospital_billie,27,10
> add_monster eyesore,40,spyder_hospital_billie,27,10
> add_monster cardinale,40,spyder_hospital_billie,27,10
> ```

Good catch! 

For now, Billie can be given Bigfin. Eventually, I would like to be able to set her monster based on which monster the player picks -- I'll make an issue about it (#1755)

**Comment by JaskRendix** [comment]
@Sanglorian seen and replied. 

Ready to go, I'm going to fix the starter in #1757 and I'm going to open a separate PR for the monk sprites (various colors).

**Review by kerizane — APPROVED** [review]

**Pull request merged**
