### PR TITLE
Cotton Town + Omnichannel (event Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR fixes some events in the Spyder campaign (Cotton Town)

This one: https://wiki.tuxemon.org/Cotton_Town#Event_5
Screenshot from 2023-04-11 16-39-30
in this way it gives correctly the phone + basic apps 

This one: https://wiki.tuxemon.org/Cotton_Town#F._Omnichannel_Building
before there was the guy blocking the access
Screenshot from 2023-04-11 16-25-32
removed and brought the event inside (foyer), so as soon as the player enters
Screenshot from 2023-04-11 16-10-51
this will happen until the hospital, then after the hospital, there will be the fight (as per wiki with Rabbitosaur)
Screenshot from 2023-04-11 16-25-47

@Sanglorian Let me know if it's ok. So it respects the wiki.

### CODE REVIEW

**Comment by JaskRendix** [comment]
@Sanglorian if you have some dialogues we can fill of NPC Omnichannel 2 and 3. It looks pretty empty.

**Comment by JaskRendix** [comment]
@Sanglorian updated the page https://wiki.tuxemon.org/Omnichannel_HQ, divided for floor, etc. (like the hospital)

It contains the NPCs inserted, but there are missing details (like dialogues and monsters), sou you can easily complete, then I can put everything in the PR. By the way, nice Carnegie, you can create Peale, Hill, Powers, Schwartz, Allen and Bettger! Same pond!

Let me know if it's ok, or if you want to only 3 NPC inside (it put 6 per floor, but these aren't mandatory, unless the player needs to recover something from each floor).
Let me know.

**Comment by JaskRendix** [comment]
**removed images for readability**

@Sanglorian updated the page https://wiki.tuxemon.org/Omnichannel_HQ, divided for floor, etc. (like the hospital)

It contains the NPCs inserted, but there are missing details (like dialogues and monsters), sou you can easily complete, then I can put everything in the PR. By the way, nice Carnegie, you can create Peale, Hill, Powers, Schwartz, Allen and Bettger! Same pond!

Some interesting NPC names: Crane, Lewis, Heidenstam, Morehouse, Broer, Marciano, Dempsey and Tohei!

Let me know if it's ok, or if you want to only 3 NPC inside (it put 6 per floor, but these aren't mandatory, unless the player needs to recover something from each floor).
Let me know.

**Comment by Sanglorian** [comment]
Thank you! I've added some more NPCs. That's a great list of names, too! 

I was also wondering if we can make it more of a maze: 
* turn the staircase on the 3rd floor to the Radio Tower into an elevator that requires a key item (Spyder Pass)
* put the Spyder Pass behind a screen wall on the ground floor
* put the computer to turn off the screen wall on the 1st floor. 

So players would have to retrace their steps, exploring more of the building. 

What do you think? Is it too complicated or do you think it's doable?

**Comment by JaskRendix** [comment]
@Sanglorian that's a pity to have the 3rd floor completely empty, but it's fine.

> What do you think? Is it too complicated or do you think it's doable?

it's doable, but we need to merge #1774 first. 

> turn the staircase on the 3rd floor to the Radio Tower into an elevator that requires a key item (Spyder Pass)

done

> put the Spyder Pass behind a screen wall on the ground floor

yes, the nurse gives the spyder_pass. Added spyder_pass item.

> put the computer to turn off the screen wall on the 1st floor.

done, pc event done, now we need only the PR merged to complete everything.

> Random encounters are [Dark Robo](https://wiki.tuxemon.org/Dark_Robo) and [Xeon-2](https://wiki.tuxemon.org/Xeon-2), which are not catchable. "Not a tuxemon!" flashes up as the error.

If with random encounter you refer to the grass event (eg any route), then it would require an additional modification.

Level? 30/35/40? Let me know.
If you agree, then I would trigger those after deactivating the door from the PC (the one that gives access to the spyder pass). It reminds me Jurassic Park 1 with the raptors.

**Comment by Sanglorian** [comment]
Thanks for all those changes! 

> > Random encounters are [Dark Robo](https://wiki.tuxemon.org/Dark_Robo) and [Xeon-2](https://wiki.tuxemon.org/Xeon-2), which are not catchable. "Not a tuxemon!" flashes up as the error.
> 
> If with random encounter you refer to the grass event (eg any route), then it would require an additional modification.

Yes, that's what I had in mind -- should I create an issue for it?

> Level? 30/35/40? Let me know. If you agree, then I would trigger those after deactivating the door from the PC (the one that gives access to the spyder pass). It reminds me Jurassic Park 1 with the raptors.

Level 30 I think. Thanks -- good idea to only trigger it after deactivating the doors.

**Comment by JaskRendix** [comment]
Yes, that's what I had in mind -- should I create an issue for it?

No problem, opened #1778 to fix it.

**Comment by JaskRendix** [comment]
@Sanglorian 

> Yes, that's what I had in mind -- should I create an issue for it?
> Level 30 I think.

No problem, opened #1778 to fix it.

update: there was too much difference in style, I standardized everything (as omnichannel 3) so the style is contiguous and there are no differences, tell me if it's ok for you (so I'm going to update the wiki too).

https://wiki.tuxemon.org/Omnichannel_HQ
spyder_omnichannel4 - spyder_omnichannel2 - spyder_omnichannel1

**Comment by Sanglorian** [comment]
Same style across all floors looks good to me!

**Comment by JaskRendix** [comment]
@Sanglorian 

> Same style across all floors looks good to me!

Done and updated the new versions.

> Level 30 I think. Thanks -- good idea to only trigger it after deactivating the doors.

Implemented, last thing is the screen and then everything is done.

**Comment by JaskRendix** [comment]
@Sanglorian 

> Same style across all floors looks good to me!

Done and updated the new versions.

> Level 30 I think. Thanks -- good idea to only trigger it after deactivating the doors.

Implemented.
Screenshot from 2023-04-24 13-36-21
Screenshot from 2023-04-24 13-40-17
we need to put a dialogue on the controller (right of the player), it's intuitive for the player trying to unlock from there. At the moment the dialogue says: **Screen activated!**, but I'm not so "enthusiast" about this formula.

Same for the elevator at lv4 (access radiotower), both left and right, two dialogues:
Screenshot from 2023-04-24 13-52-39
the dialogues says: **It requires the Spyder Pass!**
then
the dialogues says: **Spyder Pass scanned, elevator activated!**

same as above, if anyone has something better, then feel free to suggest.

**Comment by Sanglorian** [comment]
Thanks @JaskRendix -- and that dialogue looks good to me.

**Comment by JaskRendix** [comment]
@Sanglorian ok, so here it's done, ready to go. Let me know what happens after Omnichannel, I'll check the wiki.
You talked about Wallet Garden, but it's a side quest like the Dojo?

**Review by kerizane — APPROVED** [review]

**Comment by Sanglorian** [comment]
> @Sanglorian ok, so here it's done, ready to go. Let me know what happens after Omnichannel, I'll check the wiki. You talked about Wallet Garden, but it's a side quest like the Dojo?

Thank you! After Omnichannel the Spyder campaign is basically over! 

The Walled Garden can be developed as a "post-game" option, for people who want to keep playing. But I don't have any plans to write it or implement it -- if you'd like to, please go ahead!

**Pull request merged**
