### PR TITLE
Create economies, and functions to lookup item price and cost

### PR DESCRIPTION
**Pull request by ultidonki**
This is part 1 of adding buying/selling to shops in tuxemon, it's split off from PR #1094 - I'm splitting that PR into smaller commits so they're easier to test and understand. (This one is still big, it's about 50% of the lines of code of the original PR!)

This PR only adds economies, as preparation for the buying/selling features which I'll add in later PR's. 
These set buy/sell prices/costs on items, which will be used later by shops to set prices. 
It allows economies to be loaded from .json, and it allows economies to be set on an NPC using a set_economy action.
At the minute, the set_economy action doesn't do anything, but it'll be used later when I change the shops code. 

You can't actually use the economies in shops yet, so I've added some unit tests around the price/cost lookup functions.

I've also generalized the price/cost lookup functions into a lookup_item_field(item_slug, field) function - which was requested on a comment in #1094 
And I've removed the ability to recursively look up parent economies, which was requested in #429 - I want to keep each PR as simple as possible. I can add that again in a later PR.

### CODE REVIEW

**Comment by xirsoi** [comment]
I'd like to present an alternative orientation that would require minimal changes to your implementation.
What if an Economy held price *modifiers* rather than prices? These modifiers would be applied to the base price, found in the item definition.

I'd love to get input from @Qiangong2 and @Sanglorian (or others) on this idea.

Otherwise this looks great!

**Comment by ultidonki** [comment]
Sure, that's fine to discuss putting it on items, either way sounds good to me! I can make the changes if we decide to go that way. Thanks for looking at this!

**Comment by Qiangong2** [comment]
In Pokemon, ceetain events or items can lower prices for a short span of time. With modifiers, we could attribute them to items which would give us more flexibility on pricing.

**Review by bitcraft — DISMISSED** [review]
looks good to me.  this is a nice start.

**Review by bitcraft — APPROVED** [review]

**Pull request merged**
