### PR TITLE
fix KeyItem

### PR DESCRIPTION
**Pull request by JaskRendix**
PR addresses #1335

### CODE REVIEW

**Comment by kerizane** [comment]
Thanks, but we already have the logic implemented for quest, so is this change required? Probably some of the  items just need to be configured correctly as quest items.

Also, is this valid python? Two if statements look suspicious...

**Review by kerizane — CHANGES_REQUESTED** [review]
Not convinced this is necessary or correct.

**Comment by Sanglorian** [comment]
I think the wiki has confused things by having Story Items (a category) and key item (a binary variable). If "quest item" is a variable, then we can just use that instead of key item, and rename the field in the wiki.

But not all key items are Story Items, which is I think why @JaskRendix has set up this separate variable.

**Comment by JaskRendix** [comment]
No problem in closing the PR, I got confused because the issue was still open. I tried to upgrade the original statement, but I wasn't able to do it. If it's ok already, then please close the issue.

**Pull request closed without merging**
