### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Qiangong2**
Minor fixes to the professor's house

### CODE REVIEW

**Comment by Qiangong2** [comment]
@bitcraft Have you reviewed this at all?

**Comment by bitcraft** [comment]
I am sorry, I have not had any free time to review PR's or hack on Tuxemon.  I will look into it when I have more time.

**Comment by ShadowApex** [comment]
Hey @Qiangong2 

Sorry for such a long delay. The reason I haven't accepted this pull request yet is because we have a few other giant pull requests pending, which might conflict with these fixes. I want to ensure that by accepting either of these requests, we don't have any issues.

**Comment by Qiangong2** [comment]
Okay, no problem.

**Comment by ShadowApex** [comment]
Hi @Qiangong2 ,

Thanks again for these changes. I had time to review the other large pending pull request, and there's still some things it needs before pulling it in, so I'm going to go ahead and merge these changes in. "Tuxemon Professor's House" is definitely better than "Generic Professor's House" :P 

Thanks!

**Pull request merged**
