### PR TITLE
mansion (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR addresses the Mansion.

@Sanglorian updated wiki (https://wiki.tuxemon.org/Mansion)

- there was a tennis player, but I have no idea where do you want it. Top?
- regarding the basement, numbers are also trainers? if yes, then I can add the events without issues.
- I guess the drinking buddy + captain need to be removed, right? If yes, tell me where do you want to move it (or simply delete or recycle as trainers).

let me know about the npcs, monsters, dialogues, etc.
if you need any help (dialogues, etc), let us know

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thank you! The numbers are meant to be items -- we can ignore them for now. 

I've filled out the list of trainers and NPCs on the [Mansion wiki page](https://wiki.tuxemon.org/Mansion). The exact locations aren't too important, though, so I've left it up to you to place them where you like -- but if that's a drag, let me know and I can assign them.

**Comment by JaskRendix** [comment]
> The exact locations aren't too important.

That's perfect, so we can also replace the maps in the wiki.

**Comment by JaskRendix** [comment]
@Sanglorian 
everything is done
added dojo pass item (let me know if we need to block the entrance to the dojo without the pass)
added some sprites (rogue and magician, because there were NPCs identical)

last point, do you agree to change this into this? so we can maintain the stone walls (like mansion and basement), wood floor is ok because it's the first floor (lighter than stone).
spyder_mansion_top
spyder_mansion_top

**Comment by Sanglorian** [comment]
> @Sanglorian everything is done added dojo pass item (let me know if we need to block the entrance to the dojo without the pass) added some sprites (rogue and magician, because there were NPCs identical)

Oh yes please, if someone can block the Dojo entrance and say "I'm sorry, only experienced trainers are allowed past this point." Or if they have the Dojo pass, they move to the side and say "Welcome master." 

> last point, do you agree to change this into this? so we can maintain the stone walls (like mansion and basement), wood floor is ok because it's the first floor (lighter than stone). spyder_mansion_top spyder_mansion_top

Sure thing! Good idea to make it more realistic.

**Comment by JaskRendix** [comment]
@Sanglorian done, monk block the access, but with the dojo pass you'll find the monk in the contiguous tile.

**Comment by Sanglorian** [comment]
> @Sanglorian done, monk block the access, but with the dojo pass you'll find the monk in the contiguous tile.

Thanks :D

**Comment by JaskRendix** [comment]
@Sanglorian I forgot to ask.
Trainers, do they need to disappear once fought?
(it regards not only Mansion, but also Omnichannel, Greenwash and Hospital)
I ask because I noticed that the old NPCs in Omnichannel where set to disappear once fought.
Let me know.

**Comment by Sanglorian** [comment]
Trainers should normally stay after being defeated. I think if any disappear that's my mistake -- except if it's Omnichannel NPCs, maybe I made the CEO and so on disappear because their scheme is over (the player can pretend they were arrested or whatever).

**Comment by JaskRendix** [comment]
@Sanglorian Excellent! Good to know!

Regarding the drunk people in the Mansion, those are still there, if it's ok for you, then we can merge it.

You can check also https://wiki.tuxemon.org/Side_Route_A (from what I understood there are fights here too), so we can fix this piece in another PR.

**Comment by Sanglorian** [comment]
Thanks, the drunk people are good to keep - I've added them to the wiki to keep track of them.

Good reminder on Side Route A, I forgot about them. I'll try to fill them in tomorrow.

**Comment by Sanglorian** [comment]
I've added the NPCs for [Side Route A](https://wiki.tuxemon.org/Side_Route_A) :)

These ones were fun!

**Comment by JaskRendix** [comment]
@Sanglorian thank you so much! I'm going to open another PR!
I've added here your last changes regarding man moon -> rocker

**Review by kerizane — APPROVED** [review]

**Pull request merged**
