### PR TITLE
greenwash hq (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR addresses Greenwash HQ

@Sanglorian updated the wiki here: https://wiki.tuxemon.org/Greenwash_HQ (division floors, etc). Originally talked about 16 NPCs, so I added a bunch in each map. 

Just one thing, regarding Looten, inside the PO there are:
```
msgid "spyder_greenwash_looten1"
msgstr "Well, I guess fusion technology isn't quite there yet. We've been working on it for years!"
msgid "spyder_greenwash_looten2"
msgstr "Here's the closest we've come -- it's a cute fusion of an ant and an Aardorn. Not exactly the ultimate killing machine Omnichannel wanted us to create. I mean … uh! You didn't hear that from me."
```
but there is no trace about **spyder_greenwash_looten2** in the maps, I guessed you planned a fight.

Let me know.

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thank you! I did plan a fight with Looten, but forgot to include it. I've updated [the wiki page](https://wiki.tuxemon.org/Greenwash_HQ) with new NPCs and a clearer plan.

**Comment by JaskRendix** [comment]
@Sanglorian 

Almost everything is done. If you can complete the details of:
https://wiki.tuxemon.org/Bearloch
https://wiki.tuxemon.org/Rocktot
https://wiki.tuxemon.org/Foxko
https://wiki.tuxemon.org/Agnsher

then I can generate a bunch of techniques and add the 4 threats inside the PR.

**Comment by JaskRendix** [comment]
@Sanglorian Fossilisator is done, but you need to tell me the level.

The player got a rhincus or a shammer, but level? Rhincus/Shammer level20/30/something else?
From what I understood the player got a fossil in the Tunnel, would you like to base the fossil in base at the gender?
if female -> shammer and if male -> rhincus?
Something like this, a precise condition can make you get one or the other.
We can use gender, night/day or seasons (like in the games)

**Comment by Sanglorian** [comment]
> @Sanglorian Fossilisator is done, but you need to tell me the level.
> 
> The player got a rhincus or a shammer, but level? Rhincus/Shammer level20/30/something else? From what I understood the player got a fossil in the Tunnel, would you like to base the fossil in base at the gender? if female -> shammer and if male -> rhincus? Something like this, a precise condition can make you get one or the other. We can use gender, night/day or seasons (like in the games)

Thanks heaps! Level 30 sounds about right. 

I was just thinking of making both available, as items hidden around the Tunnel. But we could also limit them to one per play through. Might make them more exclusive! Let's say Shammer Fossil available at night (9pm to 9am) and Rhincus Fossil available the rest of the time.

**Comment by JaskRendix** [comment]
@Sanglorian 

> I was just thinking of making both available, as items hidden around the Tunnel. But we could also limit them to one per play through. Might make them more exclusive! Let's say Shammer Fossil available at night (9pm to 9am) and Rhincus Fossil available the rest of the time.

Ok, I asked because there wasn't the option if the player had two fossils, but I added it (both in the PR and in the wiki). 
To add the items as soon as the other PR gets merged.

Here everything is ready to go.
As soon as it gets merged the threats PR #1779, I'm going to run some tests. If it's ok, then I'm going to set ready for merging.

**Comment by JaskRendix** [comment]
Ok, testing done, ready to go.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
