### PR TITLE
teleport + various

### LINKED ISSUE #2304: The game crashed when entering the building.
**Describe the bug**
I loaded one of my saves, but the game crashed when I entered the building.
**To Reproduce**
1. Started a new game.
2. Saved the progress near a building.
3. Exited and re-entered the game.
4. Loaded the save and attempted to enter the building.
5. The game crashed.

**Expected behavior**
The game should not crash; instead, it should continue to run smoothly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Python Version 3.12.2

**Additional context**
If before entering the building, I navigate to another outdoor scene and then return, upon re-entering the building, the game does not crash.

### LINKED ISSUE #2311: Game crashes if you sell a tuxemon + 2 dialog bugs
(I'm currently playing through both campaigns and trying to see how many bugs there are, to see if we can release a new version yet, so I'll be posting a bunch of small bugs if I find any, if that's OK:)

1. Spyder Campaign, spyder_healing_center.tmx - If you sell a tuxemon to the shady guy, and accept the 250 moneys, the game crashes. 

Traceback (most recent call last):
  File "/home/src/games/tuxemon_dev/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/home/src/games/tuxemon_dev/tuxemon/main.py", line 90, in main
    client.main()
  File "/home/src/games/tuxemon_dev/tuxemon/client.py", line 301, in main
    update(clock_tick)
  File "/home/src/games/tuxemon_dev/tuxemon/client.py", line 346, in update
    self.event_engine.update(time_delta)
  File "/home/src/games/tuxemon_dev/tuxemon/event/eventengine.py", line 359, in update
    self.update_running_events(dt)
  File "/home/src/games/tuxemon_dev/tuxemon/event/eventengine.py", line 450, in update_running_events
    action.start()
  File "/home/src/games/tuxemon_dev/tuxemon/event/actions/modify_money.py", line 64, in start
    raise AttributeError(f"{wallet}'s doesn't have {abs(amount)}")
AttributeError: bill_cathedral's doesn't have 250

Also, I wasn't expecting it to be able to let me sell my only tuxemon? I was expecting it to say eg. "You cannot sell your only Tuxemon! Come back when you have more!" or something.

2. When talking to the nurse in the same map, the following dialogue appears:
tuxemon_bug_1
EDIT: I only had 1 tuxemon at the time, and it might have been at full health, if that helps.
EDIT2: It only happened the first time I used the health center. After that (After I got the Nu Phone, I think?), the nurse always says "That will be $0", however the Cathedral Bill increases by $100 each time. Expected nurse to say "That will be $100", and the Cathedral bill to increase by the same amount.

3. When examining the radio in Billie's room, spyder_paper_rival_bedroom.tmx, If it's nighttime, 2 dialogue boxes played: Dawn and Night. 
(Expected only Night to play)
 
:smiley_cat:

### LINKED ISSUE #2314: Screen goes black if you're defeated on Route 3
**Describe the bug**
When I was defeated in Route 3 (`mods/tuxemon/maps/spyder_route3.tmx`), the screen goes black and never comes back.
The command-line still works: After typing 'whereami', it responds `spyder_leather_town.tmx`, which was the map I was just on previously.
I was expecting to go to the spyder_health_center inside leather town. (I was also expecting the screen to go back to normal after turning black.)

**To Reproduce**
- Go to Leather town (`maps/spyder_leather_town.tmx`)
- Walk up to Route 3
- Start a battle and let all your tuxemon be defeated. 
- After the battle ends, you'll see about 0.5 seconds of the Route 3 map again, it will fade to black and stay that way.

Here's a save game where I can reproduce the bug, the player is at the top of Leather Town:
[slot3.zip](https://github.com/Tuxemon/Tuxemon/files/15380148/slot3.zip)
Walk up, and you'll be on the Route 3 map. 
I got defeated twice by the 'Weaver' NPC on this map (looks like a knight) but it probably happens if you're defeated by anything I'm guessing (but I could be wrong). Both times, the screen went black, but the \command-line still worked.

It didn't happen on any of the other maps, which is why I think the problem is in `mods/tuxemon/maps/spyder_route3.tmx`.

### LINKED ISSUE #2318: After battling a trainer on Route 3, the game crashes.
**Describe the bug**
While updating and optimizing the Chinese translation for Tuxemon, I've been searching for bugs by exploring every corner of the game, entering each house, talking to every NPC, and not missing out on any battles. When I reached Route 3, a trainer blocked my path. After engaging and defeating the trainer in battle, the game immediately crashed.

**To Reproduce**
1. Proceed to Route 3.
2. Battle and defeat the trainer as depicted.
3. Encounter a game crash.
**Expected behavior**
The game should not crash but rather proceed without issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Python Version 3.12.3

**Additional context**
I have also uncovered some other bugs, which I will report later in separate issues.

### PR DESCRIPTION
**Pull request by JaskRendix**
PR:

- fix #2314 - the issue was related to the fact that the monsters were healed in the town (for free) by the woman; I needed to add some exceptions inside the YAML file, in this way the player will be teleported back to the woman (or inside the cafes or where there is some exceptional healing);
- related to #2311 fixes "Also, I wasn't expecting it to be able to let me sell my only tuxemon? I was expecting it to say eg. "You cannot sell your only Tuxemon! Come back when you have more!" or something." , shady guy isn't supposed to appear if there is only 1 monster in the party;
- related to #2311 fixes "When examining the radio in Billie's room, spyder_paper_rival_bedroom.tmx, If it's nighttime, 2 dialogue boxes played: Dawn and Night.";
- fix #2304 - this was crazy because the crash was caused by a NPC walking (the monk walking among the buddha statues), it was necessary to add inside "transition_teleport" some lines to remove all the NPCs;
- specifies the gender in Billie party from here (https://github.com/Tuxemon/Tuxemon/pull/2286#issuecomment-2089586828 by @Sanglorian in response to https://github.com/Tuxemon/Tuxemon/pull/2286#issuecomment-1973502704);
- fix an error in **spyder_candy_cafe.tmx**, it was defined the wrong location;
- updates [Wallow](https://wiki.tuxemon.org/index.php?title=Wallow&curid=4824&diff=29694&oldid=28080) technique as per Tuxepedia;
- fix #2318 there was an issue related to modfiy_money, it was triggering an attribute error if the amount is more than the one in the wallet (eg wallet 100, amount - 200 -> crash), now it'll simply return 0; consequently I fixed the test too (it will fix also the other part of fix #2311);
- adds the nurse in the citypark as requested by @ultidonki and confirmed by @Sanglorian in #2313, it'll simply say: "Hey, you look tired. Let me help you feel better!";

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks heaps!

**Comment by Davidliang11292** [comment]
Thanks!

**Review by Davidliang11292 — COMMENTED** [review]
Thank you very much! I accidentally found out that I have the authority to approve it, may I proceed to do so? (If I have done anything wrong, please accept my apologies in advance.)

**Comment by ultidonki** [comment]
Thanks for this, @JaskRendix - I've tested this and almost completed Route 3 with the fixes, Wallow is much better too :smile:

**Review by kerizane — APPROVED** [review]

**Pull request merged**
