### PR TITLE
Route A (Spyder) & Cotton Tunnel (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR addresses side Route A (https://wiki.tuxemon.org/Side_Route_A)
- adds NPCs;
- adds trainer battles;
- adds some new sprites (florist_blue, florist_brown and florist_black) -> because it's pretty annoying to see 3/4 identical sprites inside a map;
- adds cotton tunnel encounter.json;

@Sanglorian regarding Billie, I guess you need to fix the levels.
You put
- STARTER level 14, [Eyenemy](https://wiki.tuxemon.org/Eyenemy) level 12, [Cardiling](https://wiki.tuxemon.org/Cardiling) level 12

but looking at the resume of the battles with Billie here: https://wiki.tuxemon.org/Rival_Billie
it would be lower than Route4

- STARTER level 18, [Cardiwing](https://wiki.tuxemon.org/Cardiwing) level 16, [Eyesore](https://wiki.tuxemon.org/Eyesore) level 16, [Viviphyta](https://wiki.tuxemon.org/Viviphyta) level 16

let me know how do you want to fix it

### CODE REVIEW

**Comment by Sanglorian** [comment]
> @Sanglorian regarding Billie, I guess you need to fix the levels. You put
> 
>     * STARTER level 14, [Eyenemy](https://wiki.tuxemon.org/Eyenemy) level 12, [Cardiling](https://wiki.tuxemon.org/Cardiling) level 12
> 
> 
> but looking at the resume of the battles with Billie here: https://wiki.tuxemon.org/Rival_Billie it would be lower than Route4
> 
>     * STARTER level 18, [Cardiwing](https://wiki.tuxemon.org/Cardiwing) level 16, [Eyesore](https://wiki.tuxemon.org/Eyesore) level 16, [Viviphyta](https://wiki.tuxemon.org/Viviphyta) level 16
> 
> 
> let me know how do you want to fix it

Thanks, good spotting. Have bumped up the numbers in the Side Route A encounter a little.

**Comment by JaskRendix** [comment]
Thank you!

**Comment by JaskRendix** [comment]
@Sanglorian Thank you

unrelated question: 
since we have fixed the Dragon's Cave with Drokoro, the [Cotton Tunnel](https://wiki.tuxemon.org/Cotton_Tunnel) is supposed to be empty? Maybe you planned trainers fights + wild encounters (level 35/40). Let me know.

**Comment by Sanglorian** [comment]
> @Sanglorian Thank you
> 
> unrelated question: since we have fixed the Dragon's Cave with Drokoro, the [Cotton Tunnel](https://wiki.tuxemon.org/Cotton_Tunnel) is supposed to be empty? Maybe you planned trainers fights + wild encounters (level 35/40). Let me know.

Good point. I think let's leave the NPCs at just the three that are already there, but some random encounters could be a good opportunity to add some monsters that otherwise don't appear. I've [updated the wiki](https://wiki.tuxemon.org/Cotton_Tunnel).

**Comment by JaskRendix** [comment]
@Sanglorian done

**Review by kerizane — APPROVED** [review]

**Pull request merged**
