### PR TITLE
Create locale_check.py

### PR DESCRIPTION
**Pull request by airon90**
Initial commit. As long as I cannot really contribute in Tuxemon development, I prefer to do something related to translations. 
This script is a bit useful to easily check wether the translation is up-to-date. By now it can be done manually, but in the future maybe this script could be more useful. As of now, it just check online translations. It could be improved by implementing file reading, in case of ongoing offline translation. Every function is explained, one is not working, maybe because I'm stupid.
Simply reject this file if you don't find it useful at all! At least I did some exercise in Python ;)

### CODE REVIEW

**Comment by AndyMender** [comment]
I am just going to link issue #462 here, since those seem related. For now I am fixing some path issues in `tuxemon/core/prepare.py` and `tuxemon/core/platform/__init__.py `, but then intended to seriously overhaul the translation system (as mentioned in the linked issue).

If this gets merged, it might useful to the translation system as such :).

**Comment by airon90** [comment]
Thank you! I didn't know about the issue. My script is very simple, it may be badly coded. I tried to explain as much as I can in the doc. I hope it will be useful to the development, as long as translations are manually managed by now.

**Comment by bitcraft** [comment]
Looks well documented, not too bad.  Code quality isn't absolutely the most important thing....being outside of that game means some minor issues can be tolerated....so no worried if you are learning.  Have you compared it to our existing tools here? https://github.com/Tuxemon/Tuxemon/tree/development/tests/interactive/locale

https://github.com/Tuxemon/Tuxemon/blob/development/tests/interactive/locale/verify_master_locale.py
This will go through all our JSON DB and look for strings missing from the english (master) locale

https://github.com/Tuxemon/Tuxemon/blob/development/tests/interactive/locale/compare_locales.py
This goes through all the alternative (non-english) locales and prints the ones missing from english.

I don't mind adding your script.  Could you please add a docstring at the top which documents how to use it?

**Comment by bitcraft** [comment]
> I don't mind adding your script. Could you please add a docstring at the top which documents how to use it?

@airon90

**Comment by airon90** [comment]
> some minor issues can be tolerated
Example?

> Have you compared it to our existing tools here? 
OMG no. If it is a duplicate I close the PR :)

>  Could you please add a docstring at the top which documents how to use it?
Ehm, I will find some info about that and then I will do, if my script is not a duplicate of the other scripts ^^'

**Comment by bitcraft** [comment]
> Example?

Nothing specific.  I can be a little picky (and I encourage others to be)  of code that gets commited into Tuxemon.  For scripts, I dont really care if the formatting is wrong, if there are unused variables, missing docstrings, "un pythonic", etc.  If it works and is documented, that is good enough.


> OMG no. If it is a duplicate I close the PR :)

I'm sorry, I just don't have time to check the script.  We have some existing tools to check.  

BTW, there is a major refactoring of all the translation code which is going on now.  It was started after you opened this PR.  I can't say 100% but I think your scripts (if using JSON) will be obsolete after the translation changes are made.  Please checkout https://github.com/Tuxemon/Tuxemon/pull/477 for more information.  Basically, the dev is moving us to industry standard translation tools, based on GNU gettext with PO files.

**Comment by bitcraft** [comment]
@airon90 Thanks for the effort in putting this together and sharing it.  I'm going to close this now because we are really close to merging a big locale update which will make this tool obsolete.  The upside is, we will be using PO files and will have a bunch of different tools we can use.

**Pull request closed without merging**
