### PR TITLE
monsters package +  piscine body shape

### PR DESCRIPTION
**Pull request by JaskRendix**
We are over 270!

@Sanglorian here, opened as draft

247 https://wiki.tuxemon.org/Dankush
248 https://wiki.tuxemon.org/Cherubat
249 https://wiki.tuxemon.org/Ambuwl
250 https://wiki.tuxemon.org/Woodoor
251 https://wiki.tuxemon.org/Blasdoor
252 https://wiki.tuxemon.org/Rhinocarpe (new fishing material)
253 https://wiki.tuxemon.org/Kernel @kerizane 
254 https://wiki.tuxemon.org/Tux (finally!)
255 https://wiki.tuxemon.org/Hotline
256 https://wiki.tuxemon.org/Rinocereed
257 https://wiki.tuxemon.org/Potturmeist
258 https://wiki.tuxemon.org/Potturney
259 https://wiki.tuxemon.org/Imbrickcile
260 https://wiki.tuxemon.org/Bricgard
261 https://wiki.tuxemon.org/Brickhemoth
262 https://wiki.tuxemon.org/Waysprite
263 https://wiki.tuxemon.org/Angesnow
264 https://wiki.tuxemon.org/Demosnow
265 https://wiki.tuxemon.org/Lucifice
266 https://wiki.tuxemon.org/Seraphice
267 https://wiki.tuxemon.org/UF0
268 https://wiki.tuxemon.org/Tadcool
269 https://wiki.tuxemon.org/Fribbit
270 https://wiki.tuxemon.org/Squink
271 https://wiki.tuxemon.org/Hectapod
272 https://wiki.tuxemon.org/Slichen
273 https://wiki.tuxemon.org/Glombroc
274 https://wiki.tuxemon.org/Conglolem

### CODE REVIEW

**Comment by Sanglorian** [comment]
> As you can see we are over 250!
> 
> @Sanglorian here, opened as draft

Thank you! Let's say level 25 for Woodoor to morph into Blasdoor. And thank you for the maturity flag, I think that's a good idea. 

I've tweaked the face sprites and set Potturney to complete; will try to take a look at the others later this week.

**Comment by JaskRendix** [comment]
> I've tweaked the face sprites and set Potturney to complete; will try to take a look at the others later this week.

That's great! Sure, no problem.

**Comment by JaskRendix** [comment]
@Sanglorian ah, you need to complete the evolution details for 
https://wiki.tuxemon.org/Imbrickcile evolutions (as usual, level? technique? item? etc.)
https://wiki.tuxemon.org/Waysprite evolutions (as above, but this one is more interesting)
https://wiki.tuxemon.org/Claymorior

> I've tweaked the face sprites and set Potturney to complete; will try to take a look at the others later this week.

That's great! Sure, no problem.

enlarged https://wiki.tuxemon.org/Seraphice back (right side)
updated menu1 and 2 https://wiki.tuxemon.org/UF0 too (closed the border at the bottom)

**Comment by Sanglorian** [comment]
Ah good reminder! Okay, I added level morph for Imbrickcile, and a day/night morph for Waysprite - is that possible? If not we can come up with something else. Because Claymorior's flavour says only one in 1,000 can morph, I made it so only Claymorior with a particular taste can morph. Not quite 1/1000 odds, but still! 

Seraphice and UF0 look good, thanks!

**Comment by JaskRendix** [comment]
@Sanglorian 

> a day/night morph for Waysprite - is that possible?

Yes, no problem.

https://wiki.tuxemon.org/Seraphice is missing the species! Are you sure that Seraphics is male/female? I'm asking because all the others are neuter. If yes, does it becomes male or female randomly?

https://wiki.tuxemon.org/Shelagu and https://wiki.tuxemon.org/Volconey missing species too

**Comment by Sanglorian** [comment]
> https://wiki.tuxemon.org/Seraphice is missing the species! Are you sure that Seraphics is male/female? I'm asking because all the others are neuter. If yes, does it becomes male or female randomly?
> 
> https://wiki.tuxemon.org/Shelagu and https://wiki.tuxemon.org/Volconey missing species too

Thanks! I've added species for Seraphice and fixed it back to no gender (good catch), and added species for Shelagu and Volconey. 

I've marked Glombroc, Tadcool and Squink as complete after making some minor changes to the sprites - thank you for all your work on them! The others will need a bit more work -- I'll make some notes over on Missing Things at some point.

**Comment by JaskRendix** [comment]
@Sanglorian that's perfect, I'm going to fix and add the ready ones.

> The others will need a bit more work -- I'll make some notes over on Missing Things at some point.

Sure, no problem, we are close to 300 now.

**Comment by JaskRendix** [comment]
ready to go, the last 3 will be included in another package

**Review by kerizane — APPROVED** [review]

**Pull request merged**
