### PR TITLE
Adds dialog_choice and translated_dialog_choice to the event system

### PR DESCRIPTION
**Pull request by dulsi**
Implements issue 197 so that NPCs can ask questions.

### CODE REVIEW

**Comment by ShadowApex** [comment]
Hi dulsi, thanks for the PR! Everything looks good, but I wanted fully test the `dialog_choice` and `translated_dialog_choice` in a map, which has taken me a little bit to get around to. Once I've finished testing I should be able to merge this in.

**Comment by ShadowApex** [comment]
I did some testing and found some issues with the current implementation. Right now I have only tested `dialog_choice` and not `translated_dialog_choice`. I'd like to know if you can also replicate these issues. Here's what I found:

## Events
Here's what I currently have configured in the map. If I didn't create these events properly, let me know:
**Event 1**


**Event 2**


## Bugs
- Right now it appears that I have to trigger the dialog chain twice in order for the choices to appear:


- After picking the appropriate choice, it looks like the dialog choice continues to pop up:


- Not really a bug necessarily, but I think we should also allow `dialog_choice` after normal `dialog` and `translated_dialog` actions, and not just `dialog_chain` actions.

Other than those things, everything else seems to work pretty well!

**Comment by dulsi** [comment]
dialog_chain ${{end}} needs to be after the dialog_choice. See issue #197 for my example. I agree ideally you want to be able to do it after dialog. Frankly I don't like dialog_chain and would prefer to have no need to specify dialog_chain ${{end}} but haven't looked into how.

**Comment by ShadowApex** [comment]
> dialog_chain ${{end}} needs to be after the dialog_choice. See issue #197 for my example.

Thanks for linking to your example. After moving the `dialog_choice` before calling `${{end}}` everything worked perfectly!

I also agree that not needing to specify `${{end}}` would be ideal. The main reason it was originally implemented that way was because each action is inherently not aware of any of the other actions. For example, `act2 dialog_chain My name is Lampy\\, lord of all lamps` doesn't know about or have access to "act1", "act3", "act4", etc., and thus doesn't know if it's the last text in the dialog chain (once the last text in the dialog chain appears, it needs to call [open_dialog](https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/event/actions/core.py#L234)). We might be able to solve this problem and other event problems like it by [passing the full "action_list" to every action that's executed by the Event Engine](https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/event/__init__.py#L169).

**Comment by dulsi** [comment]
I have two thoughts on the problem:

1) When an event is started a "context" object is created. Event system is passed this "context" object. _dialog_chain_queue and _menu are moved to this object. If after the event finishes, it finds a _dialog_chain_queue and/or -menu, it opens the dialog.

2) Dialog is opened immediately but all add future dialog/choice events add to the dialog object. How exactly that is done, I'm not sure. (I suppose you could say this is kinda the same idea. Just that the dialog object becomes the "context" object mentioned above.)

**Comment by bitcraft** [comment]
Currently, the dialog_chain event will queue up any messages that it gets.  What if we dropped the normal dialog action and renamed dialog_chain to dialog?  Then in the event manager, we explicitly check for any messages in the dialog queue and open them at the end of the frame.  We'll shoehorn the dialog choices in the queue as well.

This would also drop the need for {{end}}.

Thoughts?

**Comment by dulsi** [comment]
That is essentially what I'm suggesting with the "context" object. The reason I mentioned it as passing in a new object instead of just checking the _dialog_chain_queue/_menu globals at the end of running an event is that eventually the plan is to support multiplayer. If I have a single _dialog_chain_queue, that won't work.

Right now the event manager doesn't know anything about the event system. Moving the open_dialog there makes it more knowledgeable about the internals. Maybe the context could be a collection of "finish" functions. That way the event manager still doesn't know anything.

**Comment by bitcraft** [comment]
I see what you are saying @dulsi.  Our suggestions will do essentially the same thing, but the implementation differs.  Right now, I don't see any need outside of the dialogs for a "context" system like you are proposing, but I do see the merits.

If you want to pursue this, it would help everyone if you could provide some pseudo code and a general plan of how it works and what the benefits will be.  Opening an issue would be a good start.

**Comment by bitcraft** [comment]
After a bit of thought, it seems to me that we could pass the list of events without much effort, and we can fix a few issues with "one weird trick" (computer programers HATE him).  The context system can be bolted on later, because I don't see them creating any conflicts with each other.

**Comment by ShadowApex** [comment]
@dulsi I'm going to accept this PR, but I created a separate issue for discussion about adding a context system to the event engine. It can be referred to here:  #208

**Pull request merged**
