### PR TITLE
background environment

### PR DESCRIPTION
**Pull request by JaskRendix**
I was testing some things and I realized that I've never seen a single background (battle or random encounters). I checked and I discovered it was broken. Now it's possible to see again the backgrounds during the battles or random_encounters.

Since I was doing the task, I added snow_background and sand_background as requested here #1135 by @ultidonki 

One addition, I noticed that the images were too small (240x112), the problem was the width (240), so I increased it to 280. All the images were edited by resizing canvas. It took me a while, but it was necessary (all the background images are 280 x 112).

### CODE REVIEW

**Review by kerizane — DISMISSED** [review]

**Comment by kerizane** [comment]
@Sanglorian do we have credits for the art?

**Comment by kerizane** [comment]
Why did you need to change the width?

**Comment by JaskRendix** [comment]
> Why did you need to change the width?

Before 240
before
After 280
after

**Comment by JaskRendix** [comment]
From wiki:
https://wiki.tuxemon.org/File:5_(240px).png
https://wiki.tuxemon.org/File:NightBackground_(240px).png
https://wiki.tuxemon.org/File:Ocean_cropped.png
https://wiki.tuxemon.org/File:Region_concept_art.jpeg (bottom right)
https://wiki.tuxemon.org/File:Background_zpstcxpw68m_-_Leo.JPG

**Comment by kerizane** [comment]
I haven't seen that before, what resolution are you playing at? (Check tuxemon.cfg)

**Comment by JaskRendix** [comment]
I never touched these values:
resolution_x = 1280
resolution_y = 720

My display 1920x1080

**Comment by kerizane** [comment]
@JaskRendix Could you add the two new files to CREDITS.md? There is a "Battle Backgrounds" section

**Comment by JaskRendix** [comment]
No problem, done!

**Review by kerizane — APPROVED** [review]

**Pull request merged**
