### PR TITLE
missing events and locations (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR adds missing events and fixes trading (after #1738 )

@Sanglorian 

firefigher as per wiki https://wiki.tuxemon.org/Timber_Town
spyder_timber_house
magician as per wiki https://wiki.tuxemon.org/Timber_Town
spyder_timber_cafe
catgirl (3rd house) https://wiki.tuxemon.org/Candy_Town
spyder_candy_house3
private garden behind the 3rd house (removed some trees, added the back door in the 3rd house) https://wiki.tuxemon.org/Candy_Town
Screenshot from 2023-04-09 20-11-57 
eventually explain what you mean by this:
_Welcome to my market garden. I grow plants. Would you like me to show you how you can grow plants too? (Insert description)_

So in another PR I can eventually insert it.

### CODE REVIEW

**Comment by JaskRendix** [comment]
@sanglorian is it ok or do you want to decide the level of the traded monster (eg grintot lv 25 -> hampotamos lv 10)?
Let me know, so I can fix it.

Moreover I noticed some trading never added, so I created the cafe and house in Timber Town:
firefigher as per wiki
spyder_timber_house
magician as per wiki
spyder_timber_cafe

I like these trading, we could add more, especially in cafes.

I noticed I put catgirl inside the art critic house, I'm going to move in another house later.
```
You know, I'm just fascinated by fossils. You know - Shammer, Rhincus.
```

**Comment by Sanglorian** [comment]
> 
> catgirl (3rd house) https://wiki.tuxemon.org/Candy_Town spyder_candy_house3 private garden behind the 3rd house (removed some trees, added the back door in the 3rd house) https://wiki.tuxemon.org/Candy_Town Screenshot from 2023-04-09 20-11-57 eventually explain what you mean by this: _Welcome to my market garden. I grow plants. Would you like me to show you how you can grow plants too? (Insert description)_
> 
> So in another PR I can eventually insert it.

Ah, at one point people proposed a gardening mini-game. I don't think it's worth adding at this point, so I've written an alternative: [the Florist gives a random item,](https://wiki.tuxemon.org/Candy_Town#Private_Garden) maximum of once per day. The Ancient Egg can only ever be given once. 

Does that work or is it too complicated to program? Otherwise we can find a different solution, like having her just give the Ancient Egg.

**Comment by JaskRendix** [comment]
I need to look into (random item per day), but regarding Ancient Egg, are you sure you want to give it randomly?

**Review by kerizane — APPROVED** [review]

**Comment by Sanglorian** [comment]
> I need to look into (random item per day), but regarding Ancient Egg, are you sure you want to give it randomly?

Thanks for checking, yes I think it's okay -- it's a bonus rather than a key part of the plot.

**Pull request merged**
