### PR TITLE
Porting Tuxemon to Python 3.x

### PR DESCRIPTION
**Pull request by luckymouse0**
Built using Pillow (PIL fork) library, because the PIL library is
outdated since 2009 and there isn't compatible with python 3.x

http://pillow.readthedocs.org/en/3.1.x/about.html

### CODE REVIEW

**Comment by ShadowApex** [comment]
This change causes the python2 version to crash when opening a dialog with text animation:

```python
Traceback (most recent call last):
  File "./tuxemon.py", line 60, in <module>
    main()
  File "/tmp/Tuxemon/tuxemon/core/main.py", line 99, in main
    control.main()
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 512, in main
    self.main_loop()
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 573, in main_loop
    self.update(time_delta)
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 203, in update
    state.update(dt)
  File "/tmp/Tuxemon/tuxemon/core/components/menu/menu.py", line 420, in update
    self.animations.update(time_delta)
  File "/usr/lib/python2.7/dist-packages/pygame/sprite.py", line 399, in update
    for s in self.sprites(): s.update(*args)
  File "/tmp/Tuxemon/tuxemon/core/components/animation.py", line 356, in update
    self.finish()
  File "/tmp/Tuxemon/tuxemon/core/components/animation.py", line 383, in finish
    self.abort()
  File "/tmp/Tuxemon/tuxemon/core/components/animation.py", line 405, in abort
    self.callback()
  File "/tmp/Tuxemon/tuxemon/core/components/menu/menu.py", line 370, in show_items
    self.on_open()
  File "/tmp/Tuxemon/tuxemon/core/states/dialog/__init__.py", line 27, in on_open
    self.next_text()
  File "/tmp/Tuxemon/tuxemon/core/states/dialog/__init__.py", line 40, in next_text
    self.alert(text)
  File "/tmp/Tuxemon/tuxemon/core/components/menu/menu.py", line 139, in alert
    self.animate_text(find_textarea(), message)
  File "/tmp/Tuxemon/tuxemon/core/components/menu/menu.py", line 118, in animate_text
    self.start_text_animation(text_area)
  File "/tmp/Tuxemon/tuxemon/core/components/menu/menu.py", line 106, in start_text_animation
    next_character()
  File "/tmp/Tuxemon/tuxemon/core/components/menu/menu.py", line 98, in next_character
    next(text_area)
TypeError: TextArea object is not an iterator
```

**Comment by luckymouse0** [comment]
Thanks for the feedback!

So both version are mutally exclusive then...

That's bad :(

**Comment by bitcraft** [comment]
Revert the changes to  tuxemon/core/components/ui/text.py and it should be fine.

**Comment by bitcraft** [comment]
Revert the changes to  tuxemon/core/components/ui/text.py to keep py2 working, as it is the primary target.  I wrote the text animation code, and I'll work out a solution for py3 compatibility if you want.

**Comment by luckymouse0** [comment]
Thanks bitcraft, It's your call. 
I will be closing this pull request if it's not useful tho.

**Comment by bitcraft** [comment]
Go ahead and leave it open, its needed.  I'm on a roll tonight with fixes, so I'll take care of the iterator thingy.

**Comment by luckymouse0** [comment]
Thank you very much :)
I will wait for your answer.

**Comment by luckymouse0** [comment]
Now it should work...

**Pull request merged**
