### PR TITLE
simplify maps 3

### PR DESCRIPTION
**Pull request by JaskRendix**
More stuff inside CORE_set, I needed more space so the PNG is slightly bigger. Already fixed the parameters inside the files tmx.

There were some files with still unused tilesets, especially among the inside locations, but way less than before.

Technically we can delete:
- Pacheesi Tiles.png (moved in CORE_floor and replaced)
- Truck-red-all.png (moved in CORE_outdoors and replaced)
- Car,_Black_by_Isaiah658 (moved in CORE_outdoors and replaced)
- city tiles.png (moved in CORE_outdoors and replaced)
- Interiors 2 by Redshrike (moved in CORE_set and replaced)
- couch.png (never used)
- gothicvania.png (never used)
- shade.bmp (never used)
- shade.gif (never used)
- shade.png (never used)
- stairs_down.png (never used)
- Vegetation_and_Outdoor_Fittings_by_George.png (never used)
- Interior_Floors_by_George.png (moved in CORE_floors and replaced)
- Interiors by Redshrike (moved in CORE_ and replaced)
- Tileset.png (moved in CORE_ and replaced)
- Objects_by_ArMM1998 (moved in CORE_ and replaced)
- signs.png (duplicated and used in buddha mountain... still no reply to the dump)
- ladders.png (duplicatd and used in rubberduck_cave)
- Waterfall_by_George (moved in CORE_ and replaced)

Comments:
- **city tiles.png** still used in paper_town XERO (this maps could be deleted, because if Xero will have Paper, it would be better copy and paste and then edit the spyder version than update the current one)
- **Pacheesi Tiles.png** still used in tests
- **Interior_Floors_by_George.png** still used in gaming_hall
- **Outdoor_odds_and_ends_by_Isaiah658** used in paper_town.tmx and rubberduck_city
- **setPieces_glitch** used in 37707 town
- **updated_ground_tiles_by_rubberduck** only used by rubberduck

all the files are still inside the folder

### CODE REVIEW

**Review by kerizane — APPROVED** [review]

**Comment by Sanglorian** [comment]
Thanks, this all sounds like good progress. I did just want to check what the plan is for crediting the creators of different sprites, when they're consolidated? Is there a way to clearly identify which sprites come from where somehow?

**Comment by JaskRendix** [comment]
There's no way to clearly identify which sprites come from where. It's mainly a problem for set pieces, terrains, floors and buildings are ok.

**Comment by kerizane** [comment]
Can't we just list it out in the credits?

Grass tiles from X,
Water tiles from Y...

**Comment by JaskRendix** [comment]
Pointless, it would create another file, confusion for the modders too.
The only way is starting to replacing the sprites and deleting the duplicates.
2 kitchen stove? 3? Let's choose just one, etc.
I opened the PR to revert everything.
Let's hope next time will be ok.

**Pull request merged**
