### PR TITLE
update all monster techniques by ToLower-ing the animation strings

### PR DESCRIPTION
**Pull request by xirsoi**
This was a problem mentioned in #613 . Just used a simple C# program to to lower the animation property.

We'll need to have them be updated in the wiki as well or the problem will just keep coming back.

### CODE REVIEW

**Comment by bitcraft** [comment]
I think that we can fix the wiki import script rather than the wiki itself

**Comment by bitcraft** [comment]
This looks like a good start to fixing this issue.  There are two other issues involved:
* animation names contain a space, and the name is used for the filename, which don't contain spaces
* use of `startswith` in `technique.py` when finding filenames could have ambiguous results
I can merge as is.  let me know if you want to tackle the other problems

**Comment by xirsoi** [comment]
Lets merge this now, i'll tackle the other issues in a second PR.
This change alone fixes over a dozen techniques, which improves the experience quite a bit.

I've also consulted with a friend who is a bit of a shell-script wizard and he helped me put together something to convert all the gifs in the wiki into single frame png's for use by the engine.

I'll include that as a third PR, since it'll be huge. It will also be best to have already figured out the solution to spaces and whatnot *before* i do a bunch of file generation/renaming.

**Comment by bitcraft** [comment]
cool looks good to me, ty.  any code that you want to leave on the repo is fine in the "scripts" folder.  i encourage people to add things there and also won't scrutinize them heavily.  the gif->png stuff might be better in the wiki import script though, using Pillow.

**Pull request merged**
