### PR TITLE
monsters: other 53 missing

### PR DESCRIPTION
**Pull request by JaskRendix**
PR addresses the missing monsters + fix spirit monsters gender (neuter)
After the reply in #1436 I got curious and I discovered there were other monsters ready (graphics already done).

Techniques are missing (same as the other PR)

 [Altie](https://wiki.tuxemon.org/Altie) -  [Apeoro](https://wiki.tuxemon.org/Apeoro) -  [Banling](https://wiki.tuxemon.org/Banling) -  [Baobaraffe](https://wiki.tuxemon.org/Baobaraffe) -  [Baoby](https://wiki.tuxemon.org/Baoby) -  [Beenstalker](https://wiki.tuxemon.org/Beenstalker) -  [Boltnu](https://wiki.tuxemon.org/Boltnu) -  [Boxali](https://wiki.tuxemon.org/Boxali) -  [Brewdin](https://wiki.tuxemon.org/Brewdin) -  [Bumbulus](https://wiki.tuxemon.org/Bumbulus) -  [Chibiro](https://wiki.tuxemon.org/Chibiro) -  [Drashimi](https://wiki.tuxemon.org/Drashimi) -  [Exclawvate](https://wiki.tuxemon.org/Exclawvate) -  [Ferricran](https://wiki.tuxemon.org/Ferricran) -  [Fordin](https://wiki.tuxemon.org/Fordin) -  [Furnursus](https://wiki.tuxemon.org/Furnursus) -  [Graffiki](https://wiki.tuxemon.org/Graffiki) -  [Grumpi](https://wiki.tuxemon.org/Grumpi) -  [Gryfix](https://wiki.tuxemon.org/Gryfix) -  [Jelillow](https://wiki.tuxemon.org/Jelillow) -  [Loliferno](https://wiki.tuxemon.org/Loliferno) -  [Lunight](https://wiki.tuxemon.org/Lunight) -  [Medushock](https://wiki.tuxemon.org/Medushock) -  [Merlicun](https://wiki.tuxemon.org/Merlicun) -  [Metesaur](https://wiki.tuxemon.org/Metesaur) -  [Mystikapi](https://wiki.tuxemon.org/Mystikapi) -  [Nuenflu](https://wiki.tuxemon.org/Nuenflu) -  [Octabode](https://wiki.tuxemon.org/Octabode) -  [Pantherafira](https://wiki.tuxemon.org/Pantherafira) -  [Pythock](https://wiki.tuxemon.org/Pythock) -  [Qetzlrokilus](https://wiki.tuxemon.org/Qetzlrokilus) -  [Rosarin](https://wiki.tuxemon.org/Rosarin) -  [Selket](https://wiki.tuxemon.org/Selket) -  [Selmatek](https://wiki.tuxemon.org/Selmatek) -  [Shelagu](https://wiki.tuxemon.org/Shelagu) -  [Shnark](https://wiki.tuxemon.org/Shnark) -  [Snaki](https://wiki.tuxemon.org/Snaki) -  [Snock](https://wiki.tuxemon.org/Snock) -  [Snokari](https://wiki.tuxemon.org/Snokari) -  [Snowrilla](https://wiki.tuxemon.org/Snowrilla) -  [Solight](https://wiki.tuxemon.org/Solight) -  [Spoilurm](https://wiki.tuxemon.org/Spoilurm) -  [Spycozeus](https://wiki.tuxemon.org/Spycozeus) -  [Statursus](https://wiki.tuxemon.org/Statursus) -  [Tarpeur](https://wiki.tuxemon.org/Tarpeur) -  [Taupypus](https://wiki.tuxemon.org/Taupypus) -  [Tetrchimp](https://wiki.tuxemon.org/Tetrchimp) -  [Tobishimi](https://wiki.tuxemon.org/Tobishimi) -  [Tsushimi](https://wiki.tuxemon.org/Tsushimi) -  [Tumblequill](https://wiki.tuxemon.org/Tumblequill) -  [Turnipper](https://wiki.tuxemon.org/Turnipper) -  [Urcine](https://wiki.tuxemon.org/Urcine) -  [Vigueur](https://wiki.tuxemon.org/Vigueur)

### CODE REVIEW

**Comment by JaskRendix** [comment]
Pointless keep it open, the missing monster will not be added (although majority is ready)

**Comment by Sanglorian** [comment]
Sorry if you were waiting for a reply from me -- I think it'd be great to add these missing monsters. There is/was a script that could do it but I'm not sure of the details.

**Comment by JaskRendix** [comment]
Reopened, let's see if the script will be back. 
If someone has some ideas, then feel free to share, because the script isn't around since 2019.

**Comment by JaskRendix** [comment]
Come up with this method.
Applied to **Altie** and **Apeoro**, both **humanoid** / **metal**.
Let's look into the db and see all the moves of similar monsters (humanoid / metal).
Here we go:
```
        monster_slug = list(db.database["monster"])
        filtered = []
        for mon in monster_slug:
            result = db.lookup(mon, table="monster")
            if result.shape == "humanoid":
                if "metal" in result.types:
                    for i in range(0,3):
                        filtered.append(result.moveset[i].technique)
                        res = [*set(filtered)]
```
if the combination doesn't exist (eg hunter/wood), then:
```
        techs = list(db.database["technique"])
        filters = []
        for mov in techs:
            results = db.lookup(mov, table="technique")
            if "wood" in results.types:
                filters.append(results.slug)
                output = [*set(filters)]
```
All the moves of these monsters (humanoid/metal), duplicates already removed + sorted:
```
['beam', 'bubble_trap', 'electrical_storm', 'perfect_cut', 'shrapnel',
'sleep_bomb', 'strike', 'surge', 'thunderclap', 'wall_of_steel']
```
random sample choice (3 moves), some combinations:
```
['electrical_storm', 'shrapnel', 'sleep_bomb']
['bubble_trap', 'shrapnel', 'sleep_bomb']
['electrical_storm', 'strike', 'wall_of_steel']
['bubble_trap', 'shrapnel', 'sleep_bomb']
[...]
['perfect_cut', 'shrapnel', 'wall_of_steel']
['bubble_trap', 'shrapnel', 'strike']
['sleep_bomb', 'strike', 'surge']
```
Just to be complete, all these are all the techniques with metal in the types:
```
['amnesia', 'battery_discharge', 'beam', 'blade', 'bubble_trap', 'bullet', 'constrict',
'muddle', 'peregrine', 'perfect_cut', 'rust_bomb', 'shrapnel', 'shuriken', 'sleep_bomb',
'strike', 'wall_of_steel', 'whirlwind', 'wing_tip']
```

**Comment by JaskRendix** [comment]
@Sanglorian is it something similar to the old script? Is it enough good for you? Do you want to apply it?


Combination shape/types not present means that it doesn't exist now a monster with that combination (eg. hunter/wood).
In that case I generate the moves based on techniques (eg all the techniques wood).

Example: [example.pdf](https://github.com/Tuxemon/Tuxemon/files/10179043/example.pdf)
Calc file complete: [moves.ods](https://github.com/Tuxemon/Tuxemon/files/10179066/moves.ods)

**Comment by Sanglorian** [comment]
Hi @JaskRendix , this approach is much more sophisticated than the original one, and it looks like a great implementation to me.

**Review by kerizane — APPROVED** [review]

**Review by kerizane — APPROVED** [review]

**Pull request merged**
