### PR TITLE
terrains (combat)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR updates islands (terrain during combat)
- replaces **grass** front and back islands with a single **grass** island;
- replaces **snow** front and back islands with a single **snow** island;
- replaces **sand** front and back islands with a single **sand** island;
- replaces **cave** front and back islands with a single **cave** island;
- removes **ice** front and back islands from **snowplain** (day and night) > replaced by the new **snow**;
- adds **tiled** islands
- adds single **woodland** island (updates islands for **forest** - day and night - background)
- deletes **battle_bg02.png** and **battle_bg02-bg.png** (both unused);

---

By the way, if you want to test it, then you need to change the JSON in the environment folder.

At the moment the majority of the background is set on grass, so grass.json / night_grass.json, because it changes day/night

Here https://wiki.tuxemon.org/Battle_Terrain,  I updated battle terrain page, so you can easily understand the association between background/environment and island/terrain, it'll simplify your update task. There is also a category (https://wiki.tuxemon.org/Battle_Terrain#Unused_Terrain_islands) where there are unused terrains - I had no idea where to put those back in September/October.

If you want to change/add/remove, then let me know. I'll keep an eye on Tuxepedia too.

Moreover, at the moment we got 2 files front/back, but we can do it with only 1, as you did for grass/woodland
(less files around, always better)

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks @JaskRendix , that's very useful. Have updated the cave islands now, and will have a think about how to do the others. 

List for my reference later: 

- [x] Update sand and water islands so front and back match
- [x] Review battle terrains
- [x] Review unused terrain islands

**Comment by JaskRendix** [comment]
@Sanglorian ok, cave island is updated as well as battle terrain (wiki).
You can delete the old back version too (as you did for grass): https://wiki.tuxemon.org/File:Cave_back_island.png

**Comment by Sanglorian** [comment]
> @Sanglorian ok, cave island is updated as well as battle terrain (wiki). You can delete the old back version too (as you did for grass): https://wiki.tuxemon.org/File:Cave_back_island.png

Thanks, done now!

**Comment by JaskRendix** [comment]
@Sanglorian updated everything with your last changes.
Moved both ice islands in [unused](https://wiki.tuxemon.org/Battle_Terrain#Unused_Terrain_islands), so at the end we can consider if delete both or maintain something

**Comment by Sanglorian** [comment]
> @Sanglorian updated everything with your last changes. Moved both ice islands in [unused](https://wiki.tuxemon.org/Battle_Terrain#Unused_Terrain_islands), so at the end we can consider if delete both or maintain something

Thanks, good idea!

**Comment by Sanglorian** [comment]
Okay so I've had a think about battle terrains - my favourites are the Superpowers Assets Pack backgrounds with the new island designs. I've moved to an "Unused Terrain" section the ones that use concept art backgrounds or, in the case of the forest background, original pixel art from Catch Challenger. 

That leaves a large variety of backgrounds, with a mix of islands - but I think they're good to go for now and we can think about harmonising the islands later. I'll keep my eyes out for more tiles on OpenGameArt that can be turned into islands. For my own campaign, I'll stick to the new islands - but I don't want to limit what others do.

**Comment by JaskRendix** [comment]
@Sanglorian it sounds good, at the end we did a nice job

**Review by kerizane — APPROVED** [review]

**Pull request merged**
