### PR TITLE
datacenter quest (post game Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
Wasted some time to expand Spyder campaign.

PR:
- updates side ROUTE E and ROUTE B;
- adds events to Cotton Town + Cotton Town Cathedral (Spyder)
- creates new map spyder_datacenter;
- places the [Gold Pass](https://wiki.tuxemon.org/Gold_Pass) in the datacenter;
- places 8 screens/doors;
- monsters updated;

### CODE REVIEW

**Comment by Sanglorian** [comment]
Great work, looks like a great expansion. Not sure which monsters and levels work at this stage of the game for the NPCs, but I've added some ideas for the dialogue. 

What are your thoughts for the puzzle? Something involving the 12 PCs? A few ideas:

* Some PCs are linked to doors blocking the player's way. Each asks for a password, with a cryptic clue. Other PCs give more details about the cryptic clues, to help with guessing the passwords? 
* Some kind of CAPTCHA style puzzle people could do? Or an in-game version of the mini-game where people identify the tuxemon from its silhouette?
* Each PC opens a gate somewhere and closes a gate somewhere, so players need to figure out the right order to switch them on and off. 

I think this is a great use for Virware and Trojerror.

**Comment by JaskRendix** [comment]
I think one of these two:
- Some PCs are linked to doors blocking the player's way. Each asks for a password, with a cryptic clue. Other PCs give more details about the cryptic clues, to help with guessing the passwords?
- Each PC opens a gate somewhere and closes a gate somewhere, so players need to figure out the right order to switch them on and off.

**Comment by JaskRendix** [comment]
I think one of these two:
- Some PCs are linked to doors blocking the player's way. Each asks for a password, with a cryptic clue. Other PCs give more details about the cryptic clues, to help with guessing the passwords?
- Each PC opens a gate somewhere and closes a gate somewhere, so players need to figure out the right order to switch them on and off.

updated the Tuxepedia page of Datacenter, I put some things, added others.

**Comment by JaskRendix** [comment]
I think one of these two:
- Some PCs are linked to doors blocking the player's way. Each asks for a password, with a cryptic clue. Other PCs give more details about the cryptic clues, to help with guessing the passwords?
- Each PC opens a gate somewhere and closes a gate somewhere, so players need to figure out the right order to switch them on and off.

@Sanglorian updated the Tuxepedia page of Datacenter, I put some things, added others, especially regarding what we can trigger after Datacenter, from what I understood Walled Garden is optional, but at least to give to the player the next destination.

**Comment by JaskRendix** [comment]
@Sanglorian everything has been completed, it remains to know if there is/are a message/messages after winning against Kernel, some sort of code to trigger (?). Let me know.

**Comment by Sanglorian** [comment]
This is looking great, I like your dialogue and the quizzes. Have added suggested dialogue at the end, which links it to the Walled Garden and Route 7. What do you think?

**Comment by JaskRendix** [comment]
I like the idea of seeing Billie again.

**Comment by JaskRendix** [comment]
This is ready to go.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
