### PR TITLE
Adding Tech Shops to Candy and Cotton Scoops

### PR DESCRIPTION
**Pull request by Sanglorian**
I hope I've done this correctly, I'm afraid I can't run Tuxemon on my system at the moment to confirm that it's working. 

If these two work, I'll replicate them for the other towns. 

I wanted to make a place for TMs specifically to be sold, as we've got a lot of techniques that could become TMs and I didn't want them blocking the more basic items in the Scoop stores. 

I also wanted to make the evolution items for the "new" starters available. 

**Yet to do**
I'd also like these shops to sell the "new" starters. Is there a way to add tuxemon for sale in an economy, or does that need to be done through a separate process?

### CODE REVIEW

**Comment by kerizane** [comment]
@JaskRendix could you test this for sanglorian?

**Comment by JaskRendix** [comment]
When you open the Flower City Scoop in Tiled, it may appear without events - this is normal. The events are actually stored in the YAML file. Feel free to add the event to the map in Tiled, and I can help move it to the correct file later.

**Comment by JaskRendix** [comment]
When you open the Flower City Scoop in Tiled, it may appear without events - this is normal. The events are actually stored in the YAML file. Feel free to add the event to the map in Tiled, and I can help move it to the correct file later.

>  Is there a way to add tuxemon for sale in an economy, or does that need to be done through a separate process?

it'll be possible after #2553 

I've anticipated some of the items and translations. If you'd like, I can quickly add the techie character to all the necessary locations. To complete this task, I'll need the following information:
• The specific items and technologies you'd like to include
• The monsters you want to sell, along with their corresponding locations

**Comment by kerizane** [comment]
Closing as covered by https://github.com/Tuxemon/Tuxemon/pull/2557. Thanks both of you!

**Pull request closed without merging**
