### PR TITLE
add moves (monster JSONs)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR reduces the gap between techniques.
before
```
            "level_learned": 2, "technique": "ram"
            "level_learned": 2, "technique": "boulder"
            "level_learned": 12, "technique": "thunderball"
```
after
```
            "level_learned": 2, "technique": "ram"
            "level_learned": 2, "technique": "boulder"
            "level_learned": 6, "technique": "mudslide" --> new technique
            "level_learned": 8, "technique": "assault" --> new technique
            "level_learned": 12, "technique": "thunderball"
```
before the gap was too big (from 2 to 12). Random earth because Rockitten is type earth.

used same script, type earth, moves earth (mixed type, mixed techniques).

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks @JaskRendix , this will help keep things interesting. Eventually I hope monsters will have techniques planned out, except perhaps a few random ones. But for now what you've done looks good.

**Comment by JaskRendix** [comment]
@Sanglorian 
I wonder why you told me to introduce the random field inside moveset if you wanted everything planned out.
I could have trashed the previous PR.

**Comment by Sanglorian** [comment]
> @Sanglorian I wonder why you told me to introduce the random field inside moveset if you wanted everything planned out. I could have trashed the previous PR.
> 
> update: almost removed all the random (still missing fire and wood)

The game is still in development, so there's lots of features that we can use now that we won't need to use so much when/if the game is complete.

Random techniques is very useful at the moment, and there will probably always be some monsters that have random techniques (imagine for example a chaos monster). The ultimate goal is for most techniques to be fixed but that is probably still years away.  The random techniques feature is especially useful now and will still have uses then too

**Comment by JaskRendix** [comment]
> The ultimate goal is for most techniques to be fixed but that is probably still years away. 

Are you serious? It's literally what I'm doing right now by replacing the random with defined techniques.

**Comment by JaskRendix** [comment]
> The ultimate goal is for most techniques to be fixed but that is probably still years away. 

Are you serious? It's literally what I'm doing right now by replacing the random with defined techniques.
I don't know how it sounds for you, but this sentence sounds like a punch in the face (included the generic "features" stuff).

update: I closed the other PR (pointless feature), feel free to check the technique added, I used the script (as it was done before), so it uses only the techniques corresponding the type.

**Comment by JaskRendix** [comment]
> The ultimate goal is for most techniques to be fixed but that is probably still years away. 

Are you serious? It's literally what I'm doing right now by replacing the random with defined techniques.
I don't know how it sounds for you, but this sentence sounds like a punch in the face (included the generic "features" stuff).

@Sanglorian update: I closed the other PR (pointless feature), feel free to check the technique added. Changed title too.
I used the script (as it was done before), so it uses only the techniques corresponding the type.

Look, if this doesn't go in your "techniques to be fixed" direction, then I can trash it.

**Comment by Sanglorian** [comment]
It's certainly not my intention to offend you. You have made many big, important contributions to this project, for which I'm very grateful, and I was trying to explain that random techniques are useful.

For monsters to feel different, they will (eventually) all have their own unique technique progressions (mostly -- there is of course room for random techniques as well). But coming up with additional techniques and assigning them to monsters will be a long-term project involving playtesting, discussions, brainstorming and so on.

If there's anything unclear about this process, please let me know. I don't want you to feel like your work is ever wasted, because it's so valuable to this project.

**Comment by JaskRendix** [comment]
@Sanglorian no problem, my only fear is not being on the same page with you, this is why I tag you all along.

**Review by kerizane — APPROVED** [review]

**Comment by kerizane** [comment]
Just wanted to reiterate what Sanglorian said: you've done SO MUCH! It's appreciated.

**Pull request merged**
