### PR TITLE
replace gender with symbols

### PR DESCRIPTION
**Pull request by JaskRendix**
Following #1363 
(M) -> ♂
(F) -> ♀
(N) ->⚲
~~In the neuter case, users will get the ?, but at the end since it's neuter, it makes sense.
If someone has another symbol (Greek letter, etc), then fell free to suggest.~~
Updated the font with the neuter symbol, similar to the female, but without the cross in lower part. So we can use the three symbols without problems. 

Screenshot from 2022-10-05 19-42-40

### CODE REVIEW

**Comment by kerizane** [comment]
We don't necessarily need a neuter symbols, the Pokémon games just leave it blank in this case.

Could you provide screenshots of all three?

**Comment by JaskRendix** [comment]
Sure, updated first post

**Comment by kerizane** [comment]
The neuter one is quite similar to the female one, and I'm not sure how many people actually know what it means. Leave the glyph in the font pack, but don't use it.

**Comment by kerizane** [comment]
M and f look good, thanks.

**Comment by JaskRendix** [comment]
Done

**Review by kerizane — APPROVED** [review]

**Pull request merged**
