### PR TITLE
Renamed downstairs bedroom

### PR DESCRIPTION
**Pull request by yairm210**
This is also the place for discussion on how renaming maps affects currently saved games
Once we manage to 'successfully' migrate one map, the other renames will probably be en-masse (depends on y'all though)

### CODE REVIEW

**Comment by bitcraft** [comment]
Looks good.  I want to make sure the other map editors do not have unpushed changes before merging this.

**Comment by kerizane** [comment]
Do we want the game to be able to handle these changes? 
Bad user experience if it crashes. Annoying for us to explain to people how to fix.

How about this? 
https://github.com/Tuxemon/Tuxemon/pull/648

If people want to rename a map they need to add it to MAP_RENAMES.

**Comment by yairm210** [comment]
I'm in favor of this!

**Comment by Qiangong2** [comment]
the thing about map1 is that it includes both taba and paper town in one. As well as route 20

**Comment by yairm210** [comment]
Wait, the second town is called paper town?
There's no sign around, and the nurse is called taba town nurse, so... =/

**Comment by Qiangong2** [comment]
Yeah, it's called paper town. It's taken from the wiki

**Comment by bitcraft** [comment]
Are these areas part of a region?  Can we call this "region01.tmx?"

**Comment by Qiangong2** [comment]
> Are these areas part of a region? Can we call this "region01.tmx?"

Well, as with all pokemon-esque games, the entire game is called a "region". The region we are building is called Fondent region.

I guess taba_town.tmx would work fine

**Pull request merged**
