### PR TITLE
revert simplify maps

### PR DESCRIPTION
**Pull request by JaskRendix**
PR reverts everything and it goes back to the original situation. 
I made a mistake in the first version, everything was mixed, now it's way better than before.

Update:
the maps have been purged (all the unused tilesets have been removed);
added some new set of pieces inside the COREs, I used white stripes to divide in various areas, that's better than before because it's not mixed, so we can identify easily the tilesets;

### CODE REVIEW

**Comment by JaskRendix** [comment]
Momentarily draft, I'm going to purge unused tilesets from maps, so the job isn't completely lost.

**Comment by JaskRendix** [comment]
@Sanglorian this needs your approval, I reverted the changes of the previous PRs and I resorted in a more ordinate way the sprites inside the COREs. In this way we can use the white delimitation to write inside the provenience of the source.

If it's ok, tell us. If not, tell us too by requesting the previous situation (so leaving the unused tilesets inside the maps) and leaving everything as it was. In this way we aren't stuck anymore.

**Comment by Sanglorian** [comment]
Sorry for the delay. Thanks for doing this. I think this approach is much better. Sorry you had to do so much work using the original approach.

**Comment by JaskRendix** [comment]
Perfect, now I have ready another PR to continue the replacement, I'll submit as soon as this gets merged.

**Comment by JaskRendix** [comment]
Perfect, now I have ready another PR to continue the replacement, I'll submit as soon as this gets merged.

**Comment by JaskRendix** [comment]
BEFORE -> AFTER
cotton_cathedral1 - cotton_cathedral2
healing_center1 - healing_center2
maple_house1 - maple_house2
player_house_bedroom1 - player_house_bedroom2
player_house_downstairs1 - player_house_downstairs2
spyder_bedroom1 - spyder_bedroom2
spyder_flower_center1 - spyder_flower_center2
spyder_healing_center1 - spyder_healing_center2
spyder_leather_center1 - spyder_leather_center2
spyder_paper_mart1 - spyder_paper_mart2
spyder_timber_center1 - spyder_timber_center2

**Comment by JaskRendix** [comment]
Fix #1483 
game crashes because it's missing the name of the location (properties). It was an addition planned with simplify maps4, which got disbanded after a reply to simplify maps 3.

I would like to know the reason why the PR isn't merged. Do you want to resume simplify maps4?

@sanglorian is ok, he replied above.

Deleted all the last changes to the centers, downstairs and bedroom. So it's not necessary to check again.

**Review by kerizane — APPROVED** [review]

**Comment by kerizane** [comment]
@JaskRendix please @ me if there is an urgent PR (something that breaks the game).

**Pull request merged**
