### PR TITLE
Add different icon for slots with tuxemon in them.

### PR DESCRIPTION
**Pull request by dulsi**
This implements issue #241. Right now there is only one icon for slots with tuxemons. The image is just a yellow filled circle as a prototype. I wanted to put in different colors for active tuxemon and fainted tuxemon but it isn't updating so that can be an enhancement later.

### CODE REVIEW

**Comment by MirceaKitsune** [comment]
Can we see a screenshot please, just out of curiosity? In any case, 👍 to this!

**Comment by ShadowApex** [comment]
Hey dulsi, thanks for this PR!

There's actually these icons to be used as slot icons for different statuses:
https://github.com/Tuxemon/Tuxemon/tree/master/tuxemon/resources/gfx/ui/icons/party

`party_icon01.png` is for a normal monster slot.    
`party_icon02.png` is for a monster with a status effect.    
`party_icon03.png` is for a monster who has fainted.    

If you update your PR to use `party_icon01.png`, then we should be able to merge this in.

Thanks!

**Comment by MirceaKitsune** [comment]
I like the icons @ShadowApex posted. I believe the code should use those personally.

**Comment by dulsi** [comment]
Icon @ShadowApex asked for is now used. I'll to upload an image when I get a chance.

**Comment by ShadowApex** [comment]
Looks great dulsi! Thanks for the change!

**Pull request merged**
