### PR TITLE
Add more animations

### PR DESCRIPTION
**Pull request by kerizane**
Just ran the script to get animations from the wiki.

Credits were painful... Sanglorian has offered to help me finish them off. @Sanglorian if there are any repeated changes you need made to the entries let me know; I might be able to script it a bit. E.g. I made the credits by writing the entries like this:

`X Attack | https://wiki.tuxemon.org/File:X_attack.gif | Unknown`

And then used a vim macro to convert it to 

`* ["X Attack"](https://wiki.tuxemon.org/File:X_attack.gif) Unknown`

Which made things _slightly_ faster.

I was unable to modify the animation download script as the html did not contain all the information that was required, it seems that the credit text is added by javescript. If we want to support scripting this, it would need to be done with something like selenium.

### CODE REVIEW

**Comment by kerizane** [comment]
I haven't actually tested the animations in battle. 

@JaskRendix do you fancy testing these? I'm asking because in the past you have raised PRs that have done a good job analysing the existing assets and making slightly tedious changes. Feel free to refuse.

**Comment by kerizane** [comment]
Tbh, I think the credits are good enough for now, although there are some where the source is unknown. Maybe we should remove those ones?

**Comment by JaskRendix** [comment]
I notice this only now. I'll run some tests. Remove those unknown? It makes sense.

**Comment by JaskRendix** [comment]
I realized that I've never seen an animation. It doesn't do anything, I don't see an animation, only mine and the adversary monster blinking after receiving the strike. **The only one is capture.**

Now, let's see some data. I've extrapolated all the animations="" from the technique .json. I got the list and I made a diff with the animations inside the technique/animations/ folder. This is the result:

These are the animations in the JSON files, but without the actual animation00.png (eg disintegrate -> no files png)
```
bolt -> maybe it's bolt_back?
darkfire -> no files
disintegrate -> no files
dusty explosion -> no files
fire enemy death -> no files
fire lion right -> you renamed firelion_right, but you missed breathe_fire.json and flamethrower.json
heal (no cross) -> no files
ice blast -> no files
puff -> no files
thud -> no files
triforce -> no files
triple whammy -> no files
``` 
These are the animations in the JSON files with the animation00.png, it matches (eg bite -> bite00.png, etc)
```
bite, bomb_bright, buff_rage, claw_blue, constantburn, crushingball, crystal, drip_green, explosion_small, 
firelion_front, gloop_orange, icetacle, lance_ice, lightning_claw, pound, screen, shield_rock, slash_power, 
smash, smokebomb, snake_right, sparks_gold_alt, sparks_red, sparks_white, spikes_rock, tentacle_metal, 
thunderstrike, torrentacle, water_shot, water_spurt, watershot, whirlwind
```
These are in the technique/animations/ folder, but unused:
```
appearance, beartrap, bite_zombie, bomb, buff_armour, buff_fast, buff_ranged, capture, debuff_melee, 
drip, drip_blue, drip_blue_alt, explosion_burst, fire, fire_fade, firelion_back, firetwirl, fireworks, gloop_blue, 
greendrip, heal_swarm, hit_preview, hits_for_separation, metal_delete, misc_hit_preview, pound_bright, 
powerslash, push_trap_front, push_trap_right, pushtrap_front, pushtrap_right, shield_ice, shield_turtle, 
shield_turtle_left, shield_turtle_right, slash_fire, smokebomb_plume, sparks_gold, sparks_red_alt, 
sparks_white_alt, spike_ice, spike_rock, spikes, spikes_fire, spikes_ice, spikes_metal, teeth, 
tentacles_water, tornado_basic, tornado_bulk, tornado_volume, waterfall, whisp_fire, x_attack
```
Through this test I've found the following bugs. I referenced these.

**Comment by kerizane** [comment]
Do any animations work? e.g. bite, water_shot

**Comment by JaskRendix** [comment]
Nothing, I tried with sparks_red and others.

Capture works because there is the code in combat/combat_animations.py
```
        # capdev opening animation
        images = list()
        for fn in ["capture%02d.png" % i for i in range(1, 10)]:
            fn = "animations/technique/" + fn
            image = graphics.load_and_scale(fn)
            images.append((image, 0.07))
```
If I look for animations/technique/, I don't find anything else.

I noticed that a series of techniques don't have the **animation** field, it's missing.

**Comment by kerizane** [comment]
Well that's not good. I am pretty sure they used to work... @AndyMender is working on a similar issue so it might make sense for him to look at this.

Thanks for the analysis.

**Comment by JaskRendix** [comment]
No problem, remember about:
```
bolt -> maybe it's bolt_back?
darkfire -> no files
disintegrate -> no files
dusty explosion -> no files
fire enemy death -> no files
fire lion right -> you renamed firelion_right, but you missed breathe_fire.json and flamethrower.json
heal (no cross) -> no files
ice blast -> no files
puff -> no files
thud -> no files
triforce -> no files
triple whammy -> no files
```

**Comment by kerizane** [comment]
I'm aware of some of those, will have a look later, thanks.

https://github.com/Tuxemon/Tuxemon/issues/1185#issuecomment-1214331839

**Comment by kerizane** [comment]
I've raised which fixes the existing animations https://github.com/Tuxemon/Tuxemon/pull/1288 @AndyMender FYI.

**Comment by JaskRendix** [comment]
I've seen, well done!

**Comment by JaskRendix** [comment]
After integrating the regex fix into my branch, yesterday I checked the following animations and everything went smoothly: tentacle_metal, firelion_front, lance_ice and snake_right.

UPDATE: now the logs shows only the missing techniques (the ones without files.png - eg . disintegrate, etc)
```
2022-09-03 22:42:22,685 - tuxemon.technique - ERROR - Cannot find animation frames for: disintegrate
2022-09-03 22:42:22,689 - tuxemon.technique - ERROR - Cannot find animation frames for: fire lion right
2022-09-03 22:42:22,696 - tuxemon.technique - ERROR - Cannot find animation frames for: ice blast
2022-09-03 22:42:22,703 - tuxemon.technique - ERROR - Cannot find animation frames for: fire lion right
```
Why only these? Because I added these monsters: k9, cardiling, chillimp, dracune and abesnaki to check animations.

**Comment by kerizane** [comment]
Great, thanks for checking.

**Comment by AndyMender** [comment]
> Well that's not good. I am pretty sure they used to work... @AndyMender is working on a similar issue so it might make sense for him to look at this.
> 
> Thanks for the analysis.

I can take a look at it afterwards. Right now I'm hauling over the animation download script to generate also credit records: https://github.com/Tuxemon/Tuxemon/pull/1290

One of the things I also changed is putting the downloaded anim frames directly into the correct game path so they don't linger in the root of the game directory and the downloaded anim gif is put into a temp dir.

**Comment by kerizane** [comment]
Not required any more, as I got AndyMender to recreate in his pr.

**Pull request closed without merging**
