### PR TITLE
Fix route1 random enounters, and don't crash on KeyError

### PR DESCRIPTION
**Pull request by kerizane**

### CODE REVIEW

**Comment by kerizane** [comment]
#523

**Comment by bitcraft** [comment]
Thanks for looking into this.  In the past I believe there were more exception handlers like you PR has.  I have removed many like this.  I prefer to allow the game to crash in cases where the maps or config is broken, because it tells you right away that there is an issue.  Most players will never see the log output, so it could be frustrating to spend time debugging issues if the errors are being silently ignored.

One of my general goals is to have less code that needs to be maintained, and less tolerance for bad config.  For me, the game shouldn't handle a bad config....that should be fixed by the map creators.  If we keep adding workarounds for bad config, the game will quickly have lots of exception handling code, and could create more bugs around broken config.

There are some exceptions, and I am open for allowing this, but in general, I would prefer to see the game config fixed, and avoid adding new code.

Alternatives to ignoring errors like this would be better log output or maybe even a high-level exception handler in the game, which will open a dialog with the error.

Let me know if you want to merge it.  I'm ok with it for now.

**Comment by kerizane** [comment]
That's fine, I removed the error handling.

**Comment by bitcraft** [comment]
Looks good, thanks!

**Pull request merged**
