### PR TITLE
Campaign Maps and New NPC maps

### PR DESCRIPTION
**Pull request by josepharaoh99**

### CODE REVIEW

**Comment by josepharaoh99** [comment]
This pull request adds some of the first campaign maps to Tuxemon-a general start to the adventure. It also adds the npcs from this discussion: https://forum.tuxemon.org/viewtopic.php?id=75. There is a problem with the commits, though. I used to have another repository which I accidentally mixed with this one. None of its files exist anymore, but it left a zillion commits. I tried resetting the repository, but that didn't work. If you know how to delete individual commits, be sure to tell me! 
   I plan to add more to these maps soon. These are very rough maps. One thing that needs to be gotten is a remove_npc function. (Currently in Maple's bedroom, Maple will walk to her steps to go downstairs and block off the way of the player). 
   Also, the events in the junkyard don't go right. The battle is skipped for some reason. But, as far as I can tell, the game will not crash at any point. Thanks!

**Comment by bitcraft** [comment]
Yikes, thats a lot of commits.  There are many opinions of git workflow, but I'll just tell you mine personally.  I tend to make a new branch for a feature or goal and work on the branch.  When finished, I like to squash the commits from the feature branch and merge into a development or master branch.  It keeps the commit history clean, but some people don't like it because it can potentially lead to misleading statistics on who wrote what code.  If you rebase following the link below, you can clean this up and pick the commits you want in the history:

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes

One advanced technique that I employ from time to time [sarcasm] is to copy paste my changes to a new folder, revert (sometimes by just nuking the whole thing and cloning again) the git folder, copy paste the changes back it, then commit.

Once you make the changes to your repo, github will eventually realize that it has changed and will update this page for you.

**Comment by josepharaoh99** [comment]
Thanks bitbucket! What I did is use "git reset --soft HEAD~", but that didn't remove all the unneeded commits. I also used "git rebase", but that hasn't worked, either - yet. I'm not sure what I'm doing wrong. Any more pointers? (sorry, I'm a new Github user) :)

**Comment by bitcraft** [comment]
When you rebase, you need to specify the number of commits that you want to
go backwards.  Make sure to follow all the steps.  Here's another useful
description of the process:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

If you don't like the command line tools, pycharm is a great GUI editor
that has lots of useful GUI tools for git, including merging and
interactive rebasing.

Finally, if you want to discuss this more in realtime, you can contact me
on freenode IRC ("bitcraft", or #tuxemon), or skype, leif.theden@hotmail.com
.

**Comment by josepharaoh99** [comment]
Okay, so I would do git rebase -i HEAD~171 (since I have 171 commits)?

**Comment by bitcraft** [comment]
Yes.  Since you've pushed these changes, you will also need to force push
it, since the git server is going to reject it, since you've rewritten
history.

**Comment by josepharaoh99** [comment]
hmm. It didn't work. I used "git rebase -i HEAD~", then git add --all, then git commit, then pull, then push, and these commits are still here. Did I do something wrong or does it take a long time to work?

**Comment by bitcraft** [comment]
Please contact me on IRC if you wish to get more advice.

**Comment by ShadowApex** [comment]
> One advanced technique that I employ from time to time [sarcasm] is to copy paste my changes to a new folder, revert (sometimes by just nuking the whole thing and cloning again) the git folder, copy paste the changes back it, then commit.

I think this is your best bet to resolve this problem. One of the other problems with this pull request is that it's currently open to the `master` branch. All new pull requests should be opened to the `development` branch.

Try these steps:
* Copy *only* the files you've changed to another folder.
* Delete your https://github.com/josepharaoh99/Tuxemon fork.
* Fork the https://github.com/Tuxemon/Tuxemon project again.
* Clone your fork to your local computer.
* Change to the `development` branch to get the latest version of Tuxemon.
* Copy your changes you made back into the new project.
* Commit and push your changes to your repository.
* Open a new pull request from your project to the Tuxemon project (make sure you select the development branches!)

Another thing to note, try and make sure you commit *only* the files you've changed. Make sure not to commit things like "Thumbs.db" or other files that Windows or other programs create.

Thanks!

**Comment by josepharaoh99** [comment]
Okay, I'm still having trouble. I've re-forked the project, but all the former commits remain. Also, I cloned the project, but that did not add the files to my PC Github folder. Is there any way to totally remove all of your progress and go to the same level as the repository origin (i.e., Tuxemon/Tuxemon)?

**Comment by bitcraft** [comment]
I'd like to help you with this issue.  Please contact me on IRC or skype (leif.theden) if you'd like some assistance.

**Comment by josepharaoh99** [comment]
could you email me at josepharaoh99@gmail.com

**Pull request closed without merging**
