### PR TITLE
flashback Billie (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
split out from #2482 

The trigger for the flashback is an opened package on the downstairs floor of the Rival's house: @Sanglorian is there something that needs tweaking?

Trigger: https://github.com/user-attachments/assets/b134e858-a524-4100-bf12-71c2b337dd51
Unchanged: https://github.com/user-attachments/assets/878f76cf-ba9f-45a1-a475-b6ff6363cf91

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks, looks good. I think you can cut the location, "days ago" and title from the start, and the descriptions of what the characters are doing. 

But overall a nice way to flesh out some details for the characters.

**Comment by JaskRendix** [comment]
I've already removed the location, 'days ago', and title from the start, as well as the descriptions of what the characters are doing. I kept the same format to avoid recording it entirely.

**Comment by Sanglorian** [comment]
Thank you! I think this is a nice touch and a good way to humanize Billie, but I think it can be edited back a bit - I thought Granny's reflections about Bernard might be more affecting if they were shorter - leaving more to the player's imagination.

**Comment by JaskRendix** [comment]
msgid "spyder_billie_flashback13"
msgstr "Oh dear, how much I would like you to be close to me, Bernard... I remember when you were first diagnosed, and you said, 'We'll face this together, as a team.' Sometimes it feels like it was just yesterday that you were here with me. I see so much of you in Billie... it's like you're still with me, guiding me through her."

@Sanglorian I've shortened Granny's reflections in a single dialogue to make them more concise and leave more to the player's imagination. What do you think?

**Comment by Sanglorian** [comment]
> msgid "spyder_billie_flashback13" msgstr "Oh dear, how much I would like you to be close to me, Bernard... I remember when you were first diagnosed, and you said, 'We'll face this together, as a team.' Sometimes it feels like it was just yesterday that you were here with me. I see so much of you in Billie... it's like you're still with me, guiding me through her."
> 
> @Sanglorian I've shortened Granny's reflections in a single dialogue to make them more concise and leave more to the player's imagination. What do you think?

I love it, thank you!

**Review by kerizane — APPROVED** [review]

**Pull request merged**
