### PR TITLE
Add a placeholder for missing sprites

### PR DESCRIPTION
**Pull request by treetrnk**
This commit adds missing.png and tells the game to use it if a sprite cannot be found instead of throwing an error and crashing the game. In case you want to test, both merlicun and firomenis have missing back sprites. Without this PR, the game crashes when you have caught one of them and try to open the tuxemon menu or when you use either of them in battle.

At some point, I vote we replace it with our own missingo, but this will work for now. 

Missingo

I also added in a couple of minor fixes like correctly making the merlicun family fire type, changing the levels of the rare_txmn encounter and removing a white line from the left side of velocitile's back sprite.

### CODE REVIEW

**Comment by bitcraft** [comment]
Do you think it would be more appropriate to move the missing file handling to the monster class?   I like the idea of a universal "missing image" for loading, but I don't think the question mark sprite is appropriate.  A solid color that shows the dimensions of the sprite would be better for the general case, I think.  (I like the question mark is for monsters).

move this:
https://github.com/Tuxemon/Tuxemon/pull/357/files#diff-997a72d7854e725c6c93f5cecb1022e3R145

to here, maybe?
https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/monster.py#L405

**Comment by treetrnk** [comment]
Yeah, I can do that. That's actually where I had it originally (before commits) because I figured it made more sense to do it once instead of three times. That makes sense though, since it's not just monster sprites using that function. 

I should be able to move it over tonight.

**Comment by treetrnk** [comment]
This has been moved. I created a new method just so I didn't have to put the same if statement in there three times and in case we wanted to use it for anything else in the future. If you'd rather it be in three seperate if statements though, let me know and I'll move it all into the load_sprites method.

**Comment by treetrnk** [comment]
In testing this more this morning, I found out that the new placement of this doesn't actually handle front sprites when they are pulled up for a battle. I went into a random encounter against Chillimp, but his front sprite name had a typo in it, so the game crashed. Based on the traceback, it looks like `core.states.combat.combat_animations` calls `core.components.tools.load_sprite` directly, and bypasses where this checks in monster.py. 

Any ideas of a universal way to implement this for battle sprites?

**Comment by bitcraft** [comment]
> If you'd rather it be in three seperate if statements though, let me know and I'll move it all into the load_sprites method.

I'd prefer a generic function, like you implemented it.  Thats fine.

> Any ideas of a universal way to implement this for battle sprites?

In general, when I come across object loading data for pygame use (like the monster class loading pygame surfaces), I've been trying to rewrite the game state to load the graphics.  The idea being that only the game state (WorldState, CombatState, etc) should load and use images.  Otherwise, the images will remain loaded in memory for the duration of the game.  Also, moving the surface loading out of the class enables them to be using in a headless environment for automated testing or as a true headless server.

So, what I am saying is, I would make a similar function in the combat state that checks for a battle sprite and loads a default one on failure.  If you are feeling adventurous, while you are at it, maybe even play around with #347 and find the correct filename without touching the JSON.

**Comment by ShadowApex** [comment]
Thanks for this PR @treetrnk ! I'm going to merge this in :)

**Comment by treetrnk** [comment]
Cool. I still plan on implementing something for all battle sprites like what @bitcraft suggested above, if that sounds good to you. Hoping to get to it this week at some point.

**Pull request merged**
