### PR TITLE
Walled Garden (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
As anticipated in #1782 

Updated wiki: https://wiki.tuxemon.org/Walled_Garden

- couples of NPCs in Timber Town (if the player has/hasn't the gold pass + if the player won against the "boss");
- new locations (walled garden 1 and walled garden 2, 2 rooms of the same building);
- 2 new sprites for rogue (green hat and blue hat, there were a bunch of rogues, at least now there is more variety);

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks @JaskRendix ! I imagined the Walled Garden as being full of rich people rather than monks, but honestly I don't have any plans for it so I think you should do what you like with it!

**Comment by JaskRendix** [comment]
@Sanglorian I used monks because I used the Dojo scheme, but if you have some specific sprite / trainer class, let me know.

**Comment by JaskRendix** [comment]
@Sanglorian eventually we can use these sprites:
https://wiki.tuxemon.org/File:Cultist_green.gif
https://wiki.tuxemon.org/File:Cultist_yellow.gif
https://wiki.tuxemon.org/File:Cultist_red.gif

it could be an interesting sprite for the template Cultist or it's just the correct sprite for the disciple, eventually we can add those to the disciple.

**Comment by JaskRendix** [comment]
since this is mandatory and it's the only way to unlock new content for Spyder (new quests), it needs to be done.

@Sanglorian now everyone inside is CEO, I'm going to change names too.

**Comment by JaskRendix** [comment]
@Sanglorian feel free to check the Tuxepedia and change dialogues or adding monsters, because I have changed the NPCs

**Comment by Sanglorian** [comment]
> @Sanglorian feel free to check the Tuxepedia and change dialogues or adding monsters, because I have changed the NPCs

Looks really good, thank you! I just added a final boss, and mixed up the trainer classes a bit.

**Comment by JaskRendix** [comment]
@Sanglorian I'm going to sync, then we need only the monsters.

I have added the gold pass too (item), but I don't know where the player is supposed to get.

If it's the Cathedral Center who gives the Gold Pass, then it wouldn't be the perfect prize for getting rid of Kernel in the datacenter, since Kernel "messed up" the IT system of the Cathedral.

**Comment by Sanglorian** [comment]
Thanks @JaskRendix! I think the Gold Pass can be handed over when the player beats the Omnichannel CEO - then they could go to the Walled Garden or do the Kernel quest. But could another option be that the Gold Pass is found in the data center, even if Kernel messed up the IT system? Perhaps it was dropped by someone escaping?

Also I just wanted to say, I'll have some suggestions for monsters soon. I'm going through all the monsters identifying where they show up in the Spyder campaign so far. I think that'll make it easier for us to figure out which monsters are good picks for trainers at different stages of the campaign.

**Comment by JaskRendix** [comment]
> But could another option be that the Gold Pass is found in the data center, even if Kernel messed up the IT system? Perhaps it was dropped by someone escaping?

I like this idea. So.. As soon as monsters are done, I'm going to place the usual dude blocking the path or something similar. Gold pass will be found in the Datacenter.

> Also I just wanted to say, I'll have some suggestions for monsters soon. I'm going through all the monsters identifying where they show up in the Spyder campaign so far. I think that'll make it easier for us to figure out which monsters are good picks for trainers at different stages of the campaign.

I noticed, well done!

**Comment by JaskRendix** [comment]
@Sanglorian added Billie dialogues, only missing the monsters and we are ready to go, I don't know if you planned some sort of events for the mountains

**Comment by Sanglorian** [comment]
Thanks @JaskRendix , have added in monsters for the first floor.

**Comment by JaskRendix** [comment]
@Sanglorian 1st room done

**Comment by Sanglorian** [comment]
Thanks heaps! I've added a greeter to the Timber Town wiki: https://wiki.tuxemon.org/Timber_Town#Walled_Garden_2

I've also added monsters for the second room. 

Because the second batch of starter monsters are meant to be exclusives available for purchase, I thought it'd be a nice touch if there were a set of trainers who each had the final morphs of the five monsters from the second starter batch. 

What do you think?

**Comment by JaskRendix** [comment]
> What do you think?

I agree with you, it makes sense and it helps players to increase the stats in Tuxepedia (viewed monsters).

Ready to go, everything is done.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
