### PR TITLE
Fix minor spelling issue

### PR DESCRIPTION
**Pull request by MasterOChaos**
Fixes the spelling issue in en_US pertaining to revive_description

### CODE REVIEW

**Review by Qiangong2 — CHANGES_REQUESTED** [review]
Shouldn't it be "Revives a knocked out Tuxemon and restores 20 HP" ? The way you wrote it doesn't make sense

**Comment by MasterOChaos** [comment]
Whoops
You are right

**Review by MasterOChaos — COMMENTED** [review]
Fixed my bad English

**Comment by Qiangong2** [comment]
Thanks. I'm mainly concerned that it's such a small edit that a full pr may not be required at all. Maybe @bitcraft can weigh in. Should this PR be accepted, or is it too small to just have only this?

**Pull request closed without merging**
