### PR TITLE
Flatpak support

### LINKED ISSUE #804: Flatpak builds
Track flatpak build progress here.  There are some preliminary/WIP scripts and yaml in the repo under the `buildconfig` folder.  Our CI/CD provider, Travis should be able to build and deploy these.

### PR DESCRIPTION
**Pull request by Murmele**
This pullrequest in comparsion with https://github.com/flathub/flathub/pull/3135 will add flatpak support for Tuxemon. The flatpak manifest will be maintained directly on flathub. This pullrequest does only a few cleanups

Fixes  #804

### CODE REVIEW

**Comment by bitcraft** [comment]
i think im ok with being on flathub, but i want the exceptions to be correct.  tuxemon is a very early alpha with a lot of bugs and is under slow/moderate development.  if flathub is supposed to support software that people can just use, then im not sure if tuxemon is a good fit.

**Comment by Murmele** [comment]
Hmm I don't think it is a problem, but I think you get more feedback and maybe other developers find the project.

By the way, why is the Tuxemon.org webpage down?

**Comment by bitcraft** [comment]
we have enough feedback... need developers :)
the website and wiki are hosted on a basic cloud instance that cannot handle much traffic.  ill ask the right person about the status of it.

**Comment by bitcraft** [comment]
@Murmele btw, please join our discord or matrix.  if you are going to maintain the flathub stuff, it would maybe be helpful to you as most of our discussions happen there.

**Comment by Murmele** [comment]
@bitcraft I joined the Matrix channel. I wrote in the Tuxemon: Discord (#programming) space

I would add some screenshots to the appdata file so they appear on the flathub webpage as preview for the application. Can we add some screenshots to this repository so they are reliable available for fetching?

**Comment by Murmele** [comment]
@bitcraft This is now also ready

**Review by bitcraft — APPROVED** [review]

**Pull request merged**
