### PR TITLE
Add init and interact objects to the maps.

### PR DESCRIPTION
**Pull request by dulsi**
This implements issue #251 

The init object type is run when the map is loaded. This allows us to avoid constantly checking events that only run once.

The interact object runs when the player is facing the tile and pressing return. This makes adding interactive squares easier for map designers. It also decreases the number of events we need to check if return is not being pressed.

Right now the code cheats a little for the interact check. I created an EventObject (I'm open to better name for the object). It has x and y coordinates. That is passed into the check_condition function since we don't have a Condition object. Ideally I'd like to see check_condition take the EventObject and Condition object. That way x and y information is only stored once and is removed from the Condition object. Same could be done with width and height but that is not in the patch at the moment.

When should the wiki be updated? Should I add information about the init and interact objects now? Wait until it is committed to the Tuxemon/Tuxemon repository? Wait until it is merged into master?

### CODE REVIEW

**Comment by ShadowApex** [comment]
Thanks for this PR! I'll try and finish reviewing these changes this weekend so we can merge this. Once these changes have been accepted into the development branch, we can update the wiki for both interacting with objects and map init.

**Comment by ShadowApex** [comment]
I noticed that the "init" events are normal Tiled objects with custom properties, similar to normal "event" objects. I know that Tiled also supports [custom properties](http://doc.mapeditor.org/reference/tmx-map-format/#properties) within the map itself (in Tiled you can go to Map-> Map Properties). I was originally thinking that "init" events could be put there, but thinking about it now, it might be harder to put init events that require other conditions. Do you think future "init" events might require conditions other than just to start on map load?

Since we are also defining more than one custom object for events now, we might be able to create predefined properties using the [Object Types Editor](http://doc.mapeditor.org/manual/custom-properties/) to make it easier to show map creators what kind of events are available directly from within Tiled. The editor looks like this:
Object Types Editor Screenshot

With predefined objects, we could have one for `event`, `interact`, etc. with default properties.

**Comment by dulsi** [comment]
I think you may want conditions other than just first load. It could still be done like it was before in those cases but wouldn't be as elegant. I've only learned the features of Tiled through the Tuxemon map editing information so init and interact were added with my limited knowledge of what could be done. I'll take a look at the Object Types Editor when I have a chance. (It's National Novel Writing Month so don't expect much until December.)

**Comment by ShadowApex** [comment]
I agree, I think it's probably better the way you implemented it. It also follows the way we currently implement normal events and interactions.

I went over this and everything looks good. I'll open another issue to address the Object Types Editor, which can be looked at separately.

Thanks again for the PR!

**Pull request merged**
