### PR TITLE
update translated name - description monsters (base.po) - advanced

### PR DESCRIPTION
**Pull request by JaskRendix**
As requested in https://github.com/Tuxemon/Tuxemon/issues/1120

I wasn't able to update api.py and extractor.py, but using another tool I extracted the information and updated the already existing (but missing) translations.

This is the advanced update. Logically it needs #1260 

I think it will be closed (probably), I guess it's too soon, but I wanted to show the updated base.po list in alphabetical order.

The source: https://wiki.tuxemon.org/Completed_Tuxemon

### CODE REVIEW

**Comment by kerizane** [comment]
LGTM, what's the issue?

**Comment by JaskRendix** [comment]
No issue. I was just wondering if we want to insert everything at once.

**Review by kerizane — DISMISSED** [review]

**Comment by kerizane** [comment]
Fix conflict please

**Comment by kerizane** [comment]
This is our fault for not having proper guidelines, but please start doing the following before raising a PR:

Squash all your commits into one (unless multiple commits are actually useful).

Make sure the commit has a useful summary of the changes (don't have to justify the code to the extent you do in PRs, but provide a quick description of what the change is).

**Comment by JaskRendix** [comment]
Fixed. I'll squash as much as possible.

**Review by kerizane — APPROVED** [review]

**Comment by kerizane** [comment]
Merged anyway. Thanks for the work.

**Pull request merged**
