### PR TITLE
fix 2489 + tuxeball (items) + shops

### LINKED ISSUE #2489: I cannot catch Drokoro or Volcori
I beat the game, but I wasn't able to catch 2 bonus monsters, Drokoro and Volcoli.

My team was amazing but the best monsters were two level 48 tuxemon, Drokoro was level 50.
After getting Drokoro's HP down to this much, I spent 12 minutes (I counted!) throwing tuxeballs at Drokoro, but couldn't catch it. Sometimes it came close, with 3 or 4 wiggles before it was caught, but I never actually managed to catch it.

drokoro_cannot_catch

Is that right or wrong? I don't know what the catch rate is supposed to be, or how to make it more likely to be caught, but that seems a bit harsh.

It happened again with the level 50 Volcoli - I had a level 60 tuxemon this time, spent 5 minutes throwing tuxeballs at it after reducing its health, and gave up.

### PR DESCRIPTION
**Pull request by JaskRendix**
This PR builds on PR #2494 and addresses the related fixes #2489. There was some feedback about trying to catch rare monsters with just a basic Tuxeball, so I took the initiative to enhance the variety of Tuxeballs available.

In this PR, I’ve separated the Tuxeball issue from #2494 to give it the attention it deserves. I’ve added several new Tuxeball variations, each tailored to specific monster shapes. For instance, Drokoro and Volcoli will now have their own unique Tuxeballs! The images are currently similar to the standard design, but I’d love to see any creative artwork contributions from the community.

info about other [tuxeball](https://wiki.tuxemon.org/Category:Item#Capture_Items) types

Additionally, I’ve introduced Tuxeballs for daytime versus nighttime, adding even more strategy to capturing monsters. 

On the coding side, I’ve made some adjustments to the `capture.py` file to reduce hardcoded values related to Tuxeballs. The original Tuxeball logic remains intact for now, but I’m also working on separating out the Tuxeball park (capture_park) since it functions differently from the traditional ones.

The Tuxeballs follow a standard bonus and malus system based on the monster's shape and element.

I also introduced the Gambler Tuxeball, which randomly generates a modifier between 0.0 and 2.0, adding an element of chance to the mix.

For the daytime variations, they follow a similar variable logic, allowing for the creation of Tuxeballs tied to specific variables. If the variable exists and matches, the modifier is 1.5; otherwise, it’s 0.2.

@Sanglorian @ultidonki I’m looking forward to hearing your thoughts on these changes! Let me know what you think about the new Tuxeballs and any ideas you have for pricing.

@Sanglorian I'm having second thoughts about the tuxeball that changes the warm taste of the capture monster. Do you think it's really adding anything to the game, or was it a waste of time to implement it? Should we consider removing it?

Summary:
```
"Diurnal Tuxeball"
"Captures more easily during daytime, but its effectiveness is significantly reduced during the night."

"Nocturnal Tuxeball"
"Captures more easily during nighttime, but its effectiveness is significantly reduced during the day."

"Gambler Tuxeball"
"This tuxeball is known for its unpredictable nature. Its catch rate fluctuates wildly, with the chance of capturing a tuxemon ranging from extremely low to exceptionally high."
```

Now, I'd love to hear from you, @ultidonki. Take a look at the other types of capture devices we have and let me know which one you think would be a great addition. Keep in mind that Xero and Omni tuxeballs are exclusive to the Xero campaign, and the Park tuxeball is off-limits since it's only usable in the Park. If you've got a brand new idea for a tuxeball type, I'm all ears - share it with us and we can work on implementing it.

### CODE REVIEW

**Comment by JaskRendix** [comment]
I think it would be great to offer at least 2 or 3 different types of Tuxeballs in each shop to ensure some variety. I’m also open to other ideas! For instance, we could sell the Nocturnal Tuxeball during the night and the Diurnal Tuxeball during the day. What do you all think? Let me know your thoughts!

We could eventually add a couple of street vendors to some specific maps to mix things up a bit. For instance, places like Cotton Cave, Dragon's Cave, and Tunnel B could really benefit from that kind of variety.

- Paper Scoop: empty (closed)
- Cotton Scoop
- Leather Scoop
- Flower Scoop
- Timber Scoop
- Candy Scoop

Please include three key pieces of information: the **name**, its **price** (what it costs to buy), and its **cost** (the amount the store will give you if you decide to sell it back to them).

**Comment by Sanglorian** [comment]
Thanks for this @JaskRendix

Personally I'm not too excited by the shape- or season-based balls - that seems too specific for me. I can imagine players' inventories getting quite crowded. (Of course it doesn't hurt to have more options - which could appear in some campaigns but not others.)

I like the night and day ones and the gambler's ball - and the idea of pop-up street vendors selling them. 

What is your concern with the ball that changes the taste of the monster? I like that a player can guarantee that they'll get a monster with a stat boost, if they have the right ball and use it.

**Comment by JaskRendix** [comment]
> Personally I'm not too excited by the shape- or season-based balls - that seems too specific for me. I can imagine players' inventories getting quite crowded. (Of course it doesn't hurt to have more options - which could appear in some campaigns but not others.)

I think I'm going to drop the shape- and season-based balls. You're right, they might make the inventory a bit too cluttered. And upon further consideration, I realize that the formula for these special balls isn't that different from the day/night system, so it's not like we're losing a unique mechanic. By focusing on the more general modifier-based balls, like the Lavish Tuxeball, etc., we can keep things simpler and more streamlined. (see below)

> What is your concern with the ball that changes the taste of the monster? I like that a player can guarantee that they'll get a monster with a stat boost, if they have the right ball and use it.

That makes a lot of sense when you put it that way. I was worried about the ball's effect on the monster, but if it's a guaranteed stat boost, that's a different story. 

Speaking of which, I've been thinking about the improved Tuxeball, and I'm not a fan of the obvious "Mega Tuxeball" and "Ultra Tuxeball" names. Do you have any suggestions for something a bit more unique? We've already got the "Lavish Tuxeball" with a 1.5 modifier, but I'd love to hear some other ideas.

For instance (Tuxeball is price 50 and cost 10):
```
    Noble Tuxeball (1.25 modifier) price 150, cost 30
    Lavish Tuxeball (1.5 modifier) price 200, cost 40
    Grand Tuxeball (1.75 modifier) price 250, cost 50
    Majestic Tuxeball (2 modifier) price 400, cost 80
```
Descriptions

1. "Noble Tuxeball" "A moderate upgrade to the standard Tuxeball, offering a reliable capture rate."
2. "Lavish Tuxeball" "The ultimate capture tool, boasting a significantly higher capture rate than the Noble Tuxeball."
3. "Grand Tuxeball" "Offers an even higher capture rate than the Lavish Tuxeball, increasing the chances of a successful catch."
4. "Majestic Tuxeball" "Boasts the highest capture rate of all, making it the ultimate choice for catching even the most elusive tuxemon."

Shops
```
Cotton Scoop = Tuxeball
Leather Scoop = Noble + Lavish
Flower Scoop = Lavish + Grand
Timber Scoop = Grand + Majestic + Diurnal (during the day) + Nocturnal (during the night)
Candy Scoop = Majestic + Diurnal (during the day) + Nocturnal (during the night)
```
@Sanglorian sounds good?

**Comment by Sanglorian** [comment]
> ```
> Cotton Scoop = Tuxeball
> Leather Scoop = Tuxeball + Lavish
> Flower Scoop = Lavish + Grand
> Timber Scoop = Grand + Majestic + Diurnal (during the day) + Nocturnal (during the night)
> Candy Scoop = Majestic + Diurnal (during the day) + Nocturnal (during the night)
> ```
> 
> @Sanglorian sounds good?

Yes, that sounds good, thank you.

I'm just not sure what the difference between cost and price is - is that how much it can be bought for versus how much it can be sold back for?

**Comment by JaskRendix** [comment]
> I'm just not sure what the difference between cost and price is - is that how much it can be bought for versus how much it can be sold back for?

Think of it this way: when you return an item to a store, the amount they give you back is usually a percentage of the original price you paid. Eventually we can increase it, no issue.

Hey, I just wanted to let you know that I swapped out the tuxeball in Leather Town with the noble one, since I accidentally forgot. Also, I've set the price for nocturnal and diurnal items to 300, with a cost of 60. By the way, I took a screenshot of the Scoop Store in Candy Town during the day - I thought you might want to take a look.

Screenshot_2024-10-13_17-33-57

**Review by kerizane — APPROVED** [review]

**Comment by Sanglorian** [comment]
> > I'm just not sure what the difference between cost and price is - is that how much it can be bought for versus how much it can be sold back for?
> 
> Think of it this way: when you return an item to a store, the amount they give you back is usually a percentage of the original price you paid. Eventually we can increase it, no issue.

Oh thanks, that makes sense. I'd be happy to give all items the same % cost, e.g. 20% of the sale price as you've done here. 

> 
> Hey, I just wanted to let you know that I swapped out the tuxeball in Leather Town with the noble one, since I accidentally forgot. Also, I've set the price for nocturnal and diurnal items to 300, with a cost of 60. By the way, I took a screenshot of the Scoop Store in Candy Town during the day - I thought you might want to take a look.
> 
> Screenshot_2024-10-13_17-33-57

Thank you, that looks like a great set of options.

**Pull request merged**
