### PR TITLE
Emails and notes hospital (Spyder)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR introduces a series of emails in the hospital, shedding light on Dr. Lee. Lee had been secretly working to find a cure for the deadly Spyderbite virus. The emails reveal the shocking events that unfolded as Dr. Lee tried to save lives and the Cathedral tried to silence them.

---

Hospital: no flashbacks, simple emails, because a flashback triggered by a single line of dialogue might not be as impactful or clear. I'm having trouble figuring it out, and it's not like I can just hop on a computer in the hospital - the hospital doesn't exactly have a lot of them lying around. The only one I can think of is the one on the ground level, and that's the one I can access to check its boxes. I could add portables around.

**Email 1: Researcher 1 to Dr. Lee**
msgid "spyder_hospital_pc_message1" msgstr "E-mail from Researcher 1: 'Dr. Lee, I've been analyzing the virus samples, and I think we should try a different strain. It might trigger a new reaction in the antibodies.'"

**Note: Researcher 1 and Researcher 2 have been working together on the project, but they have different approaches and personalities. Researcher 1 is more cautious and methodical, while Researcher 2 is more impulsive and willing to take risks.**

**Email 2: Researcher 2 to Dr. Lee**
msgid "spyder_hospital_pc_message2" msgstr "Note from Researcher 2: 'Dr. Lee, I've found a potential combination of enzymes and antibodies that could slow down the mutation rate. I'm running simulations now.'"

**Email 3: Researcher 2 to Dr. Lee**
msgid "spyder_hospital_pc_message3" msgstr "Simulation results from Researcher 2: 'The enzyme-antibody combination shows promising results. We might have a cure on our hands.'"

**Email 4: Researcher 1 to Researcher 2**
msgid "spyder_hospital_pc_message_rivalry1" msgstr "E-mail from Researcher 1: 'Researcher 2, I'm not sure I agree with your approach. We need to be more careful and methodical in our research. Your simulations are promising, but we can't rush into conclusions.'"

**Email 5: Researcher 2 to Researcher 1**
msgid "spyder_hospital_pc_message_rivalry2" msgstr "E-mail from Researcher 2: 'Researcher 1, you're always so cautious and slow. We need to take risks and push the boundaries of what's possible. Our research is too important to be held back by your fear of failure.'"

**Email 6: Enforcer to Dr. Lee**
msgid "spyder_hospital_pc_message4" msgstr "E-mail from Enforcer: 'Dr. Lee, we have reason to believe that you have been conducting unauthorized research. We are at your location and require you to come with us.'"

**Email 7: Dr. Lee to Dr. Chen, Mentor**
msgid "spyder_hospital_pc_message5" msgstr "E-mail from Dr. Lee to Dr. Chen, Mentor: 'They are destroying my door, they want to arrest me because of unauthorized research. I can't let them take this away from me. This is a breakthrough, a real cure. I need to share it with the world.'"

**Email 8: Researcher 1 to Dr. Lee**
msgid "spyder_hospital_pc_message6" msgstr "E-mail from Researcher 1: 'Dr. Lee, I've managed to isolate a new strain of the virus that seems susceptible to our current treatments. However, I'm concerned about the security implications of this discovery. We need to be extra cautious about who knows about this.'"

**Email 9: Enforcer to Dr. Lee**
msgid "spyder_hospital_pc_message7" msgstr "E-mail from Enforcer: 'Dr Lee, we have received intelligence indicating that you're conducting unauthorized research within the company. We have reason to believe that your work poses a significant threat to our organization. You're hereby ordered to cease all research immediately and report to the security office.'"

**Email 10: Mysterious Informant to Dr. Lee**
msgid "spyder_hospital_pc_message8" msgstr "E-mail from Mysterious Informant: 'There are people who want to see you fail. They will stop at nothing to destroy your work. Be careful.'"

**Email 11: Robot Assistant to Dr. Lee**
msgid "spyder_hospital_pc_message9" msgstr "E-mail from Robot Assistant: 'I have detected unauthorized access to your research files. Please investigate immediately.'"

This revised ordering makes more sense, as Dr. Lee's email to their mentor Dr. Chen is a response to the Enforcers' arrival, and the subsequent emails from Researcher 1, the Enforcer, the Mysterious Informant, and the Robot Assistant all follow from the escalating situation.

---

Based on the context, I'll redistribute the emails to Dr. Lee's two PCs:

**Dr. Lee's PC 1 (Research PC)**

* Email 1: Researcher 1 to Dr. Lee (msgid "spyder_hospital_pc_message1")
* Email 2: Researcher 2 to Dr. Lee (msgid "spyder_hospital_pc_message2")
* Email 3: Researcher 2 to Dr. Lee (msgid "spyder_hospital_pc_message3")
* Email 8: Researcher 1 to Dr. Lee (msgid "spyder_hospital_pc_message6")
* Email 11: Robot Assistant to Dr. Lee (msgid "spyder_hospital_pc_message9")

**Dr. Lee's PC 2 (Personal PC)**

* Email 6: Enforcer to Dr. Lee (msgid "spyder_hospital_pc_message4")
* Email 7: Dr. Lee to Dr. Chen, Mentor (msgid "spyder_hospital_pc_message5")
* Email 9: Enforcer to Dr. Lee (msgid "spyder_hospital_pc_message7")
* Email 10: Mysterious Informant to Dr. Lee (msgid "spyder_hospital_pc_message8")

**Researcher 1's PC**

* Email 4: Researcher 1 to Researcher 2 (msgid "spyder_hospital_pc_message_rivalry1")

**Researcher 2's PC**

* Email 5: Researcher 2 to Researcher 1 (msgid "spyder_hospital_pc_message_rivalry2")

### CODE REVIEW

**Comment by JaskRendix** [comment]
https://github.com/user-attachments/assets/dc4d6c32-65a0-4f34-ae63-ca3b163c7a02


https://github.com/user-attachments/assets/ece7272d-272a-4de6-934c-e9198911c26c


https://github.com/user-attachments/assets/12d1bf60-6b9a-4c22-9f8a-10434071dc09

**Comment by Sanglorian** [comment]
Thanks for these @JaskRendix, I think they'll do a nice job of fleshing out the backstory. 

I think the main thing is to incorporate them seamlessly into the story. I think the best way to do this would be when the player finds a clue relating to the events. For example:
* Zircon argues with Argon: what if the player could stumble across Zircon somewhere, and talk to him - and if they say yes to him telling them his side of the story, that's when the flashback begins?
* Or what if Zircon is burnt out, and needs reminders to remember what happens? Then as the player finds e.g. secret files, CD roms, and other clues, the player could visit him, and he would remember more and more (presented as flashbacks).
* Similarly for other characters - if you meet the Florist, you might be able to unlock her flashback. 

It amused me that people disagree on where the name "Xeon" comes from! And I had a good chuckle at the names of the people who work at GoodChat! 

Some feedback: 
* I think the dialogue could be trimmed a fair bit - there's parts that are quite wordy. When watching them, I felt around 45 mins to 1 and a half minutes was a good sweet spot. 
* Some of the same themes come up in a few different flashbacks without introducing a new idea or plot development. Particularly the idea of unintended consequences - which comes up in Argon and Looten's flashbacks, and with the Florists - and often expressed in quite similar language even though it's very different characters talking. I wonder if some flashbacks can be combined or cut if they explore the same themes. 
* When Dr Elara introduces the Xeon, Zircon and Argon then go on to talk about the ethical implications as if Xeons are already common knowledge. I wasn't sure what was going on there. 
* I didn't think the descriptions of what the characters were doing or how they were expressing themselves in brackets was necessary - I think the dialogue was enough to communicate this. 
* I liked the use of reaction bubbles in one scene - that could be nice to have in more scenes, both to replace the descriptions in brackets, and so it's clear to the player which sprite corresponds to which character.

Overall though I think they're a really nice addition, allowing us to explain more of the plot. And if they can be worked in organically, then I think they'll feel like a natural part of the adventure and improve the play experience.

**Comment by JaskRendix** [comment]
> I liked the use of reaction bubbles in one scene - that could be nice to have in more scenes, both to replace the descriptions in brackets, and so it's clear to the player which sprite corresponds to which character.

Yeah, I'm glad you liked that! I was actually testing out the reaction bubbles to see if they'd help clarify who's speaking, and it sounds like they did the trick. I'm definitely thinking of using them more widely now, especially in scenes with multiple characters. It's a nice way to visually cue the player and make the dialogue feel more dynamic.

> Overall though I think they're a really nice addition, allowing us to explain more of the plot. And if they can be worked in organically, then I think they'll feel like a natural part of the adventure and improve the play experience.

Totally agree, I think they'll really help flesh out the story and make the game more engaging. To make sure they're integrated smoothly, I was thinking of splitting out each flashback into separate pull requests. That way, we can review and add them in the right locations, kind of like a showroom where we can see how they fit into the overall narrative.

**Comment by JaskRendix** [comment]
> I liked the use of reaction bubbles in one scene - that could be nice to have in more scenes, both to replace the descriptions in brackets, and so it's clear to the player which sprite corresponds to which character.

Yeah, I'm glad you liked that! I was actually testing out the reaction bubbles to see if they'd help clarify who's speaking, and it sounds like they did the trick. I'm definitely thinking of using them more widely now, especially in scenes with multiple characters. It's a nice way to visually cue the player and make the dialogue feel more dynamic.

> Overall though I think they're a really nice addition, allowing us to explain more of the plot. And if they can be worked in organically, then I think they'll feel like a natural part of the adventure and improve the play experience.

Totally agree, I think they'll really help flesh out the story and make the game more engaging. To make sure they're integrated smoothly, I was thinking of splitting out each flashback into separate pull requests. That way, we can review and add them in the right locations, kind of like a showroom where we can see how they fit into the overall narrative.

---

I'm a bit confused - in one of the dialogues in route 3, Zoolander is referred to as a woman. Can you clarify, is Zoolander actually a female character? 

"spyder_route3_roxby3": "I hope Boss is not mad - she gets angry so fast, \n But she is a nice person and has a heart like a diamond."

You can see the updated elements in the top of the page.

**Comment by Sanglorian** [comment]
> I'm a bit confused - in one of the dialogues in route 3, Zoolander is referred to as a woman. Can you clarify, is Zoolander actually a female character?
> 
> "spyder_route3_roxby3": "I hope Boss is not mad - she gets angry so fast, \n But she is a nice person and has a heart like a diamond."

Ah yes, Zoolander is female.
> 
> You can see the updated elements in the top of the page.

Thanks! Looks good to me.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
