### PR TITLE
introduction tastes

### PR DESCRIPTION
**Pull request by JaskRendix**
As discussed here: https://github.com/Tuxemon/Tuxemon/pull/1638#issuecomment-1444408024

PR addresses the introduction of tastes.

@Sanglorian here we are, random assignation of the tastes at the capture as well as automatic stats update.

Everything is based on: https://wiki.tuxemon.org/Stats#Tastes
```
    + Speed: Peppy
    - Speed: Mild
    + Melee: Salty
    - Melee: Sweet
    + Armour: Hearty
    - Armour: Soft
    + Ranged: Zesty
    - Ranged: Flakey
    + Dodge: Refined
    - Dodge: Dry
```
I guess taste warm and cold cannot be change. Is it true? If not I need to set up an action to change it. Let me know.

Tested + isort + black

The info will appear on the monster journal (the one you can access through the monster menu).
Screenshot from 2023-02-25 07-55-10

Unrelated questions: regarding friendship field, did you imagine it as a numeric parameter? if yes, like a percentage where 100% is equal to best friend? if yes, then what is the max value (eg. 100?). If yes, at the capture, the default value will be 50? Let me know.

### CODE REVIEW

**Comment by Sanglorian** [comment]
Sounds good, thank you! 
I wouldn't worry about friendship field at this point as I haven't figured out how it would work or what we'd use it for.

**Comment by JaskRendix** [comment]
Understood

**Comment by kerizane** [comment]
The wording sounds a bit like the monster is sweet when it's cold and salty when it's hot? Maybe Likes/Dislikes?
Or :) and :(

**Comment by JaskRendix** [comment]
@Sanglorian ?

**Comment by Sanglorian** [comment]
We could just say "Tastes: Salty, Sweet" or "Likes Sweet or Salty Food"? Really the warm/cold thing is just to make sure each monster gets one bonus and one penalty instead of some getting two bonuses or two penalties

**Comment by JaskRendix** [comment]
That's good, it takes less space too.
Screenshot from 2023-02-26 07-49-59

fixed typehints

**Review by kerizane — DISMISSED** [review]

**Comment by kerizane** [comment]
Need to fix the conflict

**Review by kerizane — APPROVED** [review]

**Pull request merged**
