### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by vnmabus**
Spanish translation updated:

- Added translations for attacks
- Added translations for new plot changes
- Added translations for 37707 town.

### CODE REVIEW

**Comment by Sanglorian** [comment]
This is really cool! I've set up the wiki so Spanish translations can be added there too, if desired!

**Comment by airon90** [comment]
@vnmabus could you please explain how to translate Tuxemon now that the entire translation system has been changed? Thank you very much!

**Comment by vnmabus** [comment]
You have to add to  `mods/tuxemon/l18n/<LANGUAGE>/LC_MESSAGES/base.po` the msgid/msgstr pairs missing from `mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po` and translate only the mgstr. In order to test your changes you have to manually remove the `*.mo` files of your language in order for them to be reconstructed before launching the game (at least until a solution for #661 is merged).

**Comment by bitcraft** [comment]
@vnmabus thanks for your effort to update the translations!  i really appreciate the effort.  i know you have made some changes on the locale before, did you work on the json before?  what do you think of the new system?

**Comment by vnmabus** [comment]
I do not see a big difference for now, but I think that gettext is helpful for plural forms and gender, so probably when those situations arise it will be more useful.

**Comment by bitcraft** [comment]
ok cool thanks.  i just realized i may have asked before.  i will remember moving forward ^_^'

**Comment by airon90** [comment]
@vnmabus I manually checked for new keys or changes in old keys. Is there a way to do that automatically?

**Comment by vnmabus** [comment]
I do not know, I am not an expert in gettext... I have done it manually but I would have used the commit history if the names of the files had not change.

**Comment by airon90** [comment]
For that I created #759

**Pull request merged**
