### PR TITLE
Save system improvements

### PR DESCRIPTION
**Pull request by kerizane**
Implements the redesign detailed in:
https://github.com/Tuxemon/Tuxemon/issues/265

Fixes:
https://github.com/Tuxemon/Tuxemon/issues/411

Code is backwards compatible with current save files. 

Screenshots taken with the old system will be lost, didn't seem any point in preserving that.

### CODE REVIEW

**Comment by bitcraft** [comment]
Wow nice work man!  Its cool that you were able to solve a couple issue with this one PR.  I only have a cpuple concerns about it

* cbor is great (i use it, too!) but i'd prefer to keep the json format since its useful for debugging
* when you edit a method/function signature, please keep the docstrings up to date.

Sorry about the cbor thing, because I can see you put a lot of effort into preserving the json format, but I don't want that to be merged as-is.  I could accept it if there was a config file option to change the save/load format, then remove the logic & fallbacks when loading...for example: https://github.com/Tuxemon/Tuxemon/pull/417/files#diff-fada4d66045cd1c7a22769a1840722f0R113

Keeping the docstrings is important because smart editors like pycharm, or static analysis tools (pyflake/pylint, etc) can run a check the source code before runtime to eliminate bugs and regressions
when signature changes.  Please correct the function signatures.

Myself and ShadowApex are often in the discord. so in the future, it would be awesome to check with us about big changes like the save game format.  JSON files make it possible debug and edit save file to help development, and it would make my debugging more difficult without it.

Other than that, I'd love to merge this and fix the really annoying "cannot save when poisoned" bug!  Thank you!

**Comment by kerizane** [comment]
Np, I'll get it done.

**Comment by kerizane** [comment]
I'll add the config option to choose which method to save, but leave it able to load either type (no reason to break things when we don't need to).

**Comment by kerizane** [comment]
Done.

**Pull request merged**
