### PR TITLE
458 Tuxepedia and tuxemon JSON interfaces

### PR DESCRIPTION
**Pull request by AndyMender**
- Addresses #458 (opened by me)
- Partially addresses #347 

This PR introduces:
- A `tuxepedia` module located at "tuxemon/core/tuxepedia"
- A class for scraping the [Tuxepedia](https://wiki.tuxemon.org) wiki page called `TuxepediaWebExtractor` located in `tuxepedia.extractor`
This class is an interface based on [scripts/sync-wiki-monster.py](https://github.com/Tuxemon/Tuxemon/blob/development/scripts/sync-wiki-monsters.py), however made in a more modular fashion and importing even the tuxemon cry sound files.
- An API to sync with the Tuxepedia using `TuxepediaWebExtractor` as the backend and extract JSON data for individual tuxemon
- The API contains auxiliary methods to manage SQLite connections if that is needed in the future
- An `__init__` file defining standard local file paths as well as remote URL paths for easy reference by the API and `extractor`
- Sprites are stored at "tuxemon/resources/gfx/sprites/tuxemon"
- Sounds are stored at "tuxemon/resources/sounds/tuxemon"
- Tuxemon JSON records are stored at "tuxemon/resources/db/tuxemon"

Everything is modular so it doesn't interfere with existing code :).

Example JSON record for Aerodeer. Unfortunately, `sync-wiki-monsters.py` seems to be broken and fails when a sprite HTML `src` attribute is missing.
```json
{"Aerodeer":  
     {
         "tuxepedia_url": "https://wiki.tuxemon.org/index.php?title=Aerodeer", 
         "types": ["Untyped"], 
         "sprites": {
             "battle1": null,
             "battle2": null,
             "menu1": null,
             "menu2": null
         },
         "blurp": "",
         "call": null
     }
}

```

### CODE REVIEW

**Comment by bitcraft** [comment]
So if I understand correctly, this is usable from the scripts/sync-wiki-monster.py script?  I think it would be nice to not have competing implementations of the sync, so could you verify that it is 1:1 replacement (no missing features?)  If so, please remove the existing code and set the script to call this one instead.

**Comment by bitcraft** [comment]
Also, I think you meant to link #347 in your comment, not #437.

**Comment by AndyMender** [comment]
> So if I understand correctly, this is usable from the scripts/sync-wiki-monster.py script? I think it would be nice to not have competing implementations of the sync, so could you verify that it is 1:1 replacement (no missing features?) If so, please remove the existing code and set the script to call this one instead.

The only thing I removed was the `is_valid_monster` feature since the sync is only meant to download the sprites/sounds and prep the JSONs, not to validate whether a monster record is complete. This could be done at a later stage when loading a JSON for a specific tuxemon into the game. I left the original script in place for backward compatibility. I will check both the script and my implementation for any discrepancies and fix them if there are any :).

The other issue is that the existing tuxemon JSON files contain a lot more information than just the type, sprites, sounds, name, etc. `TuxemonStore.sync_with_remote` considers this and when it encounters an existing tuxemon JSON, it will only update the fields/paths which are new and only if `overwrite` is set to `True` (default behavior).


> Also, I think you meant to link #347 in your comment, not #437.

Yes, sorry, I corrected the original post promptly :).

**Comment by bitcraft** [comment]
I really like that the script can update existing monsters.  With all the changes, I think it is a good to merge.

**Pull request merged**
