### PR TITLE
fix exteriors

### PR DESCRIPTION
**Pull request by JaskRendix**
following #1616 so we can distinguish between interiors and exteriors:
- flowers animated everywhere;
- extended the Tuxemart animation (M moving to almost all the cities);
- minor fixes (often collisions zone outside the map);
- added a new building, red hospital (before there was only the green one);
- created the new core_city_and_country.png, added the source inside the PNG and deleted the old one (identical);
- fixed a bunch of signs and added some;
- fixed some east/west inside the maps;

Spyder and Xero maps exteriors are done.

### CODE REVIEW

**Comment by JaskRendix** [comment]
@Sanglorian since the tileset **Outdoor_Tiles_-_City_and_Country_-_by_ArMM1998** is used a lot in cities and routes (less in interiors), I guess we can promote it to CORE_, because honestly I don't know if it makes sense import all of it inside other COREs.

If you agree, then what about the name? Is **core_city_and_country** good? (we'll update the credits too)

**Comment by JaskRendix** [comment]
@Qiangong2 same question about the trees, for Xero do you want to keep the actual trees or do you want one of the two new options? It could be a way to distinguish one from the other. Let me know.

**Comment by Qiangong2** [comment]
I don't necessarily have a preference either way. If I had to choose, I personally prefer the look of tree1 over tree2.

**Comment by Sanglorian** [comment]
Thanks heaps! Promoting city and country to core under that name sounds good to me.

I'm honestly not fussed which tree design we use - up to which you prefer, I'd say.

**Comment by JaskRendix** [comment]
No changes in trees, kept the same, I noticed that we need more signs, but I'm going to complete it in another PR.

Next PRs: signs and move unused files.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
