### PR TITLE
Combat update

### PR DESCRIPTION
**Pull request by kerizane**
Implemented most of the new combat ideas, the main thing missing is the cyclic statuses. 

Feel free to merge into a separate branch for now.

### CODE REVIEW

**Comment by kerizane** [comment]
The following mons didn't have a movelist defined:
angrito,
anu,
chromeye,
dinoflop,
enduros,
fancair,
galnec,
happito,
poinchin,
sadito,
saurchin,
skwib,
spighter,
windeye

**Comment by Sanglorian** [comment]
Wow! An incredible piece of work, thank you! 

I don't have the expertise to check it, but please let me know if there's anything on the design side that I can help with (resolving any ambiguities, contradictions, etc, that came up while you were doing the implementation, for example). 

Re the monsters without move lists, I'll put something together for them. I missed Spighter by accident. The others with missing lists are from [Set 2](https://wiki.tuxemon.org/index.php?title=Set_2). I think for now I'll create a few generic move lists for new tuxemon (e.g. generic Wood list, generic Water list, etc). As we play the game, I think ideas for new techniques and new niches that move lists can fill will come naturally.

**Comment by kerizane** [comment]
I'll get you the scripts this week. 

I'll migrate the data to the database in another ticket.

Filenames are fixed

**Comment by kerizane** [comment]
Added 2/3 of my script, last one coming in a few days. Quick and dirty, might tidy them up at some point.

They should be called from the root project folder, make sure you manually set the path to the spreadsheet. I adjusted the excel doc slightly for my convenience, see Sheet4:
[techniques.xlsx](https://github.com/Tuxemon/Tuxemon/files/2503488/techniques.xlsx)

You get a ton of output from the script, that's due to the excel library.

**Comment by Sanglorian** [comment]
Thanks @kerizane  -- I've also updated the wiki to have all the technique and move list information now. I don't anticipate it changing much in the near future. 

Re the Nudiflot Male/♂ issue, @bitcraft,  does this mean I should change the monster's page title in the wiki to "Nudiflot Male"?

**Comment by kerizane** [comment]
Still have one more script to do.

**Comment by kerizane** [comment]
I've included the final script, so this is ready to go. 

If you need to, use the already existing sync_tuxemon_wiki script to update the mons. Unfortunately, it nukes the movelists, so set_movelist.py needs to be run after.

Nudiflot m/f can be left as is. The script will work around them.

**Pull request merged**
