### PR TITLE
sprites

### PR DESCRIPTION
**Pull request by JaskRendix**
PR upload some of the sprites I edited.

Nothing new, changed hair color as well as clothes color.

The reason is that I'm creating some NPCs and I need more variety.

### CODE REVIEW

**Comment by bitcraft** [comment]
have you edited existing sprites?  or does this PR add new ones only?

**Comment by NeonFlames** [comment]
> have you edited existing sprites? or does this PR add new ones only?

Just looked over it and its only new sprites

**Review by NeonFlames — APPROVED** [review]

**Review by bitcraft — APPROVED** [review]

**Comment by bitcraft** [comment]
this is great, thanks for the new sprites

**Comment by JaskRendix** [comment]
You're welcome

**Pull request merged**
