### PR TITLE
New clock and rect module

### PR DESCRIPTION
**Pull request by bitcraft**
Adding a couple files to break up the changes with the client view.

Rect: used when pygame is not available
Clock: Experimental scheduler which is very accurate and easy to use

### CODE REVIEW

**Comment by xirsoi** [comment]
What benefits does the pure Python Rect class confer?

**Comment by bitcraft** [comment]
So that pygame is not needed as a dependency.  I’d like to be able to run the server with zero pygame imports. This is a step towards that.

**Comment by xirsoi** [comment]
This looks good to me then.

**Comment by Qiangong2** [comment]
So would rect give Tuxemon the ability to run on platforms without pygame?

**Comment by bitcraft** [comment]
The immediate goal of things like the Rect and Clock module are to allow the server portion to run without pygame.  A long term, unrealistic goal would be to allow running the graphical parts on using another graphics library.  Im not committed to it or endorsing it though.  Pygame is is already well supported on a lot of systems and will be more-so when the 2.0 version is released.

**Comment by Qiangong2** [comment]
Okay, thanks for clarifying :)

**Pull request merged**
