### PR TITLE
comparison (equals, not_equals, etc.)

### PR DESCRIPTION
**Pull request by JaskRendix**
follows #2167 

PR continues the task with the Comparison class, in this way we can centralize all the sign operators:
- removes all the comparisons from actions and conditions;
- adds a small fix to get_player_monster, to avoid the possibility to close it without selecting anything (if filters haven't been set);

### CODE REVIEW

**Comment by xirsoi** [comment]
I kinda liked it better when we could use the operators (">=" instead of "greater_than_equal").

How does @Sanglorian feel about it?

**Comment by JaskRendix** [comment]
@xirsoi I have added the >, <, etc.

**Comment by Sanglorian** [comment]
Thanks both! I don't mind either way, including both sounds like a great compromise!

**Review by Grimmys — APPROVED** [review]
Very interesting refactoring, code was quite ugly before, congrats!

**Review by bitcraft — APPROVED** [review]

**Pull request merged**
