### PR TITLE
new locations

### PR DESCRIPTION
**Pull request by JaskRendix**
it'll follow #1619 

new locations:
- shaft1 (both Xero and Spyder) -> Leather City
- shaft2 (both Xero and Spyder) -> Leather City
- gym (Spyder) -> Leather City
- misa house (Xero) -> Cotton Town
- house5 work in progress
- house6 work in progress

Gym
spyder_leather_gym
Shaft1
leather_shaft1
Shaft2
spyder_leather_shaft2
House5
spyder_house5
House6
spyder_house6
Misa House
cotton_misa_house

### CODE REVIEW

**Comment by JaskRendix** [comment]
@Qiangong2 regarding Xero I noticed the **meet_misa**.tmx 

Is it your map or an old one? Do you have plans for this location?
If not, do you mind if I do some edits (like moving the entrance in front, renaming in **cotton_misa_apartment**), and connect it (teleport, etc)? The same I would like to do with **riverside_boat_centre** (it's empty and unused) and opening another close building in Cotton (renaming it too).

**Comment by Qiangong2** [comment]
Feel free to do what you want with it. It no longer applies. It was used originally because there was no way to move NPCs other than removing and adding them. I don't plan on using it

**Comment by JaskRendix** [comment]
@Qiangong2 ok, thanks, I want to inform you that inside meet_misa there are the some msgids (PO file).
These will remain inside the PO file.
```
youcantleave
discovered_a_person
a_serious_discussion
oops
backstory
backstory9
sorryfurthis
```

**Comment by Sanglorian** [comment]
> @Sanglorian during the PR to fix interiors I noticed that house5 and house6 are unused and without collisions zone / events.
> 
> Do you mind if I use them, insert some NPC dialogues coherent with the city/town, and open some closed building? Do you have other plans?

No other plans, so go right ahead! Thanks for asking

**Comment by JaskRendix** [comment]
@Sanglorian the job is done, if you're curious about the dialogues, feel free to look in the PO here in the PR.
It's not much, but I hope interesting.

**Comment by Sanglorian** [comment]
Thanks, that's looking good. 

In the gymbro house I don't get the references to Sigma or knocking on the restroom door and running away. 

Is spyder_flower_sandy the niece that the player is being asked about marrying? Sandy uses a child's sprite, so if so better to swap her out for say Florist, Homemaker or Picnicker.

The boss of Shaft is actually a woman, rather than a man.

**Comment by JaskRendix** [comment]
No particular reference regarding Sigma and Gymbros.

Regarding spyder_flower_sandy, I checked again, and there was a mistake. I used the npc only because of the sprite (only NPC with childactor as sprite) and I didn't want to create a new NPC. I chooses to represent the child, the little brother, so no problem.

Fixed the Boss Shaft

**Review by kerizane — DISMISSED** [review]

**Review by kerizane — APPROVED** [review]

**Pull request merged**
