### PR TITLE
[sprites] remove hell/dread knight that has a licensing problem

### PR DESCRIPTION
**Pull request by kevin2kevin2**
See https://opengameart.org/forumtopic/fiveasone-compromised-pixel-assets

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks, good catch!

**Comment by kerizane** [comment]
Are we using this sprite anywhere
?

**Comment by Sanglorian** [comment]
I don't think so, just one that got imported from the wiki (I've deleted it there now).

**Comment by Sanglorian** [comment]
Other FiveAsOne sprites we may have to remove: 

https://wiki.tuxemon.org/index.php?title=Category:FiveAsOne

Am deleting from the wiki now.

**Comment by JaskRendix** [comment]
> Are we using this sprite anywhere ?

No, it's not used.

**Comment by JaskRendix** [comment]
> Other FiveAsOne sprites we may have to remove:
> 
> https://wiki.tuxemon.org/index.php?title=Category:FiveAsOne
> 
> Am deleting from the wiki now.

@Sanglorian I'm going to open a new PR to get rid of those.
Do you want to delete completely Birb Robo?
Then I'm going to delete disciple.png and tentacle metal (replacing it by icetacle as you did in the wiki)

**Review by kerizane — APPROVED** [review]

**Pull request merged**
