### PR TITLE
Taba battle area 4th acolyte

### PR DESCRIPTION
**Pull request by Qiangong2**
Adds the 4th acolyte to the story and ensures the player's Tuxemon is at least level 16 for the upcoming boss

### CODE REVIEW

**Review by JaskRendix — APPROVED** [review]

**Comment by JaskRendix** [comment]
Approved before noticing #2289 

First solution: wasted some time to set up a proposal for a chain of events with player vs acolyte with 3 monsters, here the file: 
[taba_ba_br_4.txt](https://github.com/Tuxemon/Tuxemon/files/14482078/taba_ba_br_4.txt)
in this case these msgid aren't necessary anymore (if you accept):
```
msgid "tabaacolyte4talk3"
msgstr "Heh. You've got spirit, I'll give you that.\n"
"But that's not even half of my power!\n"
"FOR THE GLORY OF OMNICHANNEL... YOU SHALL NOT PASS!!"

msgid "tabaacolyte4talk4"
msgstr "Hahaha! Is that really all you got?\n"
"You'll have no chance of beating the Battle Area Master if this is your limit. Let's test it more!\n"
"FOR THE GLORY OF OMNICHANNEL... YOU SHALL NOT PASS!!"
```

if you want to maintain your method 1 vs 1 vs 1 (separated monsters), it'll take me to waste some time to fix all the chain of events

**Comment by JaskRendix** [comment]
here you go buddy, this is the original one (separated monsters), I wasted some time to fix all the variables, as you can notice you used too many variables, this was the cause of #2289 (crash related to the wrong position of lock/unlock as well as multiple boxes): [taba_ba_br_4.txt](https://github.com/Tuxemon/Tuxemon/files/14483363/taba_ba_br_4.txt)

**Comment by Qiangong2** [comment]
@JaskRendix Thank you for the fixes. Just some clarification: why do we need to take out the `last_battle: check` variable? It's there to reset it. Otherwise, if you lost the previous battle, it will immediately run teleport_faint, right?

Also, shouldn't the unlock_controls be after the battle, not before? Otherwise there's a chance that the player could move and be out of position.

**Comment by JaskRendix** [comment]
@Qiangong2 

>  Just some clarification: why do we need to take out the last_battle: check variable? It's there to reset it. Otherwise, if you lost the previous battle, it will immediately run teleport_faint, right?

it could happen, but it depends on the event you set up as well as on the complexity of the events (this one was pretty tough). You put three fights against the same dude, one after another. Look at what I did here, this is the reason why I decided to use **is char_defeated player** instead of last_battle. Because **is char_defeated player** will kick in after the battle -> checks the player's party -> confirm everyone is fainted -> true -> then the event starts
```
  <object id="18" name="check second battle-loss" type="event" x="192" y="16" width="16" height="16">
   <properties>
    <property name="act1" value="clear_variable 2ndbattle"/>
    <property name="act2" value="char_face loch,left"/>
    <property name="act4" value="translated_dialog tabaacolyte4talklost"/>
    <property name="act7" value="teleport_faint 1.5"/>
    <property name="cond1" value="is variable_set 2ndbattle:done"/>
    <property name="cond2" value="is char_defeated player"/> 
   </properties>
  </object>
```

> Also, shouldn't the unlock_controls be after the battle, not before? Otherwise there's a chance that the player could move and be out of position.

I'm accustomed to unlock before the battle because during the battle kicks in the **CombatState** (**start_battle**, during this state the player cannot move). Immediately the battle kicks in the **DialogState** (eg. translated_dialog) and the player cannot move (eg read a sign and/or speak with an NPC, and the player cannot move until there is the dialogue open).

But if you think someone can keep pressed any arrow (up, down, right or left), then feel free to add lock and unlock again, but lock and unlock in the same event, eg here:
```
    <property name="act1" value="clear_variable 1stbattle"/>
    <property name="act2" value="char_face loch,left"/>
    <property name="act3" value="translated_dialog tabaacolyte4talklost"/>
    <property name="act7" value="teleport_faint 1.5"/>
    <property name="cond1" value="is variable_set 1stbattle:done"/>
    <property name="cond2" value="is char_defeated player"/>
```
to 
```
    <property name="act1" value="lock_controls"/>
    <property name="act2" value="clear_variable 1stbattle"/>
    <property name="act3" value="char_face loch,left"/>
    <property name="act4" value="translated_dialog tabaacolyte4talklost"/>
    <property name="act6" value="unlock_controls"/>
Note: unlock always before any teleport_
because when the teleport_ kicks in, it's another state and it gets locked / unlocked by default
    <property name="act7" value="teleport_faint 1.5"/>
    <property name="cond1" value="is variable_set 1stbattle:done"/>
    <property name="cond2" value="is char_defeated player"/>
```

**Comment by Qiangong2** [comment]
PR has been updated with requested changes

**Comment by Qiangong2** [comment]
@JaskRendix Could you please take a look and verify everything was changed correctly?

**Comment by JaskRendix** [comment]
Everything looks fine

**Review by bitcraft — APPROVED** [review]

**Pull request merged**
