### PR TITLE
Create flatpak manifest

### PR DESCRIPTION
**Pull request by Murmele**
Hi,
I created a flatpak manifest to easy install Tuxemon. I get it work but I have to move some folders:

1) I don't have write access to the install folder, whereas I don't have access to the locales(this is because the install folder is blacklisted from flatpak) . So I moved them into the folder ~/.tuxemon
2) In paths.py I changed from BASEDIR to USER_GAME_DIR:
L18N_DIR = os.path.join(USER_GAME_DIR, "resources", "l18n")
LOCALE_PATH = os.path.join(USER_GAME_DIR, "resources", "db", "locale")

A question occured for me:
in locale.py:
def discover_locale_dirs(self):
        """Returns locale directories discovered in the base & user data directory

        :returns: List of discovered locale directories

        """
        directories = [os.path.join(paths.BASEDIR, paths.LOCALE_PATH)]

why do you hjoin a second time the BASEDIR to the LOCALE_PATH?

At the moment I don't know how to move the ressource folder to the ./tuxemon folder when installing the flatpak package, but I will find that out. Or maybe you suggest a better place for this folder.

How should I handle this two paths?

### CODE REVIEW

**Comment by bitcraft** [comment]
@Murmele thanks for the work on a flatpak.  there have been a lot of changes with the tuxemon path/config code.  please take another look and update your pr if you are still willing to get this feature implemented.  im not familiar with flatpak packaging.  why do the folders need to be moved?

**Comment by bitcraft** [comment]
@Murmele our folder structure has changed.  please take a look and check what you need to do.

**Comment by Murmele** [comment]
Hi bitcraft,

I will check it out as soon as possible.

**Review by bitcraft — APPROVED** [review]
I’ll treat this as WIP.  It’s not conflicting with anything at the moment.

**Comment by bitcraft** [comment]
@Murmele thanks for you contribution. I’m going to merge as-is.

**Pull request merged**
