### PR TITLE
added new floor and wall tiles, including stairs

### PR DESCRIPTION
**Pull request by rubberduck9999**
reworked a lot of indoor tiles, merged them into three main tilesets:
core_indoor_walls.png, core_indoor_floors.png and core_indoor_stairs.png

I also noticed that some core maps were changed but I didn't meant to do so

### CODE REVIEW

**Comment by rubberduck9999** [comment]
edit: gave it a better name

**Comment by bitcraft** [comment]
what are the changes to the core maps?

**Comment by rubberduck9999** [comment]
I did not mean to change the core maps, is was an accident, I think while opening a map it said that something with a tileset changed and somehow I saved these changes. I wanted to revert these changes when I saw it and saw that I already committed these earlier.
So these changes could be reverted I think

**Comment by bitcraft** [comment]
ok got ya.  so in the list here, you don't want to include changes to the maps with the yellow boxes?
image

**Comment by rubberduck9999** [comment]
yes, that's it, the testmap also isn't so important too and can be omitted, at least right now

**Comment by bitcraft** [comment]
ok, cool.  you should be able to revert them by checking out the file from the development branch
```
git checkout development mods/tuxemon/maps/cotton_cafe.tmx
git checkout development mods/tuxemon/maps/spyder_bedroom.tmx
git checkout development mods/tuxemon/maps/spyder_omnichannel1.tmx
```
...then commit those changes and push them to your branch
if you're not comfortable with that, i can merge this and revert them after the fact

**Comment by rubberduck9999** [comment]
ok, I reverted these changes, also removed the now outdated colorpalette. This should be all for now. The new outdoor tiles are still in progress and need more time for finishing and testing, but the indoor tiles are ready

**Comment by bitcraft** [comment]
cool, i see those maps are now reverted.  is it ready now?

**Comment by rubberduck9999** [comment]
yes, everything should be ready now

**Review by bitcraft — APPROVED** [review]
looks great!  this is exciting to merge in, thank you!

**Pull request merged**
