### PR TITLE
delete maps

### PR DESCRIPTION
**Pull request by JaskRendix**
@Sanglorian these maps are duplicate of already existing maps, I would like to know what do you think about deleting:

- cotton_town_spyder is the copy of cotton_town in Xero (unused);
- daycare_centre is the copy of daycare in Xero (unused);
- paper_scoop and paper_town don't exist in Xero, if someone wants to add those, it takes less effort to copy and past the Spyder version than building up based on unused maps;
- tuxe_mart.tmx is the old version of the new tuxe_mart_taba;

It can confuse newcomers too.
Let me know what do you think about.
Do you want to signal some maps that can be deleted too?

### CODE REVIEW

**Comment by Sanglorian** [comment]
That's fine by me, just worth checking with @Qiangong2 too

**Comment by Qiangong2** [comment]
The Xero campaign follows the exact same map as the Spyder campaign, so the maps should have the same base. Overall, I don't see any issue with the deletions.

**Review by Qiangong2 — DISMISSED** [review]

**Comment by kerizane** [comment]
Merge conflict

**Comment by JaskRendix** [comment]
I was unable to solve the conflict for tuxe_mart, I'm going to open a separate PR.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
