### PR TITLE
Update build system

### PR DESCRIPTION
**Pull request by NeonFlames**
Switch from setup.py to pyproject.toml

### CODE REVIEW

**Comment by NeonFlames** [comment]
Looks like I have some things to fix up.

**Comment by NeonFlames** [comment]
If anyone has an idea on how to fix the problem I'm all ears because I've looked through the setuptools documentation and found nothing (Although I may have missed it).

**Comment by JaskRendix** [comment]
I don't know if this is the reason, I noticed that before there was this:
```
for root, dirnames, filenames in os.walk("tuxemon"):
    for filename in fnmatch.filter(filenames, "__init__.py"):
        matches.append(os.path.join(root, filename))
```
So technically:
```
[tool.setuptools.packages.find]
where = [""]
include = ["tuxemon*"]
namespaces = false
```
As advised here: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages below the section pyproject.toml (BETA), the note.

**Comment by NeonFlames** [comment]
It still fails to build an editable install and a normal install with the namespaces key added as advised by the documentation.

**Comment by JaskRendix** [comment]
Remember: https://setuptools.pypa.io/en/latest/userguide/development_mode.html#legacy-behavior 
I was reading the raw logs of the failed action and I wonder if we need to add the wheel: requires = ["setuptools", "wheel"]
There are some deprecations in the raw logs pointing to it (neteria, etc).

**Comment by NeonFlames** [comment]
> Remember: https://setuptools.pypa.io/en/latest/userguide/development_mode.html#legacy-behavior I was reading the raw logs of the failed action and I wonder if we need to add the wheel: requires = ["setuptools", "wheel"] There are some deprecations in the raw logs pointing to it (neteria, etc).

I got help over at https://github.com/pypa/setuptools/discussions/3748 and they pointed out that the version should be statically defined or set via setup.py so I went for static definition in pyproject.toml but there are three packages we rely on that have deprecation warnings. (cbor, neteria, and another)

**Comment by NeonFlames** [comment]
I noticed that one of the deprecation warnings comes from a dependencies dependency but I have no idea which one, however for now it's probably fine.

**Comment by JaskRendix** [comment]
Exactly, you're right: pyperclip, neteria and cbor.

DEPRECATION: pyperclip is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

**Comment by NeonFlames** [comment]
I'll add wheel to the build depends and that should probably silence the deprecation warning.

(also I have to redo the changes since I just accidentally nuked my branch)

**Pull request closed without merging**
