### PR TITLE
fix weird menu behavior

### LINKED ISSUE #1953: Inconsistent menu behavior
**Describe the bug**
Different menu items  have different behaviour. Tuxemon list returns back to menu, but other items returns to the game

**To Reproduce**
1. Press Esc
2. Select menu item, press enter
3. Press Esc again

**Expected behavior**
All menu items returns at the same place

**Screenshots**
tuxemon_menu

### PR DESCRIPTION
**Pull request by JaskRendix**
fix

### CODE REVIEW

**Comment by pincher2012** [comment]
Now I can't exit Tuxopedia, player, phone, options, or close the menu itself using the Escape key

**Comment by JaskRendix** [comment]
@pincher2012 exactly, that's what you wanted, right?
Escape key was set to open the menu, but at the same time having the same function as the shift button (return too).
Alternatively we can find another key combination to open the menu (eg shift below enter)

but again, I have no idea, I never used escape as return.

**Comment by pincher2012** [comment]
@JaskRendix It's not exactly what I wanted. I didn't know about the shift button. It was convenient for me to use the esc button. The problem I was talking about is that different menu items return the player to different places. I'm expecting a breadcrumb effect. For example, when I enter Tuxepedia through the menu, I expect to return back to the menu. Currently, only the Tuxemon menu item has this effect. That's what I meant. I'm sorry for not describing the problem clearly enough.

**Comment by JaskRendix** [comment]
@kerizane thanks

**Comment by JaskRendix** [comment]
@pincher2012 I'll find a solution, I hope

**Pull request closed without merging**
