### PR TITLE
Fast map drawing

### PR DESCRIPTION
**Pull request by ChillyCider**
Benchmarks were taken at 320x240 resolution, on map1.tmx, using the cProfile module for Python. On my Lemote Yeeloong (CPU: Loongson 2f), the speed increase after these commits is ~40ms each frame. See commit messages for specifics.

I'm interested to hear if it increases framerate on other devices, too. :-)

### CODE REVIEW

**Comment by ShadowApex** [comment]
These changes look great! Thanks for the PR.

I'll try and test this on the GCW-Zero too and see how it's improved the framerate. What FPS were you getting on your Longsoon architecture before and after the change on map1.tmx?

**Comment by xirsoi** [comment]
40ms per frame is an incredible boost, great work @ChillyCider !

**Comment by ChillyCider** [comment]
map1.tmx was really choppy before. When I moved my character, I would see just three frames of movement and then the movement was finished. I think it was like 8 to 12 fps, but I don't have an actual measurement.

I am now getting like 15 to 25 fps. :smile:

**Comment by bitcraft** [comment]
* This PR breaks python3 compatibility with the use of xrange.  If @ShadowApex agrees, we could consider using the six module in Tuxemon (already required by pytmx) and this PR could be changed to use the range function provided by the six module.  Alternatives would be simply using range or futurize (outside the scope of this PR).

* For iterating multidimensional arrays, I like to use itertools.product...it reduces the indentation level and in some cases, is a bit faster than nested for loops.  You could consider using that in your PR (not needed, but since you use the itertools package, I thought it would fit in here!).  Here's an example: https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L866-L867


This should be opened up against the development branch as well.  Overall, thanks for the great PR.  I like the liberal use of iterators.

**Comment by ShadowApex** [comment]
> If @ShadowApex agrees, we could consider using the six module in Tuxemon (already required by pytmx) and this PR could be changed to use the range function provided by the six module.

I think using the `six` module would be good. As you mentioned, `six` is already required by PyTMX.

**Comment by ChillyCider** [comment]
Thanks for the feedback guys! I have updated my development branch and put my changes there. I'll submit a new pull request using that as the source.

**Pull request closed without merging**
