### PR TITLE
yaml event loader (1st pack)

### PR DESCRIPTION
**Pull request by JaskRendix**
Following @kerizane "Add ids for yaml events" pull request, I'm ready to pull a request for a series of yaml files. Any questions, feel free to ask.

### CODE REVIEW

**Comment by kerizane** [comment]
https://github.com/Tuxemon/Tuxemon/pull/1226 must be merged first.

**Comment by kerizane** [comment]
Did you use the script to convert these? How did that tab error happen?

**Comment by JaskRendix** [comment]
Yes, I used a script to convert these. No, it wasn't your script.
How did that tab error happen? I guess because it was among the first ones.

**Comment by ultidonki** [comment]
Thank you, @JaskRendix for this pull request - however, I don't think we should merge this without a discussion first. Have you discussed this on the Tuxemon Discord yet? 

Most of our modders still use the .tmx files, and they only know how to use Tiled - which is why we haven't converted the .tmx files to .yaml yet.

We have a couple of programmers who would prefer the .yaml files, but the people who use the .tmx files still don't want to change, I think, so if you ask on the Discord I think everyone can decide if they want to change to .yaml first. (But I have a feeling most people don't want to change yet, sorry)

If you ask on the Discord, I think more people will reply there than this pull request or on github issues. 

> Yes, I used a script to convert these. No, it wasn't your script.

Does your script have any improvements compared to our script? If so, it might be easier to raise the changes to our converter script, rather than all the .yaml files. Then, when we all decide to switch to .yaml, we can run your script to convert them. 

I *think* our script converter is this one, but I'm not sure: https://github.com/Tuxemon/Tuxemon/blob/development/scripts/yamlify_map_script.py

**Comment by JaskRendix** [comment]
Hi @ultidonki 

> Have you discussed this on the Tuxemon Discord yet?

No, I don't use Discord.

> which is why we haven't converted the .tmx files to .yaml yet.

I understand your point.

> (But I have a feeling most people don't want to change yet, sorry)

No problem.

> Does your script have any improvements compared to our script?

No, I don't think so.

**Comment by ultidonki** [comment]
I'm sorry your first pull request wasn't accepted! But there's plenty more you can do if you still want to help! 

If you use Matrix, there's a Matrix-to-Discord bridge for chatting if you need help. Most of the information from the chat is on the Issues here, it's just useful to chat before making a pull request sometimes. 

If you look at the Github issues, and raise a pull request to fix one of them, it's a lot more likely to get accepted straight away! And if you want to work on something new, raise an Issue so everyone can discuss it first. 

If you don't use Matrix, then you can ask questions on Github issues, but it might take longer (a few days) for people to respond. :smile:

**Pull request closed without merging**
