### PR TITLE
Strip repeated info from jsons

### PR DESCRIPTION
**Pull request by kerizane**
#347

Can still override them if necessary.

### CODE REVIEW

**Comment by kerizane** [comment]
Do we actually need the prefixes in the slugs (txmn_, item_, technique_)? I find them a bit annoying.

**Comment by AndyMender** [comment]
@kerizane we don't and the new translation system I am working on will not have them. An example monster JSON with the new translation system:
```json
{
  "slug": "bigfin",
  "category": "island",
  "description": "bigfin_description",

  "attack_base":            60,
  "defense_base":           7,
  "hp_base":                50,
  "special_attack_base":    6,
  "special_defense_base":   10,
  "speed_base":             7,

  "attack_mod":             1,
  "defense_mod":            1,
  "hp_mod":                 1,
  "special_attack_mod":     1,
  "special_defense_mod":    1,
  "speed_mod":              1,

  "exp_give_mod":           3,
  "exp_req_mod":            27,

  "ai": "RandomAI",
  "moveset": [
    {
      "level_learned": 2,
      "technique": "technique_bite"
    },
    {
      "level_learned": 2,
      "technique": "technique_water_shot"
    }
  ],
  "sprites": {
    "battle1": "gfx/sprites/battle/bigfin-front.png",
    "battle2": "gfx/sprites/battle/bigfin-back.png",
    "menu1": "gfx/sprites/battle/bigfin-menu01.png",
    "menu2": "gfx/sprites/battle/bigfin-menu02.png"
  },
  "types": [
    "water",
    "wood"
  ],
  "weight": 50
}
```
The monster `category` field is common across multiple Tuxemon, hence it doesn't need to be verbose in the monster JSON. Same goes for the `description`. Currently, item JSON files look as follow:
```json
{
  "slug": "apple",
  "description": "apple_description",
  "use_item": "combat_used_x",
  "use_success": "generic_success",
  "use_failure": "generic_failure",
  "effects": [
    "heal"
  ],
  "power": 20,
  "sort": "food",
  "sprite": "gfx/items/apple.png",
  "target": {
    "enemy monster": 1,
    "enemy team": 0,
    "enemy trainer": 0,
    "own monster": 2,
    "own team": 0,
    "own trainer": 0,
    "item": 0
  },
  "type": "Consumable",
  "usable_in": [
    "MainCombatMenuState",
    "WorldState"
  ]
}
```
The `slug` is also a base for the name translation, hence no need for a `name` field anymore. Apologies if my work for #462 overlaps with this issue, but I had to simplify some `slug`s to avoid extra work in the new translation system.

**Comment by kerizane** [comment]
Cool, well I don't want to interfere with your work. I'll drop the trans, description part.

The sprites stuff can stay, right?

There might still be value in me smoothing the way for your change. 

How about if I change the slugs to have no prefix, and deal with any knock-on from that? I want to put in a formal save-system backwards compatibility method. ATM changing the slugs will cause some data loss.

**Comment by kerizane** [comment]
Cool, well I don't want to interfere with your work, I'll drop the trans, description bit, but keep the sprites.

I think there may be value in me smoothing the way for your change. How about I change the slugs to have no prefix, and deal with the knock-on for that? The save system will need a small change to avoid data loss, and I'd like to put a proper system for handling backwards incompatible updates.

I'm also pretty good at vim, if there's any mass JSON changes you're despairing at, let me know.

**Comment by kerizane** [comment]
Cool, well I don't want to interfere with your work. 

If you don't mind, I'll remove the prefixes from the slugs, and deal with any knock-on impact of that. 
This will cause data-loss upon loading the save files, so I'd like to implement a backwards compatibility feature.

I'll leave the sprites change in, but won't bother with the name, category, descr changes.

**Comment by kerizane** [comment]
Cool, well I don't want to interfere with your work. 

If you don't mind, I'll remove the prefixes from the slugs, and deal with any knock-on impact of that. 
This will cause data-loss upon loading the save files, so I'd like to implement a backwards compatibility feature.

I'll leave the sprites change in, but won't bother with the name, category, descr changes.

**Comment by AndyMender** [comment]
The biggest difficulty is refactoring JSON fields and values into the PO `msgid` and `msgstr` system. For now I'm working with the en_US locale. I'll let you know if I run into any issues, though :).

**Comment by bitcraft** [comment]
@kerizane @AndyMender Thank you for working out the JSON conflicts.  Just a heads up, there could be some blocking bugs after these are merged in, and I also have a beg PR in the works for input handling.  In light of these three big PRs, Id like to ask that development be slowed down or freeze for a week after they are merged in, so that I/we can go through the code base and just clean everything up.

Any scripts that you produce for the migration, please add to the "scripts' folder in case they become required to clean up the JSON after merging.  @AndyMender you may also consider updating your wiki sync script to do the following:

* Compare what is in the local DB to the wiki
* Log/print information found in the local DB, but not wiki

With the above feature, you can give @Sanglorian a list of missing info (if any), to update the wiki.  Then we can clear the monster db, and create a new fresh one from the script using the new format with changes from @kerizane's combat PR.  That would potentially save a lot of manual effort transcribing the old JSON format to the new one, after these big PRs.  This is optional for you, but it might save you a lot of effort.

**Comment by bitcraft** [comment]
@kerizane 
> Do we actually need the prefixes in the slugs (txmn_, item_, technique_)? I find them a bit annoying.

Lets move the discussion here: #482

The prefixes are to prevent collisions when searching for slugs.  Suppose we have a txmn named "Potion", and also a item named "Potion".  Stupid example, I realize, but there could be some situation like that eventually.  It makes it less ambiguous when making reference to other things from the JSON.

I agree though, it worked well for a while, but it is tedious and should be updated.

**Pull request closed without merging**
