### PR TITLE
WIP - Spyder Map Split

### PR DESCRIPTION
**Pull request by Sanglorian**
Hi,

Not very experienced at Github, but this is my attempt to add the new Spyder map structure to the main branch. Clearly separates the Spyder overworld maps from others, and starts to change the Spyder maps. More changes to come over the following days/weeks.

### CODE REVIEW

**Comment by kerizane** [comment]
Out of the loop, what's the purpose of this?

**Comment by Sanglorian** [comment]
It's further developing maps for the Spyder in the Cathedral campaign, and distinguishing them from the maps that'll be used for other campaigns.

**Comment by kerizane** [comment]
What does  a .world file do?

**Comment by Sanglorian** [comment]
It's used for managing multiple maps in Tiled, the map editor. It stitches
together multiple maps into one map based on the coordinates given.

It serves no purpose for the game itself ... though since it's just a json
file, it could be used by the game to show the neighboring tiles in other
maps or generate world maps in game.

**Comment by Qiangong2** [comment]
Why are some maps being deleted?

**Comment by Sanglorian** [comment]
There haven't really been any maps deleted - just renamed and continued to be worked on. But if people have a use for the original maps, we can leave a copy of them in.

**Comment by Qiangong2** [comment]
Oh, okay. Just wanted to make sure the current map wasn't affected

**Comment by Sanglorian** [comment]
None of the maps that you've made changes to should be affected - but others have changed quite a lot. If you've got plans for some of the other maps, let me know and I'll preserve them in their original forms.

**Comment by bitcraft** [comment]
@Qiangong2 you are the most familiar with maps.  Could i get your blessing on this one?

@Sanglorian don't get git scare you!  i can help if you run into issues.  also, don't worry about adding a lot of commits.  i will "squash" them into a single giant change before merging.

**Comment by Sanglorian** [comment]
Thanks! I've changed the title to WIP as I had some time last night to make a bunch more changes that I might as well incorporate at the same time. I'll get that done tonight or tomorrow night and add new commits.

**Comment by Qiangong2** [comment]
As long as it isn't changing too much on the maps I've already worked on, and it still connects to the other maps, I'm fine with it

**Comment by bitcraft** [comment]
@Sanglorian for maps, i prefer small quick updates so you gues don't have crazy merge conflicts.  Can you try playing the game and verify that we can make it to cotton town?  that is the benchmark that i am using.  if that works, then it is good enough for me.

**Comment by Sanglorian** [comment]
Hi folks, I've decided I rushed in to this and will take a different approach. New pull request will be coming later - one that leaves all original maps the way they are. 

To be clear, these are intended as changes for the second plot, so they shouldn't affect the current story at all.

**Pull request closed without merging**
