### PR TITLE
remove evolve_monsters

### PR DESCRIPTION
**Pull request by JaskRendix**
Since we merged #1337 we can remove the old evolve_monsters (action and condition) as well as get_evolution (monster.py).

### CODE REVIEW

**Comment by kerizane** [comment]
Could you raise a separate PR with the following:

Modify add_monster so that it takes an index (default behaviour should still be append to end)
Change your code from recent PR so that you are using remove_monster + add_monster rather than assigning directly to the list.
Use add_monster when building the party when loading a file.

**Comment by JaskRendix** [comment]
>  Change your code from recent PR so that you are using remove_monster + add_monster rather than assigning directly to the list.

Do you realize it was with remove and add in the beginning? I'll do.

**Comment by kerizane** [comment]
I think you were using list.append and list.remove, but if you're right then I'm sorry.

**Review by xirsoi — APPROVED** [review]
LG;TftPR

**Pull request merged**
