### PR TITLE
Remove explicit garbage collection

### PR DESCRIPTION
**Pull request by kerizane**
Explicit garbage collection harms the frame-rate.

On the world map fps is 47, within a battle it drops to 30. Text drawing is slow too.

Profiling showed that garbage collection took up 50% of the run-time. 

Removing explicit gc brings the fps back up to 60 at all times.

### CODE REVIEW

**Comment by bitcraft** [comment]
i'm fine with this for now.  eventually, i would like to enable it again because it exposes problems in the code base.  it should not be taking 50% of run time, so it makes me think there are issues can can be solved with wekref to reduce cyclical references that cause slow gc collection.

**Comment by bitcraft** [comment]
I've made a comment about the fps counter.  it should be tracking the number of draws per second, not game ticks, right now anyway.  the whole refactor to decouple game ticks and drawing is not quite complete.

**Comment by kerizane** [comment]
I can't see another comment about the fps. Bit confused, currently each game tick contains a draw doesn't it?

**Comment by bitcraft** [comment]
I changed the event loop recently to only draw whenever it is needed.  When not drawing, it is either waiting a short amount of time, or updating the game engine.  its not optimized right now, and will need some tweaking in the future.  The FSP comment is visible if you look at "Files Changed"

**Comment by kerizane** [comment]
I'm tracking the draws, not the clock ticks. It does get written every clock tick though.

**Comment by bitcraft** [comment]
Ok, I see that now.  The implementation isn't very clear about what is happening.

**Comment by bitcraft** [comment]
Ok, I see that now.  The implementation isn't very clear about what is happening.

**Pull request merged**
