### PR TITLE
Development

### PR DESCRIPTION
**Pull request by bitcraft**
I'm opening this issue to describe the changes I've made to the state system in an attempt to make Tuxemon a little more lean in memory use.

In general, I've played the game, and it seems like everything works as expected, but since I'm pretty new with the project, there probably are some regressions.  Anyway, I've updated all the doc strings and made the following changes:

- States are now instanced on demand, so memory use should be lowered overall
- New state manager removes need to keep references to old states
- New State methods give more control how states interact with game
- States are now loaded at runtime, and require no modification to code to enable them
- A few more are described below

Here are a few use cases with their old way and the new way (tbh, the old way was complicated, and the 'old' examples may not be 100% correct):

## pause current state, let next state get focus
```python
# old
self.next = next_state_name
self.done = True

# new
self.game.push_state(next_state_name)
```

## end current state, let next state get focus
```python
# old (old state stays in memory)
self.next = next_state_name
self.done = True

# new (old state is cleared from memory)
self.game.pop_state()
self.game.push_state(next_state_name)
```

## end current state, let previous state take focus
```python
# old way (old state will stay in memory)
self.next = self.previous.name
self.done = True

# new (old state is cleared from memory)
self.pop_state()
```

I've added tests for the state manager.  They can be added to travis and serve as a template for others to make their own tests.

## Other changes

- Moved State and Control to own respective files
- Minor formatting edits (mostly linting by my IDE)
- Moved existing states for their own folder.  code is found in __init__.py
- cleaned up main.py
- Removed use of State.persist, as nobody was using it, and is super awkward to use anyway
- Moved existing state's State.__init__ to State.startup, as it follows the new API
- Minor changes to the method signatures of State (simplifications, mostly)

### CODE REVIEW

**Comment by ShadowApex** [comment]
Overall, these changes look great. I did encounter some problems that I'd like to fix before I accept this pull request. I'll try fixing them in my personal branch and open a PR to your fork, unless you want to take a shot at them. Here's what I've found:

* The random encounter combat event breaks. Shouldn't be very hard to fix:

```python
Traceback (most recent call last):
  File "/tmp/Tuxemon/tuxemon/core/components/event/__init__.py", line 154, in execute_action
    self.actions[action[0]]["method"](game, action)
  File "/tmp/Tuxemon/tuxemon/core/components/event/actions/combat.py", line 270, in random_encounter
    game.state_dict["COMBAT"].players.append(player1)
KeyError: 'COMBAT'
```

* When trying to use the pc in the starting room (which switches to the "PC" state) to start multiplayer, the game quits. It appears to be hitting the `sys.exit()` in `tuxemon.py`, which makes it appear to be caused by the `main()` function returning prematurely because `self.exit` being set to `True` in the control object for some reason. I suspect this is related to popping states in this way.

I still haven't tested some all the functionality, but these are the two biggest blockers right now.

**Comment by bitcraft** [comment]
I made a lot of progress, but with the two use cases that you brought up (thanks!), I found more cases that needed to be refactored to fit the new model.  The multiplayer 'state' in particular will require lots of love to work with the 'instance, kill, forget' style states.  I'll be traveling for a couple weeks now, so I may not be very productive until I return.  If you want to fix some yourself and do PR, that would be great...I'll be happy to work that way and check in when i have wifi.

**Comment by ShadowApex** [comment]
> I made a lot of progress, but with the two use cases that you brought up (thanks!), I found more cases that needed to be refactored to fit the new model. The multiplayer 'state' in particular will require lots of love to work with the 'instance, kill, forget' style states. I'll be traveling for a couple weeks now, so I may not be very productive until I return. If you want to fix some yourself and do PR, that would be great...I'll be happy to work that way and check in when i have wifi.

Sounds good to me! I'll try and make some headway on the refactoring this week and open a PR to your fork, then we can accept this request once everything is copacetic. Would you be able to push the changes you've made so I could work from there?

**Comment by bitcraft** [comment]
I can do that. From memory, multiplayer, state transitions, and exiting
battles are still broken on my fork, FYI. Mostly, anything that accesses
"game.state_dict" directly will need to be refactored. In some cases it
might need new API, or refactor to a different way that doesn't assume all
states are active all the time.

**Comment by bitcraft** [comment]
The changes from your PR look great.  Looks good!  Transitioning between states looks much better.  What is blocking the PR now?  Multiplayer?

**Comment by ShadowApex** [comment]
> The changes from your PR look great. Looks good! Transitioning between states looks much better. What is blocking the PR now? Multiplayer?

Yeah, I haven't had a chance to actually test out the multiplayer changes yet. If everything works then I think we can move on with accepting this PR. :D

**Comment by ShadowApex** [comment]
I finally got around to trying to test multiplayer on two different machines. For some reason auto-discovering servers on the local network isn't working. I'll continue to look into this to see if I can get it working. Looks like the only blocker remaining before we can merge. :)

**Comment by ShadowApex** [comment]
Actually, I am going to go ahead and accept this PR and then work on the multiplayer problem in the development branch. I want to avoid people continuing to add features using the old state system, which would only create more work. Once we've gotten multiplayer working right, I'll release the changes to the master branch and bump up the release version.

Thanks again for this pull request!

**Pull request merged**
