### PR TITLE
template (interactive object)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR adds **interactive_obj** to the **template.json**. it follows an edit inside **npc.py** to avoid looking for front, back, left, right.
That's because an interactive obj doesn't move. It creates the folder **sprites_obj** to separate obj sprites from npc sprites.

files changed 100, but:
- 57 are the sprites of log, boulder and statue (deleted - 19*3);
- 15 are the sprites of objects (eg tuxeball_red, etc);
- 21 are the JSONs edited or created in the db/npc folder;
- the actual code is in 2 files: **npc.py** and **db.py**

There are already some interactive objects inside the game (eg rock, log, boulder, statue, etc.), and the enormous bottleneck about it, it's that we need 20 identical PNGs for an object that doesn't move.

It changes something? For the player nothing, for the modders, less copy paste 20 times for an object that doesn't move.

moreover I added some interactive object (5 different type of tuxeball)
eg this ball will give the player 5 potions (just a test) and the it'll disappear.
Screenshot from 2023-04-22 11-05-02

```
event1
    <property name="act1" value="create_npc tuxeball,11,8"/>
    <property name="cond1" value="not npc_exists tuxeball"/>
    <property name="cond2" value="not variable_set tuxeballcotton1:yes"/>
event2
    <property name="act2" value="translated_dialog xxxxx"/>
    <property name="act3" value="add_item potion,5"/> <---- whatever you want, monster, etc.
    <property name="act4" value="set_variable tuxeballcotton1:yes"/> 
    <property name="act5" value="remove_npc tuxeball"/>
    <property name="cond1" value="is player_facing_tile"/>
    <property name="cond2" value="is button_pressed K_RETURN"/> <--- without this it doesn't disappear immediately, you need to exit and reenter
    <property name="cond3" value="not variable_set tuxeballcotton1:yes"/>
```
Screenshot from 2023-04-22 15-48-21

tested, black, isort, no new typehints

### CODE REVIEW

**Comment by JaskRendix** [comment]
@Sanglorian from where did you get the log and the boulder? found (Vegetation_and_Outdoor_Fittings_by_George)
- drokoro done;
- volcoli done;
- statues cotton town done (so all can be moved after);

I don't know if you have other similar stuff, this is what popped in my mind:
- hospital doors in the other PR, so we can remove the alternative map;
- paintings... but it would look really empty the artshop;
- items around the maps (eg city park), do you want the tuxeball? same color or different colors? or do you want a different sprite for each item because the player must know the item before picking it up? I would invite you to consider max 5 items for map, in this way we can put the 5 tuxeball with different colors, so the player knows there are 5 items, but... you need to give me the items!

from the wiki the places with items: [Greenwash HQ](https://github.com/Tuxemon/Tuxemon/pull/1771), Dragon's Cave, Route 4, Tunnel B, City Park. If you have stuff for Omnichannel and Hospital too, then feel free to post the items in the PRs.

let me know

drokoro done (before, after)
https://user-images.githubusercontent.com/64643719/233781178-aa83a01f-2fa1-4496-98ab-c73a5c7e24a6.png
https://user-images.githubusercontent.com/64643719/233781176-52aa049e-6456-43d2-9a69-b940718b6fee.png

volcoli done (before, after) (it doesn't look anymore so "low")
https://user-images.githubusercontent.com/64643719/233782013-1322e40c-bb21-426d-8df2-3391fefb8b72.png
https://user-images.githubusercontent.com/64643719/233782010-c7be01ee-b3a0-434a-99c3-6e955e0e351c.png

**Comment by Sanglorian** [comment]
This is very exciting, thank yo! 

> I don't know if you have other similar stuff, this is what popped in my mind:
> 
>     * hospital doors in the other PR, so we can remove the alternative map;
> 
>     * paintings... but it would look really empty the artshop;
> 
>     * items around the maps (eg city park), do you want the tuxeball? same color or different colors? or do you want a different sprite for each item because the player must know the item before picking it up? I would invite you to consider max 5 items for map, in this way we can put the 5 tuxeball with different colors, so the player knows there are 5 items, but... you need to give me the items!

1. Hospital doors, yes please! Agree that would make the maps simpler. 

2. I like the idea of the paintings disappearing. Could we make so that the next time the player visits, they have been replaced by the other artworks in Interior Tiles? Shown here above the paintings that they replace:

image
 
Or is that too complicated?

3. For items, I planned to use the cardboard box in the main part of "core_set pieces": there could be a quick two-frame animation of it opening up when the player interacts with it.

But the animation is optional! Either way of course it should disappear from the map afterwards. 

> from the wiki the places with items: [Greenwash HQ](https://github.com/Tuxemon/Tuxemon/pull/1771), Dragon's Cave, Route 4, Tunnel B, City Park. If you have stuff for Omnichannel and Hospital too, then feel free to post the items in the PRs.
> 
> let me know

Thanks, good for now but when I get a chance to play through I'll think if there needs to be more items around the place. 

> drokoro done (before, after) 
> 
> volcoli done (before, after) (it doesn't look anymore so "low")

This is so much better than what we had!

**Comment by JaskRendix** [comment]
@Sanglorian 
I'm going to open another PR for the Art Shop in Cotton Town. I have already one in the pipeline.
About the package/box, I found it and I added the single box inside the sprite_obj folder, but for adding the packages, then I'm going to open another PR so you can check precisely.

**Review by kerizane — APPROVED** [review]

**Review by kerizane — APPROVED** [review]

**Comment by kerizane** [comment]
Great idea!

**Pull request merged**
