### PR TITLE
tech tags

### PR DESCRIPTION
**Pull request by JaskRendix**
PR for @Sanglorian as requested  [here](https://github.com/Tuxemon/Tuxemon/discussions/2268#discussioncomment-10644249) First, it refines some translations and tweaks the accuracy and potency parameters of techniques to make them more balanced. But that's not all - it also introduces two new fields that will be game-changers for monster movesets. The first field is for categorizing techniques, think 'animal', 'exotic', and so on. The second field is for tagging techniques with specific keywords like 'bird', 'megafauna', or whatever fits the bill. These new fields will be super helpful in automating the assignment of techniques to monsters, ensuring that we don't end up with a water monster wielding fire techniques or a monster with an overpowered moveset. Finally, this PR transforms the 'cavity' technique into a reserved technique and replaces it with a new one in the monsters that previously had it in their moveset.

---

@Sanglorian the data you asked for, remember that these results are without the 20 technique above. If you have specific questions, feel free to ask.

What do we need?
- we need a range for min and max number of techniques (moveset), at the moment min 4 and max 15 (see below)
- we need a range of % for moves - for instance **simple** techniques must be between 40-60%, etc. depending on xxx (see monster examples at the bottom)

```
Average number of moves per monster: 10.104026845637584
Minimum number of moves: 4
Maximum number of moves: 15
```
Here: https://wiki.tuxemon.org/Technique_Distribution

Data per specific monster, some examples:
```
hydrone -> standalone
Simple 40.0 %
Basic 20.0 %
Powerful 30.0 %
Animal 10.0 %

eyenemy shares the name techniques with eyesore
Exotic 25.0 %
Simple 50.0 %
Animal 12.5 %
Condition Imposer 12.5 %
```

### CODE REVIEW

**Comment by JaskRendix** [comment]
@Sanglorian the data you asked for, remember that these results are without the 21 technique above

```
Exotic techniques:
Average level: 16.91
Level distribution:
Level 2: 54
Level 6: 42
Level 8: 33
Level 12: 20
Level 16: 24
Level 20: 21
Level 24: 30
Level 28: 32
Level 32: 18
Level 34: 1
Level 36: 15
Level 40: 15
Level 44: 1
Level 48: 2
Level 52: 1

Simple techniques:
Average level: 17.77
Level distribution:
Level 2: 245
Level 4: 7
Level 6: 138
Level 8: 158
Level 10: 6
Level 12: 123
Level 16: 76
Level 20: 76
Level 24: 103
Level 28: 116
Level 32: 73
Level 34: 16
Level 36: 44
Level 38: 3
Level 40: 60
Level 44: 27
Level 48: 22
Level 52: 11
Level 56: 6
Level 60: 6
Level 64: 3
Level 68: 3

Basic techniques:
Average level: 16.58
Level distribution:
Level 2: 89
Level 6: 14
Level 8: 21
Level 12: 31
Level 16: 15
Level 20: 8
Level 24: 20
Level 28: 21
Level 32: 41
Level 34: 3
Level 36: 10
Level 40: 13
Level 44: 3
Level 48: 3

Powerful techniques:
Average level: 19.65
Level distribution:
Level 2: 75
Level 4: 3
Level 6: 32
Level 8: 20
Level 12: 28
Level 16: 17
Level 20: 16
Level 24: 29
Level 28: 17
Level 32: 32
Level 36: 17
Level 40: 18
Level 44: 10
Level 48: 12
Level 52: 13

Condition imposer techniques:
Average level: 17.14
Level distribution:
Level 2: 61
Level 4: 3
Level 6: 30
Level 8: 24
Level 12: 66
Level 16: 17
Level 20: 24
Level 24: 26
Level 28: 26
Level 32: 21
Level 36: 25
Level 40: 21
Level 44: 3

Comparison of average levels:
Exotic: 16.91, Simple: 17.77, Basic: 16.58, Powerful: 19.65, Condition imposer: 17.14
Powerful techniques are learned at a higher average level than exotic techniques.
Basic techniques are learned at a lower average level than simple techniques.
Total exotic techniques: 309
Total simple techniques: 1322
Total basic techniques: 292
Total powerful techniques: 339
Total condition imposer techniques: 347
Exotic techniques percentage: 11.84%
Simple techniques percentage: 50.67%
Basic techniques percentage: 11.19%
Powerful techniques percentage: 12.99%
Condition imposer techniques percentage: 13.30%
```

**Comment by JaskRendix** [comment]
@Sanglorian if you can tell me which type are the missing technique, then it would be great

**Comment by Sanglorian** [comment]
> PR for @Sanglorian as requested here [#2268 (reply in thread)](https://github.com/Tuxemon/Tuxemon/discussions/2268#discussioncomment-10644249)
> 
> Pending reserved technique expansion: https://wiki.tuxemon.org/Reserved_technique
> 
> I've added a new field called "tags" to help categorize some techniques, and I've already populated it with some examples like "exotic", "simple", "animal", etc. However, I've noticed that some techniques aren't showing up on https://wiki.tuxemon.org/Technique_design_space.
> 
> ```
> acid
> cavity
> fledgling
> greenstone
> lineage
> lust
> meltdown
> nest
> peck
> pit
> platinum
> shapechange
> stabilo
> stonehenge
> suck_poison
> time_crisis
> tip
> undertaker
> wall_fire
> walls
> ```

Thanks for this! I've gone through the first few techniques and made some changes to fit them into the technique design space - trying to find a niche for each technique.

Does this look good to you? I'm happy to change back anything you don't like, of course!

If it does look good, I'll keep going this afternoon with the others.

**Comment by JaskRendix** [comment]
It looks good and I'm okay with making Cavity a reserved technique. Let's find some suitable replacements for [Grumpi](https://wiki.tuxemon.org/Grumpi), [Dinoflop](https://wiki.tuxemon.org/Dinoflop), [Foofle ](https://wiki.tuxemon.org/Foofle) and [Enduros](https://wiki.tuxemon.org/Enduros).

**Comment by JaskRendix** [comment]
@Sanglorian all your changes have been integrated.

It looks good and I'm okay with making Cavity a reserved technique. Let's find some suitable replacements for [Grumpi](https://wiki.tuxemon.org/Grumpi), [Dinoflop](https://wiki.tuxemon.org/Dinoflop), [Foofle ](https://wiki.tuxemon.org/Foofle) and [Enduros](https://wiki.tuxemon.org/Enduros).

**Comment by Sanglorian** [comment]
> @Sanglorian all your changes have been integrated. Are you sure about wall of fire for [Medushock](https://wiki.tuxemon.org/Medushock)?
> 
> It looks good and I'm okay with making Cavity a reserved technique. Let's find some suitable replacements for [Grumpi](https://wiki.tuxemon.org/Grumpi), [Dinoflop](https://wiki.tuxemon.org/Dinoflop), [Foofle ](https://wiki.tuxemon.org/Foofle) and [Enduros](https://wiki.tuxemon.org/Enduros).

Thank you - have replaced Cavity for those four mons, and took the opportunity to change up a few other parts of their movesets. 

Good point re Medushock. I have introduced more of an electricity-theme for it.

**Comment by JaskRendix** [comment]
@Sanglorian I noticed and all the changes have been integrated. Regarding the [tags](https://wiki.tuxemon.org/Tags) I would say that we can integrate it in the Technique form like checkboxes (it'll take 4, eventually 5 lines, but we can put it at the bottom), what do you think?

**Comment by Sanglorian** [comment]
> @Sanglorian I noticed and all the changes have been integrated. Regarding the [tags](https://wiki.tuxemon.org/Tags) I would say that we can integrate it in the Technique form like checkboxes (it'll take 4, eventually 5 lines, but we can put it at the bottom), what do you think?

Thank you!

I wonder if we can do a prompt. Like with Sources now, where if you start typing it shows you which creators you can choose from. That would spare us some space. It would mean creating a page for every tag, but I think that's worthwhile.

**Comment by JaskRendix** [comment]
> I wonder if we can do a prompt. Like with Sources now, where if you start typing it shows you which creators you can choose from. That would spare us some space. It would mean creating a page for every tag, but I think that's worthwhile.

@Sanglorian I'm with you on the Source method. I've already duplicated the property and added it to the Technique template, as well as the Form and Category. That way, we can easily roll it out to the Monster later on. Tags was still showing Sword, but you have renamed it Slice. Ice Spear doesn't exist. Now you can see everything from here: https://wiki.tuxemon.org/Category:Technique (some techniques are still missing tags)

**Comment by Sanglorian** [comment]
> > I wonder if we can do a prompt. Like with Sources now, where if you start typing it shows you which creators you can choose from. That would spare us some space. It would mean creating a page for every tag, but I think that's worthwhile.
> 
> @Sanglorian I'm with you on the Source method. I've already duplicated the property and added it to the Technique template, as well as the Form and Category. That way, we can easily roll it out to the Monster later on. Tags was still showing Sword, but you have renamed it Slice. Ice Spear doesn't exist. Now you can see everything from here: https://wiki.tuxemon.org/Category:Technique (some techniques are still missing tags)

Thank you, that is looking so good! Have filled in some more tags.

**Comment by JaskRendix** [comment]
@Sanglorian I think we can go ahead and merge this. We can tackle the 'steel' tag and those other minor issues in the next PR, either #2438 or #2452.

**Comment by Sanglorian** [comment]
> @Sanglorian I think we can go ahead and merge this. We can tackle the 'steel' tag and those other minor issues in the next PR, either #2438 or #2452.

I agree, and thank you for all this work.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
