### PR TITLE
Change bg and intro spyder

### PR DESCRIPTION
**Pull request by JaskRendix**
PR addresses discussions happened here #1381 and #1377

Originally the intention was to remove the hardcode, but it was missing an alternative.

Alternative that finally I developed. It's a new action called change_bg and it allows modders to change background. To test it, I recreated the intro spyder that @Sanglorian wanted to implement (which originated this video: https://youtu.be/GyQjCrsVJX4)

I guess it can be useful for @Qiangong2 too, like the announcement in television, as well as finding the right spot where they can ask the name in game.

I removed the hardcoding, so when a player click newgame > spyder, it appears this:
by the way, don't give much importance to the dialogues, I was filling the void.
if you want to watch the intro:
Screenshot from 2023-01-15 14-10-39
question no/yes
Screenshot from 2023-01-15 13-41-10
if the player says yes, no intro, he'll appear inside spyder_bedroom exactly like now.
if the player says no, it continues (exactly like in the video)
Screenshot from 2023-01-14 23-11-19
ended the intro, the player will be teleported inside the old spyder_paper_mart, it's a duplicate of spyder_paper_scoop, identical, but unused and not accessible in any way. Perfect location for setting up an event like this, the player will never know.
By the way, not worry about the face "down" of the player, it has been fixed, now it looks right.
Screenshot from 2023-01-15 13-42-06
assistant distribute the papers to fill in
Screenshot from 2023-01-15 13-42-27
first question of the papers
Screenshot from 2023-01-15 13-44-09
it appears the input
Screenshot from 2023-01-15 13-44-24
second questions (originally @Sanglorian planned for three question, but at the moment we can ask only 2)
Screenshot from 2023-01-15 13-44-50
choice among the monsters
Screenshot from 2023-01-15 13-37-36
trainers need to give back the papers (the position of the face has been fixed), it's animated by pathfinding, exactly like the distribution, but here it's not the shop assistant to move, but each trainer, last one our hero.
Screenshot from 2023-01-15 13-37-53
last one
Screenshot from 2023-01-15 13-38-24
here the player gets teleported inside the bedroom, exactly like if it didn't choose the intro.

tested + isort + black

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks! Sounds great.

**Comment by JaskRendix** [comment]
@Qiangong2 what do you want to do with Xero, if I'm going to remove the hardcoded set_name, the name of the player will be Red (as per json file).

Is it ok? Did you plan a different name? If yes, which name? If no, where do you want to insert the rename_player (action)?

Something like "Is is true that you're RED?", then the player has a yes/no choice, if no rename, if yes it keeps going on as Red.

Let me know!

**Comment by Qiangong2** [comment]
The Xero campaign was always designed around the very first thing a player sees would be the name prompt, so I don't know actually.

Maybe a simple prompt asking if your name is red, and if not to enter it? I don't plan on having a big "Tuxemon are our friends" intro sequence like with the mainline pokemon games as my campaign doesn't really follow that.

If you want, I can probably mock up a "Welcome to Fondent" intro. It would emphasize Omnichannel and how great they are, etc.

**Comment by JaskRendix** [comment]
No problem, I'm going to put the rename_player at the beginning.
Sure, it would be welcome a mockup, it would be like your signature (Size: 240x160)
If not I was thinking about using the empty one (the one behind "do you want to skip the intro"), so I can make appear "Is it your name RED?", then choice, (then eventually rename_player), then everything starts inside the bedroom.

**Comment by Qiangong2** [comment]
I guess a full intro would be:

1) dialog "Welcome to the Fondent Region!"
2) map of the fondent region appears
3) dialog "The Fondent Region is a wonderful place filled with all sorts of wonderful people! You're sure to love it here!"
4) dialog "The Fondent Region is run by the benevolent Omnichannel Corporation. They make sure everyone's needs are met and that everyone is protected from the fearsome Tuxemon!"
5) map fades and picture of Aeble shows up
6) dialog "The great and benevolent Omnichannel Corporation has been led by one man since its inception 25 years ago: Aeble Flisk! Along with the Omni-Council and the Omnigrunts, he has brought stability and prosperity to the Fondent Region!
7) picture of Aeble fades
8) dialog "Thank you for visiting the Fondent Region! We hope you enjoy your stay, whether it's for a few days, or for a lifetime!"
9) dialog "What's your name?"
10) select/type name

I know it's a little long, but I hope this is enough for you :)

**Comment by JaskRendix** [comment]
It sounds ok. I'm unable to create a map of Fondent region, but as soon as we have one, we can replace it later.
About the fade in / fade out, I alert you that it's an image replacement, so it appears / disappears.
Update: Xero, since the intro is longer:
```
Do you want to skip the intro? Yes or No
-> if yes, "What's your name" -> play
-> if no, it shows the intro -> What's your name? -> play
```
While waiting for the map of the region, do you want to show your favorite monster instead of the empty screen? I don't know if it exists an Omnichannel logo, something like this.

**Comment by JaskRendix** [comment]
Fixed issue with Player menu.
No idea why style 3.9 fails,  for `tox -efmt ` everything is fine

**Comment by Qiangong2** [comment]
Omnichannel should probably have a logo. I don't know if there's one in the Spyder campaign at all, but I'm not very good at art myself.

For the time being, rockitten could be a placeholder image

**Comment by JaskRendix** [comment]
Ok, rockitten

**Comment by JaskRendix** [comment]
Everything is ready, I'm waiting for #1587, so I can insert the gender choice at the beginning.

**Comment by JaskRendix** [comment]
@Sanglorian and @Qiangong2 tagging you for informing that after this PR gets merged, well, the player can finally choose the gender at the beginning. This will literally increase exponentially the possibility to trigger different events based on the gender. With the right inspiration you can create two games into one.

It took a lot of time and many tasks, but we did it. Here the screen, really basic, that will appear:

Screenshot from 2023-03-03 07-57-25

for both of you the choice will be saved in the variable **gender_choice** and the two options are:
**gender_female** or **gender_male** 
with this parameter and the conditions, well, you know better than me how to trigger specific events.

existing players will be automatically set at gender_male

**Review by kerizane — APPROVED** [review]

**Comment by Sanglorian** [comment]
> @Sanglorian and @Qiangong2 tagging you for informing that after this PR gets merged, well, the player can finally choose the gender at the beginning. This will literally increase exponentially the possibility to trigger different events based on the gender. With the right inspiration you can create two games into one.
> 
> It took a lot of time and many tasks, but we did it. Here the screen, really basic, that will appear:
> 
> Screenshot from 2023-03-03 07-57-25
> 
> for both of you the choice will be saved in the variable **gender_choice** and the two options are: **gender_female** or **gender_male** with this parameter and the conditions, well, you know better than me how to trigger specific events.
> 
> existing players will be automatically set at gender_male

That's great, thanks so much for getting that implemented.

**Pull request merged**
