### PR TITLE
16 monsters package + morph item (ox stick)

### LINKED ISSUE #22: Add free software mascot-inspired monsters
For ideas, check out: https://commons.wikimedia.org/wiki/Category:Free_software_mascots

### PR DESCRIPTION
**Pull request by JaskRendix**
PR adds:
- [Tumbledillo](https://wiki.tuxemon.org/Tumbledillo)
- [Mauai](https://wiki.tuxemon.org/Mauai)
- [Nimbulex](https://wiki.tuxemon.org/Nimbulex)
- [Capinyah](https://wiki.tuxemon.org/Capinyah)
- [Howl](https://wiki.tuxemon.org/Howl)
- [Fuzzlet](https://wiki.tuxemon.org/Fuzzlet)
- [Fuzzina](https://wiki.tuxemon.org/Fuzzina) 
- [Flisces](https://wiki.tuxemon.org/Flisces)
- [Mingdyn](https://wiki.tuxemon.org/Mingdyn)
- [Uneye](https://wiki.tuxemon.org/Uneye)
- [Lendos](https://wiki.tuxemon.org/Lendos) 
- [Ziggurat](https://wiki.tuxemon.org/Ziggurat) 
- [Urcheedle](https://wiki.tuxemon.org/Urcheedle)
- [Joulraton](https://wiki.tuxemon.org/Joulraton)
- [Firomenis](https://wiki.tuxemon.org/Firomenis)
- [Uglip](https://wiki.tuxemon.org/Uglip)

PR adds also:
- [ox stick](https://wiki.tuxemon.org/Ox_Stick) item (morphing item for Mauai);

3 Varmint, 2 Humanoid, 1 Flier, 2 Aquatic, 2 Dragon, 6 Blob, 1 Sprite

missing description of existing tuxemon:
- [drashimi_description](https://wiki.tuxemon.org/Drashimi)
- [shelagu_description](https://wiki.tuxemon.org/Shelagu)
- [tobishimi_description](https://wiki.tuxemon.org/Tobishimi)
- [tsushimi_description](https://wiki.tuxemon.org/Tsushimi)

fix #22 
reason: _I think we can still close #22 though as we have other examples of open-source mascots._
source: https://github.com/Tuxemon/Tuxemon/issues/1517#issuecomment-1528772546

### CODE REVIEW

**Comment by Sanglorian** [comment]
> @Sanglorian are you interested in these descriptions?
> 
>     * It was said that the LOLIFERNO's fire could not be extinguished. Yet, despite its power, LOLIFERNO was also said to have a playful side, and was known to dance among the flames it created.
> 
>     * LUNIGHT was said to have the ability to control the moon and its phases, and to be a guardian of the night.
> 
>     * Little was known about DRASHIMI, as it was rarely seen, and those who claimed to have encountered it, said that it was a creature of mystery and power.

Thanks! I like Loliferno's and Lunight's. Drashimi's seems a little vague to me, I think it would be interesting to include more detail. 

For Loliferno and Lunight, the only thing is that you use "was said" a few times. I think it's stronger without them, mostly, and in the present tense: 

* It is said that the LOLIFERNO's fire could not be extinguished. Yet, despite its power, LOLIFERNO has a playful side, and is known to dance among the flames it creates.
* LUNIGHT is the guardian of the night, and can control the moon and its phases.

EDIT: Added entries for Lendos and Ziggurat. (And Merlicun I pulled in from its description.)

**Comment by JaskRendix** [comment]
updated

**Comment by JaskRendix** [comment]
@Sanglorian updated the descriptions, but I realized we don't know how [Mauai](https://wiki.tuxemon.org/Mauai) is going to evolve from  [Memnomnom](https://wiki.tuxemon.org/Memnomnom).
Do you want to create a new item (eg ox stick)? Specific level? Some random condition like place, time, season, etc.?

**Comment by Sanglorian** [comment]
Thanks heaps! 

1. Have added the Ox Stick and Fire Booster as ways for Memnomnom to morph into Mauai.
2. Have added descriptions on the wiki for Mauai, Nimbulex, Capinyah, Howl, Fuzzina, Flisces and Mingdyn.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
