### PR TITLE
Verbal conjugation is WRONG!

### PR DESCRIPTION
**Pull request by AndrejHatzi**
I changed all verbs ending in a 's' like 'fugistes' because that does not exist in portuguese!

### CODE REVIEW

**Comment by bitcraft** [comment]
Thanks for looking into the translation.  Just a heads up, another contributor recently changed our system from json to gettext/PO files.  These json files are no longer being used, so these changes won't show up in the game.  I will can merge this anyway, but for the translation to work in the game, it will need to be updated to the PO format.  Unfortunately, I guess the other contributor didn't migrate this with the rest.

**Comment by AndrejHatzi** [comment]
Where are exactly those files?

**Comment by bitcraft** [comment]
Sure.  Copy the spanish locale folder (https://github.com/Tuxemon/Tuxemon/tree/development/tuxemon/resources/l18n) and then modify it for portuguese.

**Comment by bitcraft** [comment]
@AndrejHatzi I'll merge this so the source json translation is correct when somebody tackles the gettext translation.  Keep in mind changes will not show up in game until gettext files are fixed.  Thanks again for your contribution.

**Pull request merged**
