### PR TITLE
Replace "monster_slug" with "monster" in encounter jsons

### PR DESCRIPTION
**Pull request by kerizane**
As mentioned in #467

Also renamed sumobug to sumchon, onaclov to eruptibus, tumblecoon to tumblebee and split nudiflot into nudiflot_male and nudiflot_female.

### CODE REVIEW

**Comment by airon90** [comment]
> Also renamed sumobug to sumchon, onaclov to eruptibus, tumblecoon to tumblebee and split nudiflot into nudiflot_male and nudiflot_female.

Change them also in other locale. If you can't do, I will maybe have spare time tomorrow evening

**Comment by Sanglorian** [comment]
Thanks so much for that, kerizane! Although it should actually be tumblecoon to katacoon rather than to tumblebee.

**Comment by airon90** [comment]
> Also renamed sumobug to sumchon, onaclov to eruptibus, tumblecoon to tumblebee and split nudiflot into nudiflot_male and nudiflot_female.

Change them also in other locale. If you can't do, I will maybe have spare time this evening

**Comment by kerizane** [comment]
Updated all locales.

**Comment by bitcraft** [comment]
Nice work, thank you for the fixes here.

**Pull request merged**
