### PR TITLE
Add some movement to cafe, trainer

### PR DESCRIPTION
**Pull request by HippasusTwo**
Confused Guy helps lost players figure things out, and get some exp.

(Like this confused player:
https://github.com/Tuxemon/Tuxemon/issues/2291)

Some of the npcs will now occasionally change their direction they are facing. One wanders around inside and is a trainer (so grinding isn't as painful - I always found it weird that you fought your rival and then immediately again with no action in-between.)
Cafe issue;  I didn't touch the cutscene part as I think that's only supposed to trigger when you actually talk to the hacker guy:
https://github.com/Tuxemon/Tuxemon/issues/1946

### CODE REVIEW

**Comment by ultidonki** [comment]
I haven't tested it but this looks fine. If there's any problems they can be tested when doing a full playthrough. So thanks!

**Comment by ultidonki** [comment]
Actually, after thinking about it - I don't like the idea of a trainer ambushing you if you're in the friendly base/cafe. During my playthrough I'm often walking around the village with low HP tuxemon, because I want to explore before going to the Health center (which is a bit boring). 

I think there was a suggestion to have a new map, a 'training area' underneath the cafe, where you could level up or catch tuxemon. If someone created that, it might be better to have a trainer or two in there.

If you still want an NPC to give advice on where to go, I think they should give advice without fighting you first. :grinning:

**Comment by Sanglorian** [comment]
> Actually, after thinking about it - I don't like the idea of a trainer ambushing you if you're in the friendly base/cafe. During my playthrough I'm often walking around the village with low HP tuxemon, because I want to explore before going to the Health center (which is a bit boring).
> 
> I think there was a suggestion to have a new map, a 'training area' underneath the cafe, where you could level up or catch tuxemon. If someone created that, it might be better to have a trainer or two in there.
> 
> If you still want an NPC to give advice on where to go, I think they should give advice without fighting you first. 😀

I agree.

At the very least, maybe the NPC can ask *if* the player wants a battle, and helps them out regardless?

**Comment by HippasusTwo** [comment]
Ah, it is true getting ambushed can be unfun. I'll add choices. If someone at some point wants to put trainers elsewhere, that'd be fine, but for now we really kinda need some before the 2nd rival battle as going straight from rival battle to rival battle feels kinda bad and incredibly grindy.

If you leave the town rightward you immediately get attacked by the rival. Someone who can't beat two level two mons is not going to be able to leave regardless, but with an optional lower-level battle right in front of the blocked cave they have a sense of a path toward progression which is what really matters.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
