### PR TITLE
cathedral ads (Spyder)

### LINKED ISSUE #1782: Ads to play during healing at Cathedral Centres
**Is your feature request related to a problem? Please describe.**

When someone uses a [Cathedral Centre](https://wiki.tuxemon.org/index.php?title=Cathedral_Centre&action=edit&redlink=1) to heal, the service is free but to recoup costs they have to watch an ad. This adds character to the Cathedral as a commercial operation, and also introduces the player to features of the world like the five Pillars. 

**Describe the solution you'd like**

When the player heals at a Cathedral Centre (*not* at other places, like a Cafe), an ad is displayed. The ad is displayed for a number of seconds equal to the number of times the player has been to a Cathedral Centre to heal divided by three (if they have been six times, they have to watch for two seconds) (minimum 1 second).

The ad is chosen at random. from various options. Each ad involves three things: an image, the accompanying text, and the organisation placing the ad. The organisation's logo appears in the top-right of the ad. 

At the bottom of the screen, a bar fills up as the required viewing time elapses. 

**Describe alternatives you've considered**

This is a nice-to-have but by no means essential feature, so if it's too tricky, we don't need to do it. 

I've currently made the ads in a few different sizes, but I can easily give them all the same dimensions. 

Alternatively, we could just give the text, with no image. 

**Additional context**

I have been making some ads using an AI program and have put them [on the wiki](https://wiki.tuxemon.org/Cathedral_ads). The logos of the five Pillars are listed [under "Badge" on the items page](https://wiki.tuxemon.org/Category:Item).

### PR DESCRIPTION
**Pull request by JaskRendix**
fix #1782

PR:
- creates a new action called **translated_dialog_var**, it'll allow to show the msgid contained inside a variable (eg. you have a variables alpha:gamma, where gamma is a msgid inside the PO file "Hello World" -> by using **translated_dialog_var alpha** it'll open the dialog showing **Hello World**)

```
    <property name="act41" value="change_bg cathedral_ads"/>
    <property name="act42" value="translated_dialog_var cathedral_ads_text"/>
    <property name="act43" value="wait 5"/>
    <property name="act44" value="change_bg end"/>
```

@Sanglorian this is the easiest way to implement the ads, as a sequence of actions. It appears the ad, it shows the dialogue with the description, when you click **enter** the dialogue as usual disappear and it starts the 5 seconds countdown. Ended, the ads disappears.

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks for doing this! Sorry the countdown was such a nuisance.

**Comment by JaskRendix** [comment]
@Sanglorian it depends on you, do you want 5 seconds? 3? Let me know

**Comment by Sanglorian** [comment]
Thanks, let's say 3 seconds.

**Comment by JaskRendix** [comment]
Ok, let's see what happens

**Comment by kerizane** [comment]
You read the text, click enter, then have to wait 3 seconds before the image disappears?

This will probably confuse people. 

What if we locked the controls, show the ad with text, wait 3 seconds and then unlock the controls?

**Comment by JaskRendix** [comment]
> What if we locked the controls, show the ad with text, wait 3 seconds and then unlock the controls?

it makes sense, I'm going to update it

**Comment by JaskRendix** [comment]
No, it doesn't work.... It's going to crash, I need to redo everything

**Comment by JaskRendix** [comment]
Ok, now the text will appear after three seconds:

image -> 3 seconds -> dialogue > click > disappear image > as usual

**Comment by JaskRendix** [comment]
Removed 3 seconds, now it'll will appear the ads, then the dialogue, who wants will read, otherwise it'll click.

If someone wants to add time later and stress the player more, then feel free, I'm not going to touch it anymore.

@kerizane this will not confuse the player for sure, it'll oblige him/her to click a couple of times more.

**Comment by JaskRendix** [comment]
Ok, I wasted some time by going back to the original commit, and connecting the new state (called LoadingState) to change_state, this allowed me to delete a pointless action. I removed all the cathedral_ads variables as well as the math operations because completely pointless (I hope I'm going to learn this lesson).

How it works. The ad will appear, then you click return (shift or escape) and then the action continues. There is time to read, no restrictions.

Try like this, then if you feel you need to lock the event for some time, feel free to add it.

At least the new loading state will allow us to have a state with background with dialogue integrate, handy for other things.

**Comment by Sanglorian** [comment]
Thanks @JaskRendix , that sounds like a good approach!

**Comment by JaskRendix** [comment]
I'm still not convinced about this, I'm going to close

**Pull request closed without merging**
