### PR TITLE
#273 item showing count in bag, item sorting, item sort attributes

### PR DESCRIPTION
**Pull request by bitcraft**
Implemented some changes for item sorting, as discussed in #237.

- Modified sort attributes for items.  Linting.
- Minor change in increase spacing for item list in bag, as some descenders ("j", "g") were touching letters in the next row.
- New method to sort an inventory for display (doesn't modify original)

### CODE REVIEW

**Comment by MirceaKitsune** [comment]
👍 to this.

**Comment by ShadowApex** [comment]
Hey bitcraft, thanks for these changes. The item count looks great!

Currently get this crash with your build of the game when trying to use a potion in the middle of battle:
```python
Traceback (most recent call last):
  File "./tuxemon.py", line 60, in <module>
    main()
  File "/tmp/Tuxemon/tuxemon/core/main.py", line 98, in main
    control.main()
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 542, in main
    self.main_loop()
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 603, in main_loop
    self.update(time_delta)
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 206, in update
    state.update(dt)
  File "/tmp/Tuxemon/tuxemon/core/states/combat/combat.py", line 152, in update
    self.transition_phase(new_phase)
  File "/tmp/Tuxemon/tuxemon/core/states/combat/combat.py", line 278, in transition_phase
    self.sort_action_queue()
  File "/tmp/Tuxemon/tuxemon/core/states/combat/combat.py", line 369, in sort_action_queue
    self._action_queue.sort(key=rank_action, reverse=True)
  File "/tmp/Tuxemon/tuxemon/core/states/combat/combat.py", line 347, in rank_action
    primary_order = sort_order.index(sort)
ValueError: u'potion' is not in list
```

**Comment by bitcraft** [comment]
always potions crashing the game!  :P  Fixed by adding check if the "sort"
attribute was found or not and adding things to the sort order.  IF not
found, it will be executed last and a message printed.

Maybe in the future, we can have some sort of runtime test to see if items
or techniques will crash the game, for example by checking for unhandled
techniques, sort attribute, etc.

**Comment by ShadowApex** [comment]
Looks good now! Thanks @bitcraft !

More test coverage would be great, I agree. If we have some test scripts, I could include all tests to run when I get CI going again.

**Pull request merged**
