### PR TITLE
Esperanto translation

### PR DESCRIPTION
**Pull request by Clonewayx**
partial

### CODE REVIEW

**Comment by Airon90** [comment]
Via traduko estas plene da eraroj kaj estas nekompleta. Mi nun tradukos ĝin.

Your translation is full of error and is partial. I'm going to translate it now.

**Comment by Airon90** [comment]
I opened #224 with correct translations. Some keys needs to be translated but within one hour I will finish this work

**Comment by ShadowApex** [comment]
@Clonewayx Unless there's any objections, I was going to close this merge request and use @Airon90 's translation instead. Since I cannot verify which translation is more suitable, I welcome community input on which translation appears better.

**Comment by Airon90** [comment]
Se estas proponoj, bonvole ŝanĝu la dosieron [eo.json](/Tuxemon/Tuxemon/blob/development/tuxemon/resources/db/locale/eo.json). ;)

If you have a proposal, please edit the file [eo.json](/Tuxemon/Tuxemon/blob/development/tuxemon/resources/db/locale/eo.json). ;)

**Comment by IBPX** [comment]
@Airon90 Mi ne pensas ke "estis uzata" estas bona frazo; mi pensas, ke ĝi nur bonas angle, ne esperante. Mi pensas, ke `${{user}} uzis ${{name}}!`, `${{status}} damaĝis ${{name}}!`, kaj tiel plu estas pli natura en Esperanto.

Ankaŭ, `${{name}} estis venenigita!` ŝajnas esti anglaĵo. Tio signifus, ke `${{name}}` *estis* venegita, en la estinteco. `${{name}} veneniĝis!` pli bonas, laŭ mi.

**Comment by bitcraft** [comment]
TIL, Esperanto is kinda common in the Tuxemon community.

**Comment by Airon90** [comment]
@IBPX La problemo estas, ke uzante "estis uzata" la akuzativo ne necesas dume uzante "uzis" la variablo ${{name}} necesas akuzativon (```${{name}} estis uzata de ${{user}}!``` ne necesas la akuzativon dume ```${{user}} uzis ${{name}}!``` male, ĉar la korekta frazo estas ```${{user}} uzis ${{name}}n!```, esperante, ke ${{name}} estas nur unu vorto).
```${{name}} veneniĝis!``` estas tre bona traduko. Mi ŝanĝos ĝin.

@bitcraft LOL :D Thanks to Esperanto translation I found out that maybe support to cases is needed: in Esperanto I translated many keys using the passive form (```${{user}} used ${{name}}!``` became ```${{name}} has been used by ${{name}}!```) as in the first sentece ```${{name}}``` should be in accusative form (in Esperanto you just add ```n``` to the word(s). You should add ```n``` to the end of the sentence but the problem is that you don't know if ```${{name}} is just a word or there are more than one).

**Comment by bitcraft** [comment]
>  I found out that maybe support to cases is needed: in Esperanto I translated many keys using the passive form...You should add n to the end of the sentence but the problem is that you don't know if ```${{name}} is just a word or there are more than one).

@Airon90, thanks for working around the grammar limitations with our current translation setup.  For now, I'm perfectly happy to have "80% or better" translations...meaning a little awkwardness is OK.  I hope everyone else is OK with that, too....for now.

**Comment by Airon90** [comment]
Please, could someone close this PR as Tuxemon is already translated in Esperanto and we are reviewing the translation too (#232)

**Comment by Airon90** [comment]
@Clonewayx Bonvole partoprenu al diskuto en #232! :)

**Pull request closed without merging**
