### PR TITLE
Update build system

### PR DESCRIPTION
**Pull request by NeonFlames**
Switch from setup.py to pyproject.toml
Exclude .gitignore, .travis.yml, .vscode, .github
Remove version from README.md

### CODE REVIEW

**Comment by NeonFlames** [comment]
This time without issues (I hope).

**Review by kerizane — APPROVED** [review]

**Comment by kerizane** [comment]
Lgtm

@bitcraft ?

**Comment by NeonFlames** [comment]
Bitcraft is testing the flatpak to ensure everything is fine.

**Comment by NeonFlames** [comment]
Also upon merging if all goes well https://github.com/Tuxemon/Tuxemon/issues/1404 and https://github.com/Tuxemon/Tuxemon/pull/1411 are closable.

**Comment by NeonFlames** [comment]
I've tested the flatpak and it appears to work as intended.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
