### PR TITLE
fix logger

### PR DESCRIPTION
**Pull request by JaskRendix**
After a discussion in #1304 Here a PR that addresses some changes related to loggers. I would like to know if it makes sense as well as if there are plans to replace some loggers with something else. Some sort of guidelines. 

loggers based on import logging:
```
logger.warning, logger.debug, logger.critical, logger.exception, logger.info, logger.error
```
After a deep dive, I noticed that a series of file got this:
```
import logging
logger = logging.getLogger(__name__)
```
but without having a third **logger.something**. So it's only **import logging** and **logger = logging.getLogger(__name__)**

(if changes accepted)
```
formula.py
event/actions/play_map_animation
event/actions/variable_math
menu/menu.py
ui/draw.py
```
(no loggers inside)
```
map.py 
middleware.py 
player.py 
event/__init__.py (there is a logger but after #)
event/actions/battles_print 
event/actions/clear_variable 
event/actions/copy_variable 
event/actions/get_player_monster 
event/actions/print 
event/actions/random_integer 
event/actions/store_monster 
event/actions/withdraw_monster 
event/conditions/__init__.py 
event/conditions/variable_is 
item/economy.py 
item/conditions/__init__.py 
item/conditions/status.py 
item/effects/__init__.py 
menu/quantity.py 
states/combat/combat_animations.py 
states/combat/combat_menus.py 
states/pc/__init__.py 
states/persistance/load_menu.py 
states/splash/__init__.py 
states/start/__init__.py 
states/transition/__init__.py 
states/world/world_menus.py 
```

### CODE REVIEW

**Comment by kerizane** [comment]
Could you trigger one of these errors before and after the change so we can see what the output looks like?

set_monster_health with a negative value should work.

**Comment by JaskRendix** [comment]
No problem. Value **-0.5**

Before
```
Traceback (most recent call last):
  File "/home/robespierre/Tuxemon/run_tuxemon.py", line 87, in <module>
    main.main(load_slot=args.slot)
  File "/home/robespierre/Tuxemon/tuxemon/main.py", line 116, in main
    client.main()
  File "/home/robespierre/Tuxemon/tuxemon/client.py", line 315, in main
    update(clock_tick)
  File "/home/robespierre/Tuxemon/tuxemon/client.py", line 360, in update
    self.event_engine.update(time_delta)
  File "/home/robespierre/Tuxemon/tuxemon/event/eventengine.py", line 384, in update
    self.update_running_events(dt)
  File "/home/robespierre/Tuxemon/tuxemon/event/eventengine.py", line 465, in update_running_events
    action.start()
  File "/home/robespierre/Tuxemon/tuxemon/event/actions/set_monster_health.py", line 80, in start
    self.set_health(monster, monster_health)
  File "/home/robespierre/Tuxemon/tuxemon/event/actions/set_monster_health.py", line 67, in set_health
    raise ValueError
ValueError
```

After
```
Traceback (most recent call last):
  File "/home/robespierre/Tuxemon/run_tuxemon.py", line 87, in <module>
    main.main(load_slot=args.slot)
  File "/home/robespierre/Tuxemon/tuxemon/main.py", line 116, in main
    client.main()
  File "/home/robespierre/Tuxemon/tuxemon/client.py", line 315, in main
    update(clock_tick)
  File "/home/robespierre/Tuxemon/tuxemon/client.py", line 360, in update
    self.event_engine.update(time_delta)
  File "/home/robespierre/Tuxemon/tuxemon/event/eventengine.py", line 384, in update
    self.update_running_events(dt)
  File "/home/robespierre/Tuxemon/tuxemon/event/eventengine.py", line 465, in update_running_events
    action.start()
  File "/home/robespierre/Tuxemon/tuxemon/event/actions/set_monster_health.py", line 79, in start
    self.set_health(monster, monster_health)
  File "/home/robespierre/Tuxemon/tuxemon/event/actions/set_monster_health.py", line 66, in set_health
    raise ValueError("monster health must between 0 and 1")
ValueError: monster health must between 0 and 1
```

**Review by kerizane — APPROVED** [review]

**Comment by kerizane** [comment]
Clearly better, thanks.

**Comment by kerizane** [comment]
It would be great if you could audit the exception messages and check they are good enough.

For example, "ValueError: monster health must between 0 and 1" doesn't tell you what the value actually is.

**Pull request merged**
