### PR TITLE
Some techniques to aether + 8 conditions + 1 effect (switch - types)

### PR DESCRIPTION
**Pull request by JaskRendix**
PR follows #1850 and converts 18 techniques to aether.
- replaces **has_effect_give** with the more generic **has_effect_param**;
- creates **generic** in combat.py, that returns messages (post action), it'll clean up init combat from some hardcoded T.format;
- renames **touch** technique into **electroplate**;
- renames **wall_ice** technique into **ice_shield**;
- renames **status_overfeed** into **status_slow**;
- adds the field **nr_turn** in technique.py to track the status (so we can know how long the status afflicts the monster);
- updates icons and texts related to the renaming of conditions/techniques;
- adds new icons and texts related to the new conditions/techniques;

Before 21 out of 177 techniques are special
After 45 out of 177 techniques are special

- [Blood Nets](https://wiki.tuxemon.org/Blood_Nets) -> lifeleech target
- [Arcane Eye](https://wiki.tuxemon.org/Arcane_Eye) -> flame shield user
- [Undertaker](https://wiki.tuxemon.org/Undertaker) -> prickly target
- [Orbs](https://wiki.tuxemon.org/Orbs) -> **switch target,random** (random type for the opponent);
- [Terror](https://wiki.tuxemon.org/Terror) -> lockdown target
- [Negation](https://wiki.tuxemon.org/Negation) -> confused target
- [Feline](https://wiki.tuxemon.org/Feline) -> wild target
- [Canine](https://wiki.tuxemon.org/Canine) -> wild target
- [Cat Calling](https://wiki.tuxemon.org/Cat_Calling) -> nodding off target
- [Gold Digger](https://wiki.tuxemon.org/Gold_Digger)
- [Clock](https://wiki.tuxemon.org/Clock) -> confused target
- [Poison Courtship](https://wiki.tuxemon.org/Poison_Courtship)  > poison target
- [Barking](https://wiki.tuxemon.org/Barking) -> flinching target
- [Insanity](https://wiki.tuxemon.org/Insanity) > confused target
- [Breath](https://wiki.tuxemon.org/Breath)  -> nodding off target
- [Conjurer](https://wiki.tuxemon.org/Conjurer) -> confused target
- [Cloud Aether](https://wiki.tuxemon.org/Cloud_Aether)  -> **switch target&user,random** (random type for the user and opponent);
- [Clairaudience](https://wiki.tuxemon.org/Clairaudience)
- lowered [Maori](https://wiki.tuxemon.org/Maori) to 2.5 power, increased recharge to 2
- lowered [Ruby](https://wiki.tuxemon.org/Ruby) to 2.2 power, increased recharge to 2
- [Sylvan](https://wiki.tuxemon.org/Sylvan) -> **switch target,wood**
- [Ants](https://wiki.tuxemon.org/Ants)  -> **switch target,earth**
- [Fiery](https://wiki.tuxemon.org/Fiery)  -> **switch target,fire**
- [Electroplate](https://wiki.tuxemon.org/Electroplate)  -> **switch target,metal**
- [Gyser](https://wiki.tuxemon.org/Gyser) -> **switch target,water**;
- [Ubuntu](https://wiki.tuxemon.org/Ubuntu) -> **switch target,random** (random type for the opponent);

@Sanglorian tagging you all along, if you have any idea/advice, then feel free to share.

I would like to introduce **confusion**. You planned it (https://sanglorian.github.io/downloads/Tuxemon/Conditions%20spec.pdf)
```
If a monster tries to use a technique while Confused
• 50% chance that the technique is successfully selected.
• Otherwise, choose one of the monster’s other techniques at random.
• Display the text: “NAME gets muddled and uses TECHNIQUE NAME instead!”
```
but I don't see the malus, the monster still uses a technique.
Do you want auto-damage instead (itself or the other monster if 2vs2? or something else?
If not, confusion takes in consideration recharge?
A technique that needs to be recharged, so unusable by the monster, is among the random ones?

### CODE REVIEW

**Comment by Sanglorian** [comment]
Thanks @JaskRendix, those changes to Aether/special look good. 

It'd be great to have confusion added. The malus is that instead of choosing the most strategic technique, the player is stuck using a technique that might be sub par. For NPCs that already choose a random technique, it wouldn't make much difference (I agree skipping a turn if the NPC chooses a non-recharged technique could be a good extra component of it) but for players it would.

**Comment by JaskRendix** [comment]
@Sanglorian I was bored and I wanted to give different conditions, so I looked here: https://wiki.tuxemon.org/Other_technique_ideas#Conditions

I have implemented:
- **Flame Shield** (positive/replaced/replaced): Each time you are hit by a special attack take 1/16 your maximum hit points in damage.
- **Lockdown** (negative/replaced/replaced): Cannot use items.
- **Prickly** (positive/replaced/replaced): Each time you are hit by a melee or touch move, the attacker takes 1/8th your maximum HP in damage
- **Feedback** (positive/replaced/replaced): Each time you are hit by a ranged or reach move, the attacker takes 1/8th your maximum HP in damage
- **Wasting** (negative/replaced/replaced): Take #/16 of your maximum HP in damage each turn, where # = the number of turns that you have had this condition.
- **Flinching** (negative/replaced/replaced): 50% chance to miss your next turn. If you do miss your next turn, this condition ends.
- **Wild** (negative/replaced/replaced): 1/4 chance each turn that instead of using the chosen technique, you take 1/8 your maximum HP in unmodified damage.
- **Harpooned** (negative/replaced/replaced): If you swap out, take damage equal to 1/8th your maximum HP 
- **Earthy, Watery, Metallic, Woody, Fiery** That Type replaces your other type(s)  --> done, but it's not a status, it's an effect (like give, poison, etc.) called switch `"switch user,water"` or `"switch target,wood"`, so you can target opponent or your monster, I added the reset of types at the end of battle, so once the battle is ended, the type return the original one. In this way, if we increase the number of types, there are no issues

if you want we can insert it, but you need to give me (positive/negative, response to positive, response negative, check mine), then we need a text if successful the effect.

regarding the other ideas with my (opinion) regarding the difficult to implement, but it depends if I'm inspired or not, because I thought **wasting** was **tricky**, but it wasn't.
```
Retaliate: Keep track of all damage you take between entering this state and next doing damage. You do additional damage equal to damage taken. 
---> (normal)

Spiky: If an opponent swaps in, they take damage equal to 1/8th your maximum HP 
 ---> (it's feasible, but it needs some modifications)

Enlarged: Your maximum and current HP increase by 1/4, but you take that much damage when you lose this condition
---> (increasing the HP is fine, but the issue is when the monster loses the condition
I guess there is a message, but I have no idea where to put the action that remove the HP.
The damage is 1/4 of the new max HP?
Eg someone has 60 HP, status, to 75HP,
the 1/4 is based on the new total 18.75 (19)
or do we need to retrieve the 15?)

Charmed: Techniques have a 50% chance of not working if they target the enemy.
---> (tricky by reading, target the enemy?
do you mean if they hit? the concept is good)

Frightened: 1/8 chance each turn that you swap out for a randomly chosen alternative tuxemon on your team. If there are no others, you attempt to retreat.
---> (this can be tricky, so if there are no replacement, then 1/8 chance
of running for wild or forfeiting? it can be really tricky for 2vs2, but I like the concept)

Slow: Do nothing on the first turn that you become Slow. On each later round, do the thing that you were commanded to do one round earlier.
---> (hmmm... I don't know, skipping the turn when becoming slow,
then do the action the turn after? normal by reading)
```
let me know

remember ideas:
a **gold_digger** can take money from the NPC, but only in trainer battles (wild encounters you get damage), in trainer battles if it fails, you get damage, otherwise money. It remains to quantify damage and money.

**Comment by Sanglorian** [comment]
Very cool! I've clarified that for prickly and feedback, by Physical I meant melee/touch and by Special I meant ranged/reach. 

For enlarged, I was imagining that it would retrieve the "15", but honestly I don't think we really need that condition. 

For frightened, I see that is tricky for 2vs2. What if swapping out still happened if there was a replacement available, but running away only happens in wild battles - there's no forfeiting in trainer battles?

For charmed what I have in mind is some techniques are really "attacks" - they damage the opponent or give them a condition. These would have a 50% failure rate if used while charmed.

But honestly only implement these conditions if you're keen and if they're not too tricky - you've already given us a heap of new conditions to play around with. 

P.S. I like your way of doing switch element better than treating it as a condition. Makes me think we could have a bunch of items that switch a monster's element for the duration of a battle ("Fire Berry", etc?).

**Comment by JaskRendix** [comment]
@Sanglorian if you have any idea to associate one of these status with the 18 techniques above, feel free to share your idea.

> Very cool! I've clarified that for prickly and feedback, by Physical I meant melee/touch and by Special I meant ranged/reach.

Excellent, I'm going to update.

> For enlarged, I was imagining that it would retrieve the "15", but honestly I don't think we really need that condition.

I agree.

> For frightened, I see that is tricky for 2vs2. What if swapping out still happened if there was a replacement available, but running away only happens in wild battles - there's no forfeiting in trainer battles?

I need to think about, because it would be perfect for Terror.

> For charmed what I have in mind is some techniques are really "attacks" - they damage the opponent or give them a condition. These would have a 50% failure rate if used while charmed.

Now it makes sense.

> But honestly only implement these conditions if you're keen and if they're not too tricky - you've already given us a heap of new conditions to play around with.

Yeah, but Retaliate is intriguing me. Maybe I can come up with a solution.

> P.S. I like your way of doing switch element better than treating it as a condition. Makes me think we could have a bunch of items that switch a monster's element for the duration of a battle ("Fire Berry", etc?).

We can do it, it's just copy/paste the code into item effects, then set the item only usable during combat, task done.
The only issue is having enough fantasy to come up with names like "Fire Berry"!

**Comment by JaskRendix** [comment]
> Very cool! I've clarified that for prickly and feedback, by Physical I meant melee/touch and by Special I meant ranged/reach.

Excellent, I'm going to update.

> For enlarged, I was imagining that it would retrieve the "15", but honestly I don't think we really need that condition.

I agree.

> For frightened, I see that is tricky for 2vs2. What if swapping out still happened if there was a replacement available, but running away only happens in wild battles - there's no forfeiting in trainer battles?

I need to think about, because it would be perfect for Terror.

> For charmed what I have in mind is some techniques are really "attacks" - they damage the opponent or give them a condition. These would have a 50% failure rate if used while charmed.

Now it makes sense.

> But honestly only implement these conditions if you're keen and if they're not too tricky - you've already given us a heap of new conditions to play around with.

Yeah, but Retaliate is intriguing me. Maybe I can come up with a solution.

> P.S. I like your way of doing switch element better than treating it as a condition. Makes me think we could have a bunch of items that switch a monster's element for the duration of a battle ("Fire Berry", etc?).

We can do it, it's just copy/paste the code into item effects, then set the item only usable during combat, task done.
The only issue is having enough fantasy to come up with names like "Fire Berry"! We have berry inside Tuxemon as well as a **Metal Cherry**, both unused, we need at least other 3 items for wood, water and earth. I can split out and open another PR.

@Sanglorian I noticed that these two are similar, after you changed prickly:

- Flame Shield (positive/replaced/replaced): Creatures that hit you with a melee or touch attack take 1/16 your maximum hit points in damage.
- Prickly (positive/replaced/replaced): Each time you are hit by a melee or touch move, the attacker takes 1/8th your maximum HP in damage

it remains only **special** and **reliable**, which one? both?

Moreover, tell me what do you think:
- in Tuxepedia you are referring multiple times to the status **burn** (it would be really easy, like poison), we can add it;
- **Arcane Eye** what condition for Arcane? Flame Shield?
- **Undertaker** ... Prickly?
- **Terror** ... Lockdown?
- **Feline**... Wild?
- **Canine** ... Wild?
- **Gold Digger** ... Wasting? or the idea above?
- **Barking** ... Flinching?
- **Orbs** ...?
- **Clairaudience** ... Feedback?

let me know, 6 more aether techniques are good for us, it would be 45!

**Comment by Sanglorian** [comment]
> > P.S. I like your way of doing switch element better than treating it as a condition. Makes me think we could have a bunch of items that switch a monster's element for the duration of a battle ("Fire Berry", etc?).
> 
> We can do it, it's just copy/paste the code into item effects, then set the item only usable during combat, task done. The only issue is having enough fantasy to come up with names like "Fire Berry"! We have berry inside Tuxemon as well as a **Metal Cherry**, both unused, we need at least other 3 items for wood, water and earth. I can split out and open another PR.

> 
> @Sanglorian I noticed that these two are similar, after you changed prickly:
> 
>     * Flame Shield (positive/replaced/replaced): Creatures that hit you with a melee or touch attack take 1/16 your maximum hit points in damage.
> 
>     * Prickly (positive/replaced/replaced): Each time you are hit by a melee or touch move, the attacker takes 1/8th your maximum HP in damage

Agreed, sorry about that -- could we make Flame Shield the one for special techniques, and leave Prickly for the melee/touch techniques? 

> Moreover, tell me what do you think:
> 
>     * in Tuxepedia you are referring multiple times to the status **burn** (it would be really easy, like poison), we can add it;

Could be a good one - it could go damage like poisoned and halve Melee. 

>     * what about setting **[Sylvan](https://wiki.tuxemon.org/Sylvan)** as **aether** technique too, and the effect will be **switch target,xxx** (opposite of wood);
> 
>     * what about setting **[Ants](https://wiki.tuxemon.org/Ants)** as **aether** technique too, and the effect will be **switch target,xxx** (opposite of earth);
> 
>     * what about setting **[Fiery](https://wiki.tuxemon.org/Fiery)** as **aether** technique too, and the effect will be **switch target,xxx** (opposite of fire);
> 
>     * what about setting **[Touch](https://wiki.tuxemon.org/Touch)** as **aether** technique too, and the effect will be **switch target,xxx** (opposite of metal);
> 
>     * what about setting **[Gyser](https://wiki.tuxemon.org/Gyser)** as **aether** technique too, and the effect will be **switch target,xxx** (opposite of water);
> 
>     * what about setting **[Ubuntu](https://wiki.tuxemon.org/Ubuntu)** as **aether** technique too, and the effect will be **switch target,random** (random type for the opponent);

I think that's a good use of the techniques - but what if they set it _to_ that type, rather than the opposite? (I feel like Fiery should make the target a fire-type monster, for example). Instead of Touch, maybe call it Chrome or Electroplate?

>     * **Arcane Eye** what condition for Arcane? Flame Shield?
> 
>     * **Undertaker** ... Prickly?
> 
>     * **Terror** ... Lockdown?
> 
>     * **Feline**... Wild?
> 
>     * **Canine** ... Wild?
> 
>     * **Gold Digger** ... Wasting? or the idea above?
> 
>     * **Barking** ... Flinching?
> 
>     * **Cloud Aether** ... ?
> 
>     * **Orbs** ...?
> 
>     * **Clairaudience** ... Feedback?

Yes, I like all of those ideas, including the new gold_digger effect. 

What if Cloud Aether set a random type for both user and target?

And if Orbs was a Ranged technique rather than a Special one, and set a random type for the user while also doing damage? Then (assuming the switch type occurs before the attack) it could be a powerful attack but with a random type.

**Comment by JaskRendix** [comment]
> What if Cloud Aether set a random type for both user and target?

It sounds good, done!

> I think that's a good use of the techniques - but what if they set it to that type, rather than the opposite? (I feel like Fiery should make the target a fire-type monster, for example). Instead of Touch, maybe call it Chrome or Electroplate?

updated  [Electroplate](https://wiki.tuxemon.org/Electroplate);
updated switches;

> And if Orbs was a Ranged technique rather than a Special one, and set a random type for the user while also doing damage? Then (assuming the switch type occurs before the attack) it could be a powerful attack but with a random type.

updated [Orbs](https://wiki.tuxemon.org/Orbs)

> Agreed, sorry about that -- could we make Flame Shield the one for special techniques, and leave Prickly for the melee/touch techniques?

Done, it's great, it allowed me to get rid of 1 file, now everything is centralized for feedback, prickly and flame shield.

> Could be a good one - it could go damage like poisoned and halve Melee.

split #1853

added the status pages in Tuxepedia, feel free to change replaced, positive/negative, text, etc. All the changes will be synced here.
The only things missing are the icons and the texts
updated [Fluff Up](https://wiki.tuxemon.org/Fluff_Up)

**Comment by Sanglorian** [comment]
>  The only things missing are the icons and the texts updated [Fluff Up](https://wiki.tuxemon.org/Fluff_Up)

Thanks heaps! Have added icons and text, I think for all remaining conditions - please let me know if I've missed any.

**Comment by JaskRendix** [comment]
@Sanglorian everything seems fine, I'll check again later.
If everything is fine, then we are ready to go.
More additions/removals will be done in https://github.com/Tuxemon/Tuxemon/pull/1853

(here I added the icon_burn.png, since I added all the other icons).

**Comment by Sanglorian** [comment]
> @Sanglorian everything seems fine, I'll check again later. If everything is fine, then we are ready to go. More additions/removals will be done in #1853

Good to go from what I can see - thanks so much! A big expansion to the game.

**Review by kerizane — APPROVED** [review]

**Pull request merged**
