### PR TITLE
New Tuxemon/Techniques

### PR DESCRIPTION
**Pull request by josepharaoh99**
I have added the Dollfin and MagmaTurtle to the game, and created files for the newly added drip and bite animations

### CODE REVIEW

**Comment by josepharaoh99** [comment]
now i've updated some of the maps, as well as in adding a new city

**Comment by ShadowApex** [comment]
Hey josepharaoh99, thanks for the pull request. Unfortunately there's a few problems with this PR that prevents these changes from being accepted. In general, you should also try and open a pull request for each single feature you'd like to add, and not all at once. That way if there's a problem, I can merge other changes that didn't have any issues. 

I'll explain each issue I found in my review:

* When [contributing any new code or assets](https://github.com/Tuxemon/Tuxemon/wiki/contributing-code), please open your pull request to the *development* branch. The master branch is used only for "stable" releases of Tuxemon.
* When you changed "map1.tmx" to "boulder_city.tmx", the `transition_teleport` action from the downstairs room was not updated, and thus crashes the game when you try and go outside. If your changes introduce new crashes, they won't be accepted.
* Some maps are not using the **relative paths** to the tilesets they use. Currently when I load up any of your new maps in Tiled, they are looking for paths like the one below. This path does not exist on my machine. Take a look at [this post about contributing maps](https://forum.tuxemon.org/viewtopic.php?pid=55#p55) for a little more information. 
```xml
<image source="../../../../../tuxemon-unstable-latest/tuxemon-unstable-latest/tuxemon/resources/gfx/tilesets/My_tuxemon_sheet.png" width="128" height="208"/>
```
* The "mountain.png" tileset does not exist when trying to open "granite_city.tmx" or "granite_city_mountain_pass.tmx"
* You should make your outside maps *larger* than the walkable area. That way, when you play, the map appears to continue on forever and you don't see a black wall around the town/area. Check out [this post](https://forum.tuxemon.org/viewtopic.php?pid=64#p64) for some information on how to resize your maps and make barriers, etc.
* The new maps seem very large and mostly empty. I understand that these maps are just starting points, but try and make new areas more dense and interesting. Making the areas smaller might help with this.

I'd also like to note that if a map doesn't really fit in line with the lore of the official story, it may not be accepted in the official project, but you'll still be able to use these maps in user-created campaigns that Tuxemon will support in the future. If you'd like to contribute new areas to the official story, try posting your ideas in the forums first before opening a pull request.

If you have any other questions, let me know and I'd be happy to try and help. Thanks.

**Comment by josepharaoh99** [comment]
I am VERY sorry, ShadowApex! You see, I am a very new user to Github. What happened was that I added all of the json files and THEN created a pull request. I didn't know that any contributions afterwards on my fork would be added to the pull request. I will fix the problem on my fork. But meanwhile, I have a few questions.
1. What specific type of map are we looking for? I need some ideas!
2. is Pigabyte (https://cloud.githubusercontent.com/assets/15201616/11159504/19dfe2f2-8a2e-11e5-879d-3eb114bdde73.png) ready for a pull request? I made the top more 3d, but the top looks maybe too flat.
3. Are dollfin and magmaturtle ready to be added to the game?

Thanks for surviving my obviously uneducated efforts!

P.S. Sorry about the mountain tileset! It is found in this concept! https://cloud.githubusercontent.com/assets/15201616/11196318/3ccf3026-8c84-11e5-850a-0eadea1b468e.png

**Comment by ShadowApex** [comment]
It's all good.

>  1. What specific type of map are we looking for? I need some ideas!

Right now the world of Tuxemon is still quite early in its inception so it's hard at this time to give you some exact map ideas, but many of the ideas proposed by [jobashi's World Lore Suggestion](https://forum.tuxemon.org/viewtopic.php?id=39) are the direction that I'd like Tuxemon to go in. If you read his post, you might get some ideas on how we'd like to craft the world of Tuxemon. If you have a map idea, create a new forum topic to discuss it to see if it's a direction the community would like to go towards.

>  2. is Pigabyte (https://cloud.githubusercontent.com/assets/15201616/11159504/19dfe2f2-8a2e-11e5-879d-3eb114bdde73.png) ready for a pull request? I made the top more 3d, but the top looks maybe too flat.

I think the current Pigabyte proposed is still very stylistically different than the current sprites. As we start getting more graphical assets into Tuxemon, we need to more and more maintain a consistent aesthetic. Try tweaking your monster designs to try and fall more in line with some of the sprites currently in the project.

> 3. Are dollfin and magmaturtle ready to be added to the game?

* I think that Dollfin is a good sprite, but I feel it's too similar to Bigfin right now. I'd like to see what other versions would look like before including this sprite.

* "Magmaturtle" as a monster also feels stylistically different than some of the other sprites at the moment.

**Comment by Sanglorian** [comment]
> I think the current Pigabyte proposed is still very stylistically different than the current sprites. As we start getting more graphical assets into Tuxemon, we need to more and more maintain a consistent aesthetic. Try tweaking your monster designs to try and fall more in line with some of the sprites currently in the project.

Hey ShadowApex,

When I look at the existing monsters in Tuxemon, I don't see a unifying style - and as far as I can tell, Axylightl, Magmaturtle and so on are as similar to Bamboon and Nut as Bamboon and Nut are to one another.

If there is a specific style that you are after, I think you need to produce a style document that makes that clear. Otherwise, I think we should accept all contributions that meet a certain quality standard. I don't think the current system, of trying to divine a style from eight very different monsters, is viable.

**Comment by ShadowApex** [comment]
> If there is a specific style that you are after, I think you need to produce a style document that makes that clear. Otherwise, I think we should accept all contributions that meet a certain quality standard. I don't think the current system, of trying to divine a style from eight very different monsters, is viable. 

Creating a design style document is definitely something we'd like to get done at some point. Since we are still in early development from an artwork point of view, the overall design is still evolving and changing with time. You're right that I don't think we should necessarily divine a style from the current monsters, but I think that the currently included monsters have examples of aspects of their design that are things that we should include in our design style document. 

When you say that all contributions should be accepted that meet a certain quality standard, what is your current definition of a sprite that meets that standard? Would anything with a front, back, and menu image be considered quality enough to be accepted? I think that a style document would be a good place to define these standards, and I'll try and work on something to start with.

**Comment by josepharaoh99** [comment]
Okay, I'm kinda lost right now... I think I just need someone to tell me exactly what we need as far as a map right now-you know, i just need someone to tell me needed contributions right now. I am ready to add anything needed. I really like this game!!

**Comment by Sanglorian** [comment]
> When you say that all contributions should be accepted that meet a certain quality standard, what is your current definition of a sprite that meets that standard? Would anything with a front, back, and menu image be considered quality enough to be accepted? I think that a style document would be a good place to define these standards, and I'll try and work on something to start with.

At this point, I'd say any monster with the complete set of four sprites should be accepted. But when we reach a point where we have more monsters than we need, I think everyone who's contributed would understand if we choose monsters that are more expertly drawn over any existing monsters that are more basic. 

At that point, we may also have spriters who will redo existing monsters to look better/fit the agreed style better. Much better to get the monsters into the game and then worry about perfecting them than to wait until they're perfect, in my opinion. An extension of the "release early, release often" open source philosophy.

That said, I think it's great that you follow up each monster contribution with constructive criticism about shading and other pixel art details. That's a useful service for contributors, as well as helping the project. I just think at this early stage the best approach is to enthusiastically use all contributions, and improve them along the way.

**Comment by ShadowApex** [comment]
> At this point, I'd say any monster with the complete set of four sprites should be accepted. But when we reach a point where we have more monsters than we need, I think everyone who's contributed would understand if we choose monsters that are more expertly drawn over any existing monsters that are more basic.

> At that point, we may also have spriters who will redo existing monsters to look better/fit the agreed style better. Much better to get the monsters into the game and then worry about perfecting them than to wait until they're perfect, in my opinion. An extension of the "release early, release often" open source philosophy.

I think overall you're right about this. Once we have a larger selection of monsters available in the game we can start improving or replacing existing monsters to start heading towards a more cohesive style. I'll go ahead and accept contributions with completed front, back, and menu sprites. Thanks for your input on this Sanglorian.

**Comment by josepharaoh99** [comment]
I must agree with Sanglorian. Putting people's sprites in the game, even if they're not exactly what we want, will make them feel rewarded enough that hopefully they will feel more impelled to add new sprites. But, of course, we should not just add any sprites that come along-we need to make sure they have enough quality!

**Pull request closed without merging**
